# Run the metamorphic + negative robustness suites (generated by gen_robustness_tests.py).
#   Metamorphic: a known-good solve transformed (noise / dim / shift / rotate) must still solve and
#                the named anchor must track the transform  -> expect ALL PASS.
#   Negative:    garbage inputs (pure noise, random blobs) must NOT solve                -> expect ALL solved=false.
# Run `python gen_robustness_tests.py` first to (re)generate the images + CSVs.
$bd = "C:\Users\jon\source\repos\srcejon_sdrangel_fix\build-qt6"
$env:PATH = "C:\Qt\6.11.0\msvc2022_64\bin;$bd\bin;" + $env:PATH
$exe = "$bd\bin\plugins\featurecamera_star_tests.exe"
$tdir = "C:\Users\jon\source\repos\srcejon_sdrangel_fix\plugins\feature\camera\test"
Remove-Item Env:\QT_LOGGING_RULES -ErrorAction SilentlyContinue

$meta = "$tdir\robustness-meta.csv"
$neg  = "$tdir\robustness-neg.csv"
$negBlind = "$tdir\robustness-neg-blind.csv"
if (-not (Test-Path $meta)) {
  Write-Output "robustness CSVs not found -- run: python gen_robustness_tests.py"
  return
}

Write-Output "============ METAMORPHIC (expect ALL PASS) ============"
$m = & $exe $meta 2>&1
$m | Select-String -Pattern "^(PASS|FAIL) " -CaseSensitive | ForEach-Object { ($_ -split "catalog=")[0] }

function Report-Negatives($csv, $label) {
  if (-not (Test-Path $csv)) { return }
  Write-Output ""
  Write-Output ("============ NEGATIVE {0} (expect ALL solved=false) ============" -f $label)
  $n = & $exe $csv 2>&1
  foreach ($line in ($n | Select-String -Pattern "^(PASS|FAIL) " -CaseSensitive)) {
    $s = $line.ToString()
    if ($s -match "(\S+\.jpg).*?solved=(\w+)") {
      $img = $matches[1]; $solved = $matches[2]
      $verdict = if ($solved -eq "false") { "OK (rejected)" } else { "*** FALSE POSITIVE ***" }
      Write-Output ("  {0}  solved={1}  -> {2}" -f $img, $solved, $verdict)
    }
  }
}
Report-Negatives $neg "(guided)"
Report-Negatives $negBlind "(blind modes 0/1)"
