/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGAircraftReport.h
 *
 * Aircraft
 */

#ifndef SWGAircraftReport_H_
#define SWGAircraftReport_H_

#include <QJsonObject>


#include "SWGAircraftProtocolReport.h"
#include <QList>

#include "SWGObject.h"
#include "export.h"

namespace SWGSDRangel {

class SWG_API SWGAircraftReport: public SWGObject {
public:
    SWGAircraftReport();
    SWGAircraftReport(QString* json);
    virtual ~SWGAircraftReport();
    void init();
    void cleanup();

    virtual QString asJson () override;
    virtual QJsonObject* asJsonObject() override;
    virtual void fromJsonObject(QJsonObject &json) override;
    virtual SWGAircraftReport* fromJson(QString &jsonString) override;

    qint32 getAircraftCount();
    void setAircraftCount(qint32 aircraft_count);

    qint32 getActiveAircraftCount();
    void setActiveAircraftCount(qint32 active_aircraft_count);

    qint32 getFlightCount();
    void setFlightCount(qint32 flight_count);

    qint64 getMessageCount();
    void setMessageCount(qint64 message_count);

    QList<SWGAircraftProtocolReport*>* getProtocols();
    void setProtocols(QList<SWGAircraftProtocolReport*>* protocols);


    virtual bool isSet() override;

private:
    qint32 aircraft_count;
    bool m_aircraft_count_isSet;

    qint32 active_aircraft_count;
    bool m_active_aircraft_count_isSet;

    qint32 flight_count;
    bool m_flight_count_isSet;

    qint64 message_count;
    bool m_message_count_isSet;

    QList<SWGAircraftProtocolReport*>* protocols;
    bool m_protocols_isSet;

};

}

#endif /* SWGAircraftReport_H_ */
