/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGAircraftSettings.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace SWGSDRangel {

SWGAircraftSettings::SWGAircraftSettings(QString* json) {
    init();
    this->fromJson(*json);
}

SWGAircraftSettings::SWGAircraftSettings() {
    removal_mins = 0;
    m_removal_mins_isSet = false;
    adsb_position_mins = 0;
    m_adsb_position_mins_isSet = false;
    acars_position_mins = 0;
    m_acars_position_mins_isSet = false;
    retention_days = 0;
    m_retention_days_isSet = false;
    atc_labels = 0;
    m_atc_labels_isSet = false;
    atc_callsigns = 0;
    m_atc_callsigns_isSet = false;
    display_max_range_on_map = 0;
    m_display_max_range_on_map_isSet = false;
    favour_livery = 0;
    m_favour_livery_isSet = false;
    display_statistics = 0;
    m_display_statistics_isSet = false;
    display_chart = 0;
    m_display_chart_isSet = false;
    database_filename = nullptr;
    m_database_filename_isSet = false;
    disabled_sources = nullptr;
    m_disabled_sources_isSet = false;
    notification_settings = nullptr;
    m_notification_settings_isSet = false;
    title = nullptr;
    m_title_isSet = false;
    rgb_color = 0;
    m_rgb_color_isSet = false;
    use_reverse_api = 0;
    m_use_reverse_api_isSet = false;
    reverse_api_address = nullptr;
    m_reverse_api_address_isSet = false;
    reverse_api_port = 0;
    m_reverse_api_port_isSet = false;
    reverse_api_feature_set_index = 0;
    m_reverse_api_feature_set_index_isSet = false;
    reverse_api_feature_index = 0;
    m_reverse_api_feature_index_isSet = false;
    workspace_index = 0;
    m_workspace_index_isSet = false;
    rollup_state = nullptr;
    m_rollup_state_isSet = false;
}

SWGAircraftSettings::~SWGAircraftSettings() {
    this->cleanup();
}

void
SWGAircraftSettings::init() {
    removal_mins = 0;
    m_removal_mins_isSet = false;
    adsb_position_mins = 0;
    m_adsb_position_mins_isSet = false;
    acars_position_mins = 0;
    m_acars_position_mins_isSet = false;
    retention_days = 0;
    m_retention_days_isSet = false;
    atc_labels = 0;
    m_atc_labels_isSet = false;
    atc_callsigns = 0;
    m_atc_callsigns_isSet = false;
    display_max_range_on_map = 0;
    m_display_max_range_on_map_isSet = false;
    favour_livery = 0;
    m_favour_livery_isSet = false;
    display_statistics = 0;
    m_display_statistics_isSet = false;
    display_chart = 0;
    m_display_chart_isSet = false;
    database_filename = new QString("");
    m_database_filename_isSet = false;
    disabled_sources = new QList<QString*>();
    m_disabled_sources_isSet = false;
    notification_settings = new QList<SWGAircraftNotificationSettings*>();
    m_notification_settings_isSet = false;
    title = new QString("");
    m_title_isSet = false;
    rgb_color = 0;
    m_rgb_color_isSet = false;
    use_reverse_api = 0;
    m_use_reverse_api_isSet = false;
    reverse_api_address = new QString("");
    m_reverse_api_address_isSet = false;
    reverse_api_port = 0;
    m_reverse_api_port_isSet = false;
    reverse_api_feature_set_index = 0;
    m_reverse_api_feature_set_index_isSet = false;
    reverse_api_feature_index = 0;
    m_reverse_api_feature_index_isSet = false;
    workspace_index = 0;
    m_workspace_index_isSet = false;
    rollup_state = new SWGRollupState();
    m_rollup_state_isSet = false;
}

void
SWGAircraftSettings::cleanup() {










    if(database_filename != nullptr) { 
        delete database_filename;
    }
    if(disabled_sources != nullptr) { 
        auto arr = disabled_sources;
        for(auto o: *arr) { 
            delete o;
        }
        delete disabled_sources;
    }
    if(notification_settings != nullptr) { 
        auto arr = notification_settings;
        for(auto o: *arr) { 
            delete o;
        }
        delete notification_settings;
    }
    if(title != nullptr) { 
        delete title;
    }


    if(reverse_api_address != nullptr) { 
        delete reverse_api_address;
    }




    if(rollup_state != nullptr) { 
        delete rollup_state;
    }
}

SWGAircraftSettings*
SWGAircraftSettings::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGAircraftSettings::fromJsonObject(QJsonObject &pJson) {
    ::SWGSDRangel::setValue(&removal_mins, pJson["removalMins"], "qint32", "");
    
    ::SWGSDRangel::setValue(&adsb_position_mins, pJson["adsbPositionMins"], "qint32", "");
    
    ::SWGSDRangel::setValue(&acars_position_mins, pJson["acarsPositionMins"], "qint32", "");
    
    ::SWGSDRangel::setValue(&retention_days, pJson["retentionDays"], "qint32", "");
    
    ::SWGSDRangel::setValue(&atc_labels, pJson["atcLabels"], "qint32", "");
    
    ::SWGSDRangel::setValue(&atc_callsigns, pJson["atcCallsigns"], "qint32", "");
    
    ::SWGSDRangel::setValue(&display_max_range_on_map, pJson["displayMaxRangeOnMap"], "qint32", "");
    
    ::SWGSDRangel::setValue(&favour_livery, pJson["favourLivery"], "qint32", "");
    
    ::SWGSDRangel::setValue(&display_statistics, pJson["displayStatistics"], "qint32", "");
    
    ::SWGSDRangel::setValue(&display_chart, pJson["displayChart"], "qint32", "");
    
    ::SWGSDRangel::setValue(&database_filename, pJson["databaseFilename"], "QString", "QString");
    
    
    ::SWGSDRangel::setValue(&disabled_sources, pJson["disabledSources"], "QList", "QString");
    
    ::SWGSDRangel::setValue(&notification_settings, pJson["notificationSettings"], "QList", "SWGAircraftNotificationSettings");
    ::SWGSDRangel::setValue(&title, pJson["title"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&rgb_color, pJson["rgbColor"], "qint32", "");
    
    ::SWGSDRangel::setValue(&use_reverse_api, pJson["useReverseAPI"], "qint32", "");
    
    ::SWGSDRangel::setValue(&reverse_api_address, pJson["reverseAPIAddress"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&reverse_api_port, pJson["reverseAPIPort"], "qint32", "");
    
    ::SWGSDRangel::setValue(&reverse_api_feature_set_index, pJson["reverseAPIFeatureSetIndex"], "qint32", "");
    
    ::SWGSDRangel::setValue(&reverse_api_feature_index, pJson["reverseAPIFeatureIndex"], "qint32", "");
    
    ::SWGSDRangel::setValue(&workspace_index, pJson["workspaceIndex"], "qint32", "");
    
    ::SWGSDRangel::setValue(&rollup_state, pJson["rollupState"], "SWGRollupState", "SWGRollupState");
    
}

QString
SWGAircraftSettings::asJson ()
{
    QJsonObject* obj = this->asJsonObject();

    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    delete obj;
    return QString(bytes);
}

QJsonObject*
SWGAircraftSettings::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    if(m_removal_mins_isSet){
        obj->insert("removalMins", QJsonValue(removal_mins));
    }
    if(m_adsb_position_mins_isSet){
        obj->insert("adsbPositionMins", QJsonValue(adsb_position_mins));
    }
    if(m_acars_position_mins_isSet){
        obj->insert("acarsPositionMins", QJsonValue(acars_position_mins));
    }
    if(m_retention_days_isSet){
        obj->insert("retentionDays", QJsonValue(retention_days));
    }
    if(m_atc_labels_isSet){
        obj->insert("atcLabels", QJsonValue(atc_labels));
    }
    if(m_atc_callsigns_isSet){
        obj->insert("atcCallsigns", QJsonValue(atc_callsigns));
    }
    if(m_display_max_range_on_map_isSet){
        obj->insert("displayMaxRangeOnMap", QJsonValue(display_max_range_on_map));
    }
    if(m_favour_livery_isSet){
        obj->insert("favourLivery", QJsonValue(favour_livery));
    }
    if(m_display_statistics_isSet){
        obj->insert("displayStatistics", QJsonValue(display_statistics));
    }
    if(m_display_chart_isSet){
        obj->insert("displayChart", QJsonValue(display_chart));
    }
    if(database_filename != nullptr && *database_filename != QString("")){
        toJsonValue(QString("databaseFilename"), database_filename, obj, QString("QString"));
    }
    if(disabled_sources && disabled_sources->size() > 0){
        toJsonArray((QList<void*>*)disabled_sources, obj, "disabledSources", "QString");
    }
    if(notification_settings && notification_settings->size() > 0){
        toJsonArray((QList<void*>*)notification_settings, obj, "notificationSettings", "SWGAircraftNotificationSettings");
    }
    if(title != nullptr && *title != QString("")){
        toJsonValue(QString("title"), title, obj, QString("QString"));
    }
    if(m_rgb_color_isSet){
        obj->insert("rgbColor", QJsonValue(rgb_color));
    }
    if(m_use_reverse_api_isSet){
        obj->insert("useReverseAPI", QJsonValue(use_reverse_api));
    }
    if(reverse_api_address != nullptr && *reverse_api_address != QString("")){
        toJsonValue(QString("reverseAPIAddress"), reverse_api_address, obj, QString("QString"));
    }
    if(m_reverse_api_port_isSet){
        obj->insert("reverseAPIPort", QJsonValue(reverse_api_port));
    }
    if(m_reverse_api_feature_set_index_isSet){
        obj->insert("reverseAPIFeatureSetIndex", QJsonValue(reverse_api_feature_set_index));
    }
    if(m_reverse_api_feature_index_isSet){
        obj->insert("reverseAPIFeatureIndex", QJsonValue(reverse_api_feature_index));
    }
    if(m_workspace_index_isSet){
        obj->insert("workspaceIndex", QJsonValue(workspace_index));
    }
    if((rollup_state != nullptr) && (rollup_state->isSet())){
        toJsonValue(QString("rollupState"), rollup_state, obj, QString("SWGRollupState"));
    }

    return obj;
}

qint32
SWGAircraftSettings::getRemovalMins() {
    return removal_mins;
}
void
SWGAircraftSettings::setRemovalMins(qint32 removal_mins) {
    this->removal_mins = removal_mins;
    this->m_removal_mins_isSet = true;
}

qint32
SWGAircraftSettings::getAdsbPositionMins() {
    return adsb_position_mins;
}
void
SWGAircraftSettings::setAdsbPositionMins(qint32 adsb_position_mins) {
    this->adsb_position_mins = adsb_position_mins;
    this->m_adsb_position_mins_isSet = true;
}

qint32
SWGAircraftSettings::getAcarsPositionMins() {
    return acars_position_mins;
}
void
SWGAircraftSettings::setAcarsPositionMins(qint32 acars_position_mins) {
    this->acars_position_mins = acars_position_mins;
    this->m_acars_position_mins_isSet = true;
}

qint32
SWGAircraftSettings::getRetentionDays() {
    return retention_days;
}
void
SWGAircraftSettings::setRetentionDays(qint32 retention_days) {
    this->retention_days = retention_days;
    this->m_retention_days_isSet = true;
}

qint32
SWGAircraftSettings::getAtcLabels() {
    return atc_labels;
}
void
SWGAircraftSettings::setAtcLabels(qint32 atc_labels) {
    this->atc_labels = atc_labels;
    this->m_atc_labels_isSet = true;
}

qint32
SWGAircraftSettings::getAtcCallsigns() {
    return atc_callsigns;
}
void
SWGAircraftSettings::setAtcCallsigns(qint32 atc_callsigns) {
    this->atc_callsigns = atc_callsigns;
    this->m_atc_callsigns_isSet = true;
}

qint32
SWGAircraftSettings::getDisplayMaxRangeOnMap() {
    return display_max_range_on_map;
}
void
SWGAircraftSettings::setDisplayMaxRangeOnMap(qint32 display_max_range_on_map) {
    this->display_max_range_on_map = display_max_range_on_map;
    this->m_display_max_range_on_map_isSet = true;
}

qint32
SWGAircraftSettings::getFavourLivery() {
    return favour_livery;
}
void
SWGAircraftSettings::setFavourLivery(qint32 favour_livery) {
    this->favour_livery = favour_livery;
    this->m_favour_livery_isSet = true;
}

qint32
SWGAircraftSettings::getDisplayStatistics() {
    return display_statistics;
}
void
SWGAircraftSettings::setDisplayStatistics(qint32 display_statistics) {
    this->display_statistics = display_statistics;
    this->m_display_statistics_isSet = true;
}

qint32
SWGAircraftSettings::getDisplayChart() {
    return display_chart;
}
void
SWGAircraftSettings::setDisplayChart(qint32 display_chart) {
    this->display_chart = display_chart;
    this->m_display_chart_isSet = true;
}

QString*
SWGAircraftSettings::getDatabaseFilename() {
    return database_filename;
}
void
SWGAircraftSettings::setDatabaseFilename(QString* database_filename) {
    this->database_filename = database_filename;
    this->m_database_filename_isSet = true;
}

QList<QString*>*
SWGAircraftSettings::getDisabledSources() {
    return disabled_sources;
}
void
SWGAircraftSettings::setDisabledSources(QList<QString*>* disabled_sources) {
    this->disabled_sources = disabled_sources;
    this->m_disabled_sources_isSet = true;
}

QList<SWGAircraftNotificationSettings*>*
SWGAircraftSettings::getNotificationSettings() {
    return notification_settings;
}
void
SWGAircraftSettings::setNotificationSettings(QList<SWGAircraftNotificationSettings*>* notification_settings) {
    this->notification_settings = notification_settings;
    this->m_notification_settings_isSet = true;
}

QString*
SWGAircraftSettings::getTitle() {
    return title;
}
void
SWGAircraftSettings::setTitle(QString* title) {
    this->title = title;
    this->m_title_isSet = true;
}

qint32
SWGAircraftSettings::getRgbColor() {
    return rgb_color;
}
void
SWGAircraftSettings::setRgbColor(qint32 rgb_color) {
    this->rgb_color = rgb_color;
    this->m_rgb_color_isSet = true;
}

qint32
SWGAircraftSettings::getUseReverseApi() {
    return use_reverse_api;
}
void
SWGAircraftSettings::setUseReverseApi(qint32 use_reverse_api) {
    this->use_reverse_api = use_reverse_api;
    this->m_use_reverse_api_isSet = true;
}

QString*
SWGAircraftSettings::getReverseApiAddress() {
    return reverse_api_address;
}
void
SWGAircraftSettings::setReverseApiAddress(QString* reverse_api_address) {
    this->reverse_api_address = reverse_api_address;
    this->m_reverse_api_address_isSet = true;
}

qint32
SWGAircraftSettings::getReverseApiPort() {
    return reverse_api_port;
}
void
SWGAircraftSettings::setReverseApiPort(qint32 reverse_api_port) {
    this->reverse_api_port = reverse_api_port;
    this->m_reverse_api_port_isSet = true;
}

qint32
SWGAircraftSettings::getReverseApiFeatureSetIndex() {
    return reverse_api_feature_set_index;
}
void
SWGAircraftSettings::setReverseApiFeatureSetIndex(qint32 reverse_api_feature_set_index) {
    this->reverse_api_feature_set_index = reverse_api_feature_set_index;
    this->m_reverse_api_feature_set_index_isSet = true;
}

qint32
SWGAircraftSettings::getReverseApiFeatureIndex() {
    return reverse_api_feature_index;
}
void
SWGAircraftSettings::setReverseApiFeatureIndex(qint32 reverse_api_feature_index) {
    this->reverse_api_feature_index = reverse_api_feature_index;
    this->m_reverse_api_feature_index_isSet = true;
}

qint32
SWGAircraftSettings::getWorkspaceIndex() {
    return workspace_index;
}
void
SWGAircraftSettings::setWorkspaceIndex(qint32 workspace_index) {
    this->workspace_index = workspace_index;
    this->m_workspace_index_isSet = true;
}

SWGRollupState*
SWGAircraftSettings::getRollupState() {
    return rollup_state;
}
void
SWGAircraftSettings::setRollupState(SWGRollupState* rollup_state) {
    this->rollup_state = rollup_state;
    this->m_rollup_state_isSet = true;
}


bool
SWGAircraftSettings::isSet(){
    bool isObjectUpdated = false;
    do{
        if(m_removal_mins_isSet){
            isObjectUpdated = true; break;
        }
        if(m_adsb_position_mins_isSet){
            isObjectUpdated = true; break;
        }
        if(m_acars_position_mins_isSet){
            isObjectUpdated = true; break;
        }
        if(m_retention_days_isSet){
            isObjectUpdated = true; break;
        }
        if(m_atc_labels_isSet){
            isObjectUpdated = true; break;
        }
        if(m_atc_callsigns_isSet){
            isObjectUpdated = true; break;
        }
        if(m_display_max_range_on_map_isSet){
            isObjectUpdated = true; break;
        }
        if(m_favour_livery_isSet){
            isObjectUpdated = true; break;
        }
        if(m_display_statistics_isSet){
            isObjectUpdated = true; break;
        }
        if(m_display_chart_isSet){
            isObjectUpdated = true; break;
        }
        if(database_filename && *database_filename != QString("")){
            isObjectUpdated = true; break;
        }
        if(disabled_sources && (disabled_sources->size() > 0)){
            isObjectUpdated = true; break;
        }
        if(notification_settings && (notification_settings->size() > 0)){
            isObjectUpdated = true; break;
        }
        if(title && *title != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_rgb_color_isSet){
            isObjectUpdated = true; break;
        }
        if(m_use_reverse_api_isSet){
            isObjectUpdated = true; break;
        }
        if(reverse_api_address && *reverse_api_address != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_reverse_api_port_isSet){
            isObjectUpdated = true; break;
        }
        if(m_reverse_api_feature_set_index_isSet){
            isObjectUpdated = true; break;
        }
        if(m_reverse_api_feature_index_isSet){
            isObjectUpdated = true; break;
        }
        if(m_workspace_index_isSet){
            isObjectUpdated = true; break;
        }
        if(rollup_state && rollup_state->isSet()){
            isObjectUpdated = true; break;
        }
    }while(false);
    return isObjectUpdated;
}
}

