/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGAircraftNotificationSettings.h
 *
 * A rule matched against each aircraft, which speaks a phrase or runs a command when it matches
 */

#ifndef SWGAircraftNotificationSettings_H_
#define SWGAircraftNotificationSettings_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"
#include "export.h"

namespace SWGSDRangel {

class SWG_API SWGAircraftNotificationSettings: public SWGObject {
public:
    SWGAircraftNotificationSettings();
    SWGAircraftNotificationSettings(QString* json);
    virtual ~SWGAircraftNotificationSettings();
    void init();
    void cleanup();

    virtual QString asJson () override;
    virtual QJsonObject* asJsonObject() override;
    virtual void fromJsonObject(QJsonObject &json) override;
    virtual SWGAircraftNotificationSettings* fromJson(QString &jsonString) override;

    qint32 getMatchColumn();
    void setMatchColumn(qint32 match_column);

    QString* getRegExp();
    void setRegExp(QString* reg_exp);

    QString* getSpeech();
    void setSpeech(QString* speech);

    QString* getCommand();
    void setCommand(QString* command);


    virtual bool isSet() override;

private:
    qint32 match_column;
    bool m_match_column_isSet;

    QString* reg_exp;
    bool m_reg_exp_isSet;

    QString* speech;
    bool m_speech_isSet;

    QString* command;
    bool m_command_isSet;

};

}

#endif /* SWGAircraftNotificationSettings_H_ */
