/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGACARSDemodSettings.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace SWGSDRangel {

SWGACARSDemodSettings::SWGACARSDemodSettings(QString* json) {
    init();
    this->fromJson(*json);
}

SWGACARSDemodSettings::SWGACARSDemodSettings() {
    input_frequency_offset = 0L;
    m_input_frequency_offset_isSet = false;
    mode = 0;
    m_mode_isSet = false;
    aero_channel = 0;
    m_aero_channel_isSet = false;
    rf_bandwidth = 0.0f;
    m_rf_bandwidth_isSet = false;
    correlation_threshold = 0.0f;
    m_correlation_threshold_isSet = false;
    filter = nullptr;
    m_filter_isSet = false;
    filter_column = 0;
    m_filter_column_isSet = false;
    hide_no_info = 0;
    m_hide_no_info_isSet = false;
    show_date = 0;
    m_show_date_isSet = false;
    display_photos = 0;
    m_display_photos_isSet = false;
    display_chart = 0;
    m_display_chart_isSet = false;
    udp_enabled = 0;
    m_udp_enabled_isSet = false;
    udp_address = nullptr;
    m_udp_address_isSet = false;
    udp_port = 0;
    m_udp_port_isSet = false;
    log_filename = nullptr;
    m_log_filename_isSet = false;
    log_enabled = 0;
    m_log_enabled_isSet = false;
    feed_enabled = 0;
    m_feed_enabled_isSet = false;
    feed_station_id = nullptr;
    m_feed_station_id_isSet = false;
    feed_airframes = 0;
    m_feed_airframes_isSet = false;
    feed_airframes_host = nullptr;
    m_feed_airframes_host_isSet = false;
    feed_airframes_port = 0;
    m_feed_airframes_port_isSet = false;
    feed_airframes_tcp = 0;
    m_feed_airframes_tcp_isSet = false;
    feed_avdelphi = 0;
    m_feed_avdelphi_isSet = false;
    feed_avdelphi_host = nullptr;
    m_feed_avdelphi_host_isSet = false;
    feed_avdelphi_port = 0;
    m_feed_avdelphi_port_isSet = false;
    feed_avdelphi_tcp = 0;
    m_feed_avdelphi_tcp_isSet = false;
    scope_ch1 = 0;
    m_scope_ch1_isSet = false;
    scope_ch2 = 0;
    m_scope_ch2_isSet = false;
    rgb_color = 0;
    m_rgb_color_isSet = false;
    title = nullptr;
    m_title_isSet = false;
    stream_index = 0;
    m_stream_index_isSet = false;
    use_reverse_api = 0;
    m_use_reverse_api_isSet = false;
    reverse_api_address = nullptr;
    m_reverse_api_address_isSet = false;
    reverse_api_port = 0;
    m_reverse_api_port_isSet = false;
    reverse_api_device_index = 0;
    m_reverse_api_device_index_isSet = false;
    reverse_api_channel_index = 0;
    m_reverse_api_channel_index_isSet = false;
    workspace_index = 0;
    m_workspace_index_isSet = false;
    scope_config = nullptr;
    m_scope_config_isSet = false;
    channel_marker = nullptr;
    m_channel_marker_isSet = false;
    rollup_state = nullptr;
    m_rollup_state_isSet = false;
}

SWGACARSDemodSettings::~SWGACARSDemodSettings() {
    this->cleanup();
}

void
SWGACARSDemodSettings::init() {
    input_frequency_offset = 0L;
    m_input_frequency_offset_isSet = false;
    mode = 0;
    m_mode_isSet = false;
    aero_channel = 0;
    m_aero_channel_isSet = false;
    rf_bandwidth = 0.0f;
    m_rf_bandwidth_isSet = false;
    correlation_threshold = 0.0f;
    m_correlation_threshold_isSet = false;
    filter = new QString("");
    m_filter_isSet = false;
    filter_column = 0;
    m_filter_column_isSet = false;
    hide_no_info = 0;
    m_hide_no_info_isSet = false;
    show_date = 0;
    m_show_date_isSet = false;
    display_photos = 0;
    m_display_photos_isSet = false;
    display_chart = 0;
    m_display_chart_isSet = false;
    udp_enabled = 0;
    m_udp_enabled_isSet = false;
    udp_address = new QString("");
    m_udp_address_isSet = false;
    udp_port = 0;
    m_udp_port_isSet = false;
    log_filename = new QString("");
    m_log_filename_isSet = false;
    log_enabled = 0;
    m_log_enabled_isSet = false;
    feed_enabled = 0;
    m_feed_enabled_isSet = false;
    feed_station_id = new QString("");
    m_feed_station_id_isSet = false;
    feed_airframes = 0;
    m_feed_airframes_isSet = false;
    feed_airframes_host = new QString("");
    m_feed_airframes_host_isSet = false;
    feed_airframes_port = 0;
    m_feed_airframes_port_isSet = false;
    feed_airframes_tcp = 0;
    m_feed_airframes_tcp_isSet = false;
    feed_avdelphi = 0;
    m_feed_avdelphi_isSet = false;
    feed_avdelphi_host = new QString("");
    m_feed_avdelphi_host_isSet = false;
    feed_avdelphi_port = 0;
    m_feed_avdelphi_port_isSet = false;
    feed_avdelphi_tcp = 0;
    m_feed_avdelphi_tcp_isSet = false;
    scope_ch1 = 0;
    m_scope_ch1_isSet = false;
    scope_ch2 = 0;
    m_scope_ch2_isSet = false;
    rgb_color = 0;
    m_rgb_color_isSet = false;
    title = new QString("");
    m_title_isSet = false;
    stream_index = 0;
    m_stream_index_isSet = false;
    use_reverse_api = 0;
    m_use_reverse_api_isSet = false;
    reverse_api_address = new QString("");
    m_reverse_api_address_isSet = false;
    reverse_api_port = 0;
    m_reverse_api_port_isSet = false;
    reverse_api_device_index = 0;
    m_reverse_api_device_index_isSet = false;
    reverse_api_channel_index = 0;
    m_reverse_api_channel_index_isSet = false;
    workspace_index = 0;
    m_workspace_index_isSet = false;
    scope_config = new SWGGLScope();
    m_scope_config_isSet = false;
    channel_marker = new SWGChannelMarker();
    m_channel_marker_isSet = false;
    rollup_state = new SWGRollupState();
    m_rollup_state_isSet = false;
}

void
SWGACARSDemodSettings::cleanup() {





    if(filter != nullptr) { 
        delete filter;
    }






    if(udp_address != nullptr) { 
        delete udp_address;
    }

    if(log_filename != nullptr) { 
        delete log_filename;
    }


    if(feed_station_id != nullptr) { 
        delete feed_station_id;
    }

    if(feed_airframes_host != nullptr) { 
        delete feed_airframes_host;
    }



    if(feed_avdelphi_host != nullptr) { 
        delete feed_avdelphi_host;
    }





    if(title != nullptr) { 
        delete title;
    }


    if(reverse_api_address != nullptr) { 
        delete reverse_api_address;
    }




    if(scope_config != nullptr) { 
        delete scope_config;
    }
    if(channel_marker != nullptr) { 
        delete channel_marker;
    }
    if(rollup_state != nullptr) { 
        delete rollup_state;
    }
}

SWGACARSDemodSettings*
SWGACARSDemodSettings::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGACARSDemodSettings::fromJsonObject(QJsonObject &pJson) {
    ::SWGSDRangel::setValue(&input_frequency_offset, pJson["inputFrequencyOffset"], "qint64", "");
    
    ::SWGSDRangel::setValue(&mode, pJson["mode"], "qint32", "");
    
    ::SWGSDRangel::setValue(&aero_channel, pJson["aeroChannel"], "qint32", "");
    
    ::SWGSDRangel::setValue(&rf_bandwidth, pJson["rfBandwidth"], "float", "");
    
    ::SWGSDRangel::setValue(&correlation_threshold, pJson["correlationThreshold"], "float", "");
    
    ::SWGSDRangel::setValue(&filter, pJson["filter"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&filter_column, pJson["filterColumn"], "qint32", "");
    
    ::SWGSDRangel::setValue(&hide_no_info, pJson["hideNoInfo"], "qint32", "");
    
    ::SWGSDRangel::setValue(&show_date, pJson["showDate"], "qint32", "");
    
    ::SWGSDRangel::setValue(&display_photos, pJson["displayPhotos"], "qint32", "");
    
    ::SWGSDRangel::setValue(&display_chart, pJson["displayChart"], "qint32", "");
    
    ::SWGSDRangel::setValue(&udp_enabled, pJson["udpEnabled"], "qint32", "");
    
    ::SWGSDRangel::setValue(&udp_address, pJson["udpAddress"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&udp_port, pJson["udpPort"], "qint32", "");
    
    ::SWGSDRangel::setValue(&log_filename, pJson["logFilename"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&log_enabled, pJson["logEnabled"], "qint32", "");
    
    ::SWGSDRangel::setValue(&feed_enabled, pJson["feedEnabled"], "qint32", "");
    
    ::SWGSDRangel::setValue(&feed_station_id, pJson["feedStationId"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&feed_airframes, pJson["feedAirframes"], "qint32", "");
    
    ::SWGSDRangel::setValue(&feed_airframes_host, pJson["feedAirframesHost"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&feed_airframes_port, pJson["feedAirframesPort"], "qint32", "");
    
    ::SWGSDRangel::setValue(&feed_airframes_tcp, pJson["feedAirframesTcp"], "qint32", "");
    
    ::SWGSDRangel::setValue(&feed_avdelphi, pJson["feedAvdelphi"], "qint32", "");
    
    ::SWGSDRangel::setValue(&feed_avdelphi_host, pJson["feedAvdelphiHost"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&feed_avdelphi_port, pJson["feedAvdelphiPort"], "qint32", "");
    
    ::SWGSDRangel::setValue(&feed_avdelphi_tcp, pJson["feedAvdelphiTcp"], "qint32", "");
    
    ::SWGSDRangel::setValue(&scope_ch1, pJson["scopeCh1"], "qint32", "");
    
    ::SWGSDRangel::setValue(&scope_ch2, pJson["scopeCh2"], "qint32", "");
    
    ::SWGSDRangel::setValue(&rgb_color, pJson["rgbColor"], "qint32", "");
    
    ::SWGSDRangel::setValue(&title, pJson["title"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&stream_index, pJson["streamIndex"], "qint32", "");
    
    ::SWGSDRangel::setValue(&use_reverse_api, pJson["useReverseAPI"], "qint32", "");
    
    ::SWGSDRangel::setValue(&reverse_api_address, pJson["reverseAPIAddress"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&reverse_api_port, pJson["reverseAPIPort"], "qint32", "");
    
    ::SWGSDRangel::setValue(&reverse_api_device_index, pJson["reverseAPIDeviceIndex"], "qint32", "");
    
    ::SWGSDRangel::setValue(&reverse_api_channel_index, pJson["reverseAPIChannelIndex"], "qint32", "");
    
    ::SWGSDRangel::setValue(&workspace_index, pJson["workspaceIndex"], "qint32", "");
    
    ::SWGSDRangel::setValue(&scope_config, pJson["scopeConfig"], "SWGGLScope", "SWGGLScope");
    
    ::SWGSDRangel::setValue(&channel_marker, pJson["channelMarker"], "SWGChannelMarker", "SWGChannelMarker");
    
    ::SWGSDRangel::setValue(&rollup_state, pJson["rollupState"], "SWGRollupState", "SWGRollupState");
    
}

QString
SWGACARSDemodSettings::asJson ()
{
    QJsonObject* obj = this->asJsonObject();

    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    delete obj;
    return QString(bytes);
}

QJsonObject*
SWGACARSDemodSettings::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    if(m_input_frequency_offset_isSet){
        obj->insert("inputFrequencyOffset", QJsonValue(input_frequency_offset));
    }
    if(m_mode_isSet){
        obj->insert("mode", QJsonValue(mode));
    }
    if(m_aero_channel_isSet){
        obj->insert("aeroChannel", QJsonValue(aero_channel));
    }
    if(m_rf_bandwidth_isSet){
        obj->insert("rfBandwidth", QJsonValue(rf_bandwidth));
    }
    if(m_correlation_threshold_isSet){
        obj->insert("correlationThreshold", QJsonValue(correlation_threshold));
    }
    if(filter != nullptr && *filter != QString("")){
        toJsonValue(QString("filter"), filter, obj, QString("QString"));
    }
    if(m_filter_column_isSet){
        obj->insert("filterColumn", QJsonValue(filter_column));
    }
    if(m_hide_no_info_isSet){
        obj->insert("hideNoInfo", QJsonValue(hide_no_info));
    }
    if(m_show_date_isSet){
        obj->insert("showDate", QJsonValue(show_date));
    }
    if(m_display_photos_isSet){
        obj->insert("displayPhotos", QJsonValue(display_photos));
    }
    if(m_display_chart_isSet){
        obj->insert("displayChart", QJsonValue(display_chart));
    }
    if(m_udp_enabled_isSet){
        obj->insert("udpEnabled", QJsonValue(udp_enabled));
    }
    if(udp_address != nullptr && *udp_address != QString("")){
        toJsonValue(QString("udpAddress"), udp_address, obj, QString("QString"));
    }
    if(m_udp_port_isSet){
        obj->insert("udpPort", QJsonValue(udp_port));
    }
    if(log_filename != nullptr && *log_filename != QString("")){
        toJsonValue(QString("logFilename"), log_filename, obj, QString("QString"));
    }
    if(m_log_enabled_isSet){
        obj->insert("logEnabled", QJsonValue(log_enabled));
    }
    if(m_feed_enabled_isSet){
        obj->insert("feedEnabled", QJsonValue(feed_enabled));
    }
    if(feed_station_id != nullptr && *feed_station_id != QString("")){
        toJsonValue(QString("feedStationId"), feed_station_id, obj, QString("QString"));
    }
    if(m_feed_airframes_isSet){
        obj->insert("feedAirframes", QJsonValue(feed_airframes));
    }
    if(feed_airframes_host != nullptr && *feed_airframes_host != QString("")){
        toJsonValue(QString("feedAirframesHost"), feed_airframes_host, obj, QString("QString"));
    }
    if(m_feed_airframes_port_isSet){
        obj->insert("feedAirframesPort", QJsonValue(feed_airframes_port));
    }
    if(m_feed_airframes_tcp_isSet){
        obj->insert("feedAirframesTcp", QJsonValue(feed_airframes_tcp));
    }
    if(m_feed_avdelphi_isSet){
        obj->insert("feedAvdelphi", QJsonValue(feed_avdelphi));
    }
    if(feed_avdelphi_host != nullptr && *feed_avdelphi_host != QString("")){
        toJsonValue(QString("feedAvdelphiHost"), feed_avdelphi_host, obj, QString("QString"));
    }
    if(m_feed_avdelphi_port_isSet){
        obj->insert("feedAvdelphiPort", QJsonValue(feed_avdelphi_port));
    }
    if(m_feed_avdelphi_tcp_isSet){
        obj->insert("feedAvdelphiTcp", QJsonValue(feed_avdelphi_tcp));
    }
    if(m_scope_ch1_isSet){
        obj->insert("scopeCh1", QJsonValue(scope_ch1));
    }
    if(m_scope_ch2_isSet){
        obj->insert("scopeCh2", QJsonValue(scope_ch2));
    }
    if(m_rgb_color_isSet){
        obj->insert("rgbColor", QJsonValue(rgb_color));
    }
    if(title != nullptr && *title != QString("")){
        toJsonValue(QString("title"), title, obj, QString("QString"));
    }
    if(m_stream_index_isSet){
        obj->insert("streamIndex", QJsonValue(stream_index));
    }
    if(m_use_reverse_api_isSet){
        obj->insert("useReverseAPI", QJsonValue(use_reverse_api));
    }
    if(reverse_api_address != nullptr && *reverse_api_address != QString("")){
        toJsonValue(QString("reverseAPIAddress"), reverse_api_address, obj, QString("QString"));
    }
    if(m_reverse_api_port_isSet){
        obj->insert("reverseAPIPort", QJsonValue(reverse_api_port));
    }
    if(m_reverse_api_device_index_isSet){
        obj->insert("reverseAPIDeviceIndex", QJsonValue(reverse_api_device_index));
    }
    if(m_reverse_api_channel_index_isSet){
        obj->insert("reverseAPIChannelIndex", QJsonValue(reverse_api_channel_index));
    }
    if(m_workspace_index_isSet){
        obj->insert("workspaceIndex", QJsonValue(workspace_index));
    }
    if((scope_config != nullptr) && (scope_config->isSet())){
        toJsonValue(QString("scopeConfig"), scope_config, obj, QString("SWGGLScope"));
    }
    if((channel_marker != nullptr) && (channel_marker->isSet())){
        toJsonValue(QString("channelMarker"), channel_marker, obj, QString("SWGChannelMarker"));
    }
    if((rollup_state != nullptr) && (rollup_state->isSet())){
        toJsonValue(QString("rollupState"), rollup_state, obj, QString("SWGRollupState"));
    }

    return obj;
}

qint64
SWGACARSDemodSettings::getInputFrequencyOffset() {
    return input_frequency_offset;
}
void
SWGACARSDemodSettings::setInputFrequencyOffset(qint64 input_frequency_offset) {
    this->input_frequency_offset = input_frequency_offset;
    this->m_input_frequency_offset_isSet = true;
}

qint32
SWGACARSDemodSettings::getMode() {
    return mode;
}
void
SWGACARSDemodSettings::setMode(qint32 mode) {
    this->mode = mode;
    this->m_mode_isSet = true;
}

qint32
SWGACARSDemodSettings::getAeroChannel() {
    return aero_channel;
}
void
SWGACARSDemodSettings::setAeroChannel(qint32 aero_channel) {
    this->aero_channel = aero_channel;
    this->m_aero_channel_isSet = true;
}

float
SWGACARSDemodSettings::getRfBandwidth() {
    return rf_bandwidth;
}
void
SWGACARSDemodSettings::setRfBandwidth(float rf_bandwidth) {
    this->rf_bandwidth = rf_bandwidth;
    this->m_rf_bandwidth_isSet = true;
}

float
SWGACARSDemodSettings::getCorrelationThreshold() {
    return correlation_threshold;
}
void
SWGACARSDemodSettings::setCorrelationThreshold(float correlation_threshold) {
    this->correlation_threshold = correlation_threshold;
    this->m_correlation_threshold_isSet = true;
}

QString*
SWGACARSDemodSettings::getFilter() {
    return filter;
}
void
SWGACARSDemodSettings::setFilter(QString* filter) {
    this->filter = filter;
    this->m_filter_isSet = true;
}

qint32
SWGACARSDemodSettings::getFilterColumn() {
    return filter_column;
}
void
SWGACARSDemodSettings::setFilterColumn(qint32 filter_column) {
    this->filter_column = filter_column;
    this->m_filter_column_isSet = true;
}

qint32
SWGACARSDemodSettings::getHideNoInfo() {
    return hide_no_info;
}
void
SWGACARSDemodSettings::setHideNoInfo(qint32 hide_no_info) {
    this->hide_no_info = hide_no_info;
    this->m_hide_no_info_isSet = true;
}

qint32
SWGACARSDemodSettings::getShowDate() {
    return show_date;
}
void
SWGACARSDemodSettings::setShowDate(qint32 show_date) {
    this->show_date = show_date;
    this->m_show_date_isSet = true;
}

qint32
SWGACARSDemodSettings::getDisplayPhotos() {
    return display_photos;
}
void
SWGACARSDemodSettings::setDisplayPhotos(qint32 display_photos) {
    this->display_photos = display_photos;
    this->m_display_photos_isSet = true;
}

qint32
SWGACARSDemodSettings::getDisplayChart() {
    return display_chart;
}
void
SWGACARSDemodSettings::setDisplayChart(qint32 display_chart) {
    this->display_chart = display_chart;
    this->m_display_chart_isSet = true;
}

qint32
SWGACARSDemodSettings::getUdpEnabled() {
    return udp_enabled;
}
void
SWGACARSDemodSettings::setUdpEnabled(qint32 udp_enabled) {
    this->udp_enabled = udp_enabled;
    this->m_udp_enabled_isSet = true;
}

QString*
SWGACARSDemodSettings::getUdpAddress() {
    return udp_address;
}
void
SWGACARSDemodSettings::setUdpAddress(QString* udp_address) {
    this->udp_address = udp_address;
    this->m_udp_address_isSet = true;
}

qint32
SWGACARSDemodSettings::getUdpPort() {
    return udp_port;
}
void
SWGACARSDemodSettings::setUdpPort(qint32 udp_port) {
    this->udp_port = udp_port;
    this->m_udp_port_isSet = true;
}

QString*
SWGACARSDemodSettings::getLogFilename() {
    return log_filename;
}
void
SWGACARSDemodSettings::setLogFilename(QString* log_filename) {
    this->log_filename = log_filename;
    this->m_log_filename_isSet = true;
}

qint32
SWGACARSDemodSettings::getLogEnabled() {
    return log_enabled;
}
void
SWGACARSDemodSettings::setLogEnabled(qint32 log_enabled) {
    this->log_enabled = log_enabled;
    this->m_log_enabled_isSet = true;
}

qint32
SWGACARSDemodSettings::getFeedEnabled() {
    return feed_enabled;
}
void
SWGACARSDemodSettings::setFeedEnabled(qint32 feed_enabled) {
    this->feed_enabled = feed_enabled;
    this->m_feed_enabled_isSet = true;
}

QString*
SWGACARSDemodSettings::getFeedStationId() {
    return feed_station_id;
}
void
SWGACARSDemodSettings::setFeedStationId(QString* feed_station_id) {
    this->feed_station_id = feed_station_id;
    this->m_feed_station_id_isSet = true;
}

qint32
SWGACARSDemodSettings::getFeedAirframes() {
    return feed_airframes;
}
void
SWGACARSDemodSettings::setFeedAirframes(qint32 feed_airframes) {
    this->feed_airframes = feed_airframes;
    this->m_feed_airframes_isSet = true;
}

QString*
SWGACARSDemodSettings::getFeedAirframesHost() {
    return feed_airframes_host;
}
void
SWGACARSDemodSettings::setFeedAirframesHost(QString* feed_airframes_host) {
    this->feed_airframes_host = feed_airframes_host;
    this->m_feed_airframes_host_isSet = true;
}

qint32
SWGACARSDemodSettings::getFeedAirframesPort() {
    return feed_airframes_port;
}
void
SWGACARSDemodSettings::setFeedAirframesPort(qint32 feed_airframes_port) {
    this->feed_airframes_port = feed_airframes_port;
    this->m_feed_airframes_port_isSet = true;
}

qint32
SWGACARSDemodSettings::getFeedAirframesTcp() {
    return feed_airframes_tcp;
}
void
SWGACARSDemodSettings::setFeedAirframesTcp(qint32 feed_airframes_tcp) {
    this->feed_airframes_tcp = feed_airframes_tcp;
    this->m_feed_airframes_tcp_isSet = true;
}

qint32
SWGACARSDemodSettings::getFeedAvdelphi() {
    return feed_avdelphi;
}
void
SWGACARSDemodSettings::setFeedAvdelphi(qint32 feed_avdelphi) {
    this->feed_avdelphi = feed_avdelphi;
    this->m_feed_avdelphi_isSet = true;
}

QString*
SWGACARSDemodSettings::getFeedAvdelphiHost() {
    return feed_avdelphi_host;
}
void
SWGACARSDemodSettings::setFeedAvdelphiHost(QString* feed_avdelphi_host) {
    this->feed_avdelphi_host = feed_avdelphi_host;
    this->m_feed_avdelphi_host_isSet = true;
}

qint32
SWGACARSDemodSettings::getFeedAvdelphiPort() {
    return feed_avdelphi_port;
}
void
SWGACARSDemodSettings::setFeedAvdelphiPort(qint32 feed_avdelphi_port) {
    this->feed_avdelphi_port = feed_avdelphi_port;
    this->m_feed_avdelphi_port_isSet = true;
}

qint32
SWGACARSDemodSettings::getFeedAvdelphiTcp() {
    return feed_avdelphi_tcp;
}
void
SWGACARSDemodSettings::setFeedAvdelphiTcp(qint32 feed_avdelphi_tcp) {
    this->feed_avdelphi_tcp = feed_avdelphi_tcp;
    this->m_feed_avdelphi_tcp_isSet = true;
}

qint32
SWGACARSDemodSettings::getScopeCh1() {
    return scope_ch1;
}
void
SWGACARSDemodSettings::setScopeCh1(qint32 scope_ch1) {
    this->scope_ch1 = scope_ch1;
    this->m_scope_ch1_isSet = true;
}

qint32
SWGACARSDemodSettings::getScopeCh2() {
    return scope_ch2;
}
void
SWGACARSDemodSettings::setScopeCh2(qint32 scope_ch2) {
    this->scope_ch2 = scope_ch2;
    this->m_scope_ch2_isSet = true;
}

qint32
SWGACARSDemodSettings::getRgbColor() {
    return rgb_color;
}
void
SWGACARSDemodSettings::setRgbColor(qint32 rgb_color) {
    this->rgb_color = rgb_color;
    this->m_rgb_color_isSet = true;
}

QString*
SWGACARSDemodSettings::getTitle() {
    return title;
}
void
SWGACARSDemodSettings::setTitle(QString* title) {
    this->title = title;
    this->m_title_isSet = true;
}

qint32
SWGACARSDemodSettings::getStreamIndex() {
    return stream_index;
}
void
SWGACARSDemodSettings::setStreamIndex(qint32 stream_index) {
    this->stream_index = stream_index;
    this->m_stream_index_isSet = true;
}

qint32
SWGACARSDemodSettings::getUseReverseApi() {
    return use_reverse_api;
}
void
SWGACARSDemodSettings::setUseReverseApi(qint32 use_reverse_api) {
    this->use_reverse_api = use_reverse_api;
    this->m_use_reverse_api_isSet = true;
}

QString*
SWGACARSDemodSettings::getReverseApiAddress() {
    return reverse_api_address;
}
void
SWGACARSDemodSettings::setReverseApiAddress(QString* reverse_api_address) {
    this->reverse_api_address = reverse_api_address;
    this->m_reverse_api_address_isSet = true;
}

qint32
SWGACARSDemodSettings::getReverseApiPort() {
    return reverse_api_port;
}
void
SWGACARSDemodSettings::setReverseApiPort(qint32 reverse_api_port) {
    this->reverse_api_port = reverse_api_port;
    this->m_reverse_api_port_isSet = true;
}

qint32
SWGACARSDemodSettings::getReverseApiDeviceIndex() {
    return reverse_api_device_index;
}
void
SWGACARSDemodSettings::setReverseApiDeviceIndex(qint32 reverse_api_device_index) {
    this->reverse_api_device_index = reverse_api_device_index;
    this->m_reverse_api_device_index_isSet = true;
}

qint32
SWGACARSDemodSettings::getReverseApiChannelIndex() {
    return reverse_api_channel_index;
}
void
SWGACARSDemodSettings::setReverseApiChannelIndex(qint32 reverse_api_channel_index) {
    this->reverse_api_channel_index = reverse_api_channel_index;
    this->m_reverse_api_channel_index_isSet = true;
}

qint32
SWGACARSDemodSettings::getWorkspaceIndex() {
    return workspace_index;
}
void
SWGACARSDemodSettings::setWorkspaceIndex(qint32 workspace_index) {
    this->workspace_index = workspace_index;
    this->m_workspace_index_isSet = true;
}

SWGGLScope*
SWGACARSDemodSettings::getScopeConfig() {
    return scope_config;
}
void
SWGACARSDemodSettings::setScopeConfig(SWGGLScope* scope_config) {
    this->scope_config = scope_config;
    this->m_scope_config_isSet = true;
}

SWGChannelMarker*
SWGACARSDemodSettings::getChannelMarker() {
    return channel_marker;
}
void
SWGACARSDemodSettings::setChannelMarker(SWGChannelMarker* channel_marker) {
    this->channel_marker = channel_marker;
    this->m_channel_marker_isSet = true;
}

SWGRollupState*
SWGACARSDemodSettings::getRollupState() {
    return rollup_state;
}
void
SWGACARSDemodSettings::setRollupState(SWGRollupState* rollup_state) {
    this->rollup_state = rollup_state;
    this->m_rollup_state_isSet = true;
}


bool
SWGACARSDemodSettings::isSet(){
    bool isObjectUpdated = false;
    do{
        if(m_input_frequency_offset_isSet){
            isObjectUpdated = true; break;
        }
        if(m_mode_isSet){
            isObjectUpdated = true; break;
        }
        if(m_aero_channel_isSet){
            isObjectUpdated = true; break;
        }
        if(m_rf_bandwidth_isSet){
            isObjectUpdated = true; break;
        }
        if(m_correlation_threshold_isSet){
            isObjectUpdated = true; break;
        }
        if(filter && *filter != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_filter_column_isSet){
            isObjectUpdated = true; break;
        }
        if(m_hide_no_info_isSet){
            isObjectUpdated = true; break;
        }
        if(m_show_date_isSet){
            isObjectUpdated = true; break;
        }
        if(m_display_photos_isSet){
            isObjectUpdated = true; break;
        }
        if(m_display_chart_isSet){
            isObjectUpdated = true; break;
        }
        if(m_udp_enabled_isSet){
            isObjectUpdated = true; break;
        }
        if(udp_address && *udp_address != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_udp_port_isSet){
            isObjectUpdated = true; break;
        }
        if(log_filename && *log_filename != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_log_enabled_isSet){
            isObjectUpdated = true; break;
        }
        if(m_feed_enabled_isSet){
            isObjectUpdated = true; break;
        }
        if(feed_station_id && *feed_station_id != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_feed_airframes_isSet){
            isObjectUpdated = true; break;
        }
        if(feed_airframes_host && *feed_airframes_host != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_feed_airframes_port_isSet){
            isObjectUpdated = true; break;
        }
        if(m_feed_airframes_tcp_isSet){
            isObjectUpdated = true; break;
        }
        if(m_feed_avdelphi_isSet){
            isObjectUpdated = true; break;
        }
        if(feed_avdelphi_host && *feed_avdelphi_host != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_feed_avdelphi_port_isSet){
            isObjectUpdated = true; break;
        }
        if(m_feed_avdelphi_tcp_isSet){
            isObjectUpdated = true; break;
        }
        if(m_scope_ch1_isSet){
            isObjectUpdated = true; break;
        }
        if(m_scope_ch2_isSet){
            isObjectUpdated = true; break;
        }
        if(m_rgb_color_isSet){
            isObjectUpdated = true; break;
        }
        if(title && *title != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_stream_index_isSet){
            isObjectUpdated = true; break;
        }
        if(m_use_reverse_api_isSet){
            isObjectUpdated = true; break;
        }
        if(reverse_api_address && *reverse_api_address != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_reverse_api_port_isSet){
            isObjectUpdated = true; break;
        }
        if(m_reverse_api_device_index_isSet){
            isObjectUpdated = true; break;
        }
        if(m_reverse_api_channel_index_isSet){
            isObjectUpdated = true; break;
        }
        if(m_workspace_index_isSet){
            isObjectUpdated = true; break;
        }
        if(scope_config && scope_config->isSet()){
            isObjectUpdated = true; break;
        }
        if(channel_marker && channel_marker->isSet()){
            isObjectUpdated = true; break;
        }
        if(rollup_state && rollup_state->isSet()){
            isObjectUpdated = true; break;
        }
    }while(false);
    return isObjectUpdated;
}
}

