/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGAircraftActions.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace SWGSDRangel {

SWGAircraftActions::SWGAircraftActions(QString* json) {
    init();
    this->fromJson(*json);
}

SWGAircraftActions::SWGAircraftActions() {
    select_icao = nullptr;
    m_select_icao_isSet = false;
    select_registration = nullptr;
    m_select_registration_isSet = false;
    select_flight = nullptr;
    m_select_flight_isSet = false;
}

SWGAircraftActions::~SWGAircraftActions() {
    this->cleanup();
}

void
SWGAircraftActions::init() {
    select_icao = new QString("");
    m_select_icao_isSet = false;
    select_registration = new QString("");
    m_select_registration_isSet = false;
    select_flight = new QString("");
    m_select_flight_isSet = false;
}

void
SWGAircraftActions::cleanup() {
    if(select_icao != nullptr) { 
        delete select_icao;
    }
    if(select_registration != nullptr) { 
        delete select_registration;
    }
    if(select_flight != nullptr) { 
        delete select_flight;
    }
}

SWGAircraftActions*
SWGAircraftActions::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGAircraftActions::fromJsonObject(QJsonObject &pJson) {
    ::SWGSDRangel::setValue(&select_icao, pJson["selectIcao"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&select_registration, pJson["selectRegistration"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&select_flight, pJson["selectFlight"], "QString", "QString");
    
}

QString
SWGAircraftActions::asJson ()
{
    QJsonObject* obj = this->asJsonObject();

    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    delete obj;
    return QString(bytes);
}

QJsonObject*
SWGAircraftActions::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    if(select_icao != nullptr && *select_icao != QString("")){
        toJsonValue(QString("selectIcao"), select_icao, obj, QString("QString"));
    }
    if(select_registration != nullptr && *select_registration != QString("")){
        toJsonValue(QString("selectRegistration"), select_registration, obj, QString("QString"));
    }
    if(select_flight != nullptr && *select_flight != QString("")){
        toJsonValue(QString("selectFlight"), select_flight, obj, QString("QString"));
    }

    return obj;
}

QString*
SWGAircraftActions::getSelectIcao() {
    return select_icao;
}
void
SWGAircraftActions::setSelectIcao(QString* select_icao) {
    this->select_icao = select_icao;
    this->m_select_icao_isSet = true;
}

QString*
SWGAircraftActions::getSelectRegistration() {
    return select_registration;
}
void
SWGAircraftActions::setSelectRegistration(QString* select_registration) {
    this->select_registration = select_registration;
    this->m_select_registration_isSet = true;
}

QString*
SWGAircraftActions::getSelectFlight() {
    return select_flight;
}
void
SWGAircraftActions::setSelectFlight(QString* select_flight) {
    this->select_flight = select_flight;
    this->m_select_flight_isSet = true;
}


bool
SWGAircraftActions::isSet(){
    bool isObjectUpdated = false;
    do{
        if(select_icao && *select_icao != QString("")){
            isObjectUpdated = true; break;
        }
        if(select_registration && *select_registration != QString("")){
            isObjectUpdated = true; break;
        }
        if(select_flight && *select_flight != QString("")){
            isObjectUpdated = true; break;
        }
    }while(false);
    return isObjectUpdated;
}
}

