/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGCameraReport.h
 *
 * Camera feature report
 */

#ifndef SWGCameraReport_H_
#define SWGCameraReport_H_

#include <QJsonObject>


#include <QList>
#include <QString>

#include "SWGObject.h"
#include "export.h"

namespace SWGSDRangel {

class SWG_API SWGCameraReport: public SWGObject {
public:
    SWGCameraReport();
    SWGCameraReport(QString* json);
    virtual ~SWGCameraReport();
    void init();
    void cleanup();

    virtual QString asJson () override;
    virtual QJsonObject* asJsonObject() override;
    virtual void fromJsonObject(QJsonObject &json) override;
    virtual SWGCameraReport* fromJson(QString &jsonString) override;

    qint32 getRunningState();
    void setRunningState(qint32 running_state);

    QString* getCaptureDateTime();
    void setCaptureDateTime(QString* capture_date_time);

    QList<QString*>* getDetectedObjectClasses();
    void setDetectedObjectClasses(QList<QString*>* detected_object_classes);

    qint32 getMotionDetected();
    void setMotionDetected(qint32 motion_detected);

    float getCloudCoveragePercent();
    void setCloudCoveragePercent(float cloud_coverage_percent);

    qint32 getCloudCoverageValid();
    void setCloudCoverageValid(qint32 cloud_coverage_valid);

    qint32 getThermalValid();
    void setThermalValid(qint32 thermal_valid);

    QString* getThermalDecoderName();
    void setThermalDecoderName(QString* thermal_decoder_name);

    float getThermalMarkerTemperatureC();
    void setThermalMarkerTemperatureC(float thermal_marker_temperature_c);

    float getThermalMinimumC();
    void setThermalMinimumC(float thermal_minimum_c);

    float getThermalMaximumC();
    void setThermalMaximumC(float thermal_maximum_c);

    float getThermalMeanC();
    void setThermalMeanC(float thermal_mean_c);


    virtual bool isSet() override;

private:
    qint32 running_state;
    bool m_running_state_isSet;

    QString* capture_date_time;
    bool m_capture_date_time_isSet;

    QList<QString*>* detected_object_classes;
    bool m_detected_object_classes_isSet;

    qint32 motion_detected;
    bool m_motion_detected_isSet;

    float cloud_coverage_percent;
    bool m_cloud_coverage_percent_isSet;

    qint32 cloud_coverage_valid;
    bool m_cloud_coverage_valid_isSet;

    qint32 thermal_valid;
    bool m_thermal_valid_isSet;

    QString* thermal_decoder_name;
    bool m_thermal_decoder_name_isSet;

    float thermal_marker_temperature_c;
    bool m_thermal_marker_temperature_c_isSet;

    float thermal_minimum_c;
    bool m_thermal_minimum_c_isSet;

    float thermal_maximum_c;
    bool m_thermal_maximum_c_isSet;

    float thermal_mean_c;
    bool m_thermal_mean_c_isSet;

};

}

#endif /* SWGCameraReport_H_ */
