/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGCameraSettings.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace SWGSDRangel {

SWGCameraSettings::SWGCameraSettings(QString* json) {
    init();
    this->fromJson(*json);
}

SWGCameraSettings::SWGCameraSettings() {
    title = nullptr;
    m_title_isSet = false;
    rgb_color = 0;
    m_rgb_color_isSet = false;
    camera_protocol = nullptr;
    m_camera_protocol_isSet = false;
    camera_id = nullptr;
    m_camera_id_isSet = false;
    camera_description = nullptr;
    m_camera_description_isSet = false;
    resolution_width = 0;
    m_resolution_width_isSet = false;
    resolution_height = 0;
    m_resolution_height_isSet = false;
    frames_per_second = 0;
    m_frames_per_second_isSet = false;
    capture_mode = 0;
    m_capture_mode_isSet = false;
    capture_interval = 0.0;
    m_capture_interval_isSet = false;
    capture_interval_units = 0;
    m_capture_interval_units_isSet = false;
    exposure_time_ms = 0.0;
    m_exposure_time_ms_isSet = false;
    iso_sensitivity = 0;
    m_iso_sensitivity_isSet = false;
    alpaca_discovery_enabled = 0;
    m_alpaca_discovery_enabled_isSet = false;
    alpaca_api_log_enabled = 0;
    m_alpaca_api_log_enabled_isSet = false;
    alpaca_host = nullptr;
    m_alpaca_host_isSet = false;
    alpaca_port = 0;
    m_alpaca_port_isSet = false;
    alpaca_focuser_enabled = 0;
    m_alpaca_focuser_enabled_isSet = false;
    alpaca_focuser_host = nullptr;
    m_alpaca_focuser_host_isSet = false;
    alpaca_focuser_port = 0;
    m_alpaca_focuser_port_isSet = false;
    alpaca_focuser_device_number = 0;
    m_alpaca_focuser_device_number_isSet = false;
    alpaca_focus_position = 0;
    m_alpaca_focus_position_isSet = false;
    alpaca_focus_step_size = 0;
    m_alpaca_focus_step_size_isSet = false;
    alpaca_filter_wheel_enabled = 0;
    m_alpaca_filter_wheel_enabled_isSet = false;
    alpaca_filter_wheel_host = nullptr;
    m_alpaca_filter_wheel_host_isSet = false;
    alpaca_filter_wheel_port = 0;
    m_alpaca_filter_wheel_port_isSet = false;
    alpaca_filter_wheel_device_number = 0;
    m_alpaca_filter_wheel_device_number_isSet = false;
    alpaca_filter_wheel_position = 0;
    m_alpaca_filter_wheel_position_isSet = false;
    alpaca_bin_x = 0;
    m_alpaca_bin_x_isSet = false;
    alpaca_bin_y = 0;
    m_alpaca_bin_y_isSet = false;
    alpaca_num_x = 0;
    m_alpaca_num_x_isSet = false;
    alpaca_num_y = 0;
    m_alpaca_num_y_isSet = false;
    alpaca_start_x = 0;
    m_alpaca_start_x_isSet = false;
    alpaca_start_y = 0;
    m_alpaca_start_y_isSet = false;
    alpaca_gain = 0;
    m_alpaca_gain_isSet = false;
    alpaca_offset = 0;
    m_alpaca_offset_isSet = false;
    alpaca_readout_mode = 0;
    m_alpaca_readout_mode_isSet = false;
    save_image = 0;
    m_save_image_isSet = false;
    image_file_name = nullptr;
    m_image_file_name_isSet = false;
    save_video = 0;
    m_save_video_isSet = false;
    video_file_camera_path = nullptr;
    m_video_file_camera_path_isSet = false;
    video_file_name = nullptr;
    m_video_file_name_isSet = false;
    video_hw_acceleration = 0;
    m_video_hw_acceleration_isSet = false;
    post_process_white_balance_mode = 0;
    m_post_process_white_balance_mode_isSet = false;
    post_process_white_balance_red_gain = 0.0;
    m_post_process_white_balance_red_gain_isSet = false;
    post_process_white_balance_green_gain = 0.0;
    m_post_process_white_balance_green_gain_isSet = false;
    post_process_white_balance_blue_gain = 0.0;
    m_post_process_white_balance_blue_gain_isSet = false;
    saturation = 0.0;
    m_saturation_isSet = false;
    gamma = 0.0;
    m_gamma_isSet = false;
    brightness = 0.0;
    m_brightness_isSet = false;
    contrast = 0.0;
    m_contrast_isSet = false;
    gaussian_blur = 0;
    m_gaussian_blur_isSet = false;
    median_blur = 0;
    m_median_blur_isSet = false;
    sharpen = 0.0;
    m_sharpen_isSet = false;
    sobel_edge = 0.0;
    m_sobel_edge_isSet = false;
    flip_x = 0;
    m_flip_x_isSet = false;
    flip_y = 0;
    m_flip_y_isSet = false;
    invert_colors = 0;
    m_invert_colors_isSet = false;
    overlay_date_time = 0;
    m_overlay_date_time_isSet = false;
    date_time_color = 0;
    m_date_time_color_isSet = false;
    date_time_format = nullptr;
    m_date_time_format_isSet = false;
    date_time_pos_x = 0;
    m_date_time_pos_x_isSet = false;
    date_time_pos_y = 0;
    m_date_time_pos_y_isSet = false;
    overlay_text = 0;
    m_overlay_text_isSet = false;
    overlay_text_string = nullptr;
    m_overlay_text_string_isSet = false;
    overlay_text_color = 0;
    m_overlay_text_color_isSet = false;
    overlay_text_font_family = nullptr;
    m_overlay_text_font_family_isSet = false;
    overlay_text_font_scale = 0.0;
    m_overlay_text_font_scale_isSet = false;
    overlay_text_pos_x = 0;
    m_overlay_text_pos_x_isSet = false;
    overlay_text_pos_y = 0;
    m_overlay_text_pos_y_isSet = false;
    diff_mask = 0;
    m_diff_mask_isSet = false;
    diff_threshold = 0;
    m_diff_threshold_isSet = false;
    dilation_size = 0;
    m_dilation_size_isSet = false;
    diff_mask_history_frames = 0;
    m_diff_mask_history_frames_isSet = false;
    diff_mask_close_size = 0;
    m_diff_mask_close_size_isSet = false;
    detection_roi_x = 0;
    m_detection_roi_x_isSet = false;
    detection_roi_y = 0;
    m_detection_roi_y_isSet = false;
    detection_roi_width = 0;
    m_detection_roi_width_isSet = false;
    detection_roi_height = 0;
    m_detection_roi_height_isSet = false;
    motion_detect = 0;
    m_motion_detect_isSet = false;
    motion_history = 0;
    m_motion_history_isSet = false;
    motion_var_threshold = 0.0;
    m_motion_var_threshold_isSet = false;
    motion_detect_shadows = 0;
    m_motion_detect_shadows_isSet = false;
    motion_open_size = 0;
    m_motion_open_size_isSet = false;
    motion_close_size = 0;
    m_motion_close_size_isSet = false;
    motion_persistence_frames = 0;
    m_motion_persistence_frames_isSet = false;
    motion_box_color = 0;
    m_motion_box_color_isSet = false;
    min_contour_area = 0;
    m_min_contour_area_isSet = false;
    video_post_process = 0;
    m_video_post_process_isSet = false;
    overlay_spectrum = 0;
    m_overlay_spectrum_isSet = false;
    spectrum_device = nullptr;
    m_spectrum_device_isSet = false;
    spectrum_offset_x = 0;
    m_spectrum_offset_x_isSet = false;
    spectrum_offset_y = 0;
    m_spectrum_offset_y_isSet = false;
    spectrum_scale = 0.0;
    m_spectrum_scale_isSet = false;
    yolo_enabled = 0;
    m_yolo_enabled_isSet = false;
    yolo_model_path = nullptr;
    m_yolo_model_path_isSet = false;
    yolo_labels_path = nullptr;
    m_yolo_labels_path_isSet = false;
    yolo_conf_threshold = 0.0;
    m_yolo_conf_threshold_isSet = false;
    yolo_nms_threshold = 0.0;
    m_yolo_nms_threshold_isSet = false;
    yolo_box_color = 0;
    m_yolo_box_color_isSet = false;
    yolo_disappear_debounce = 0.0;
    m_yolo_disappear_debounce_isSet = false;
    yolo_dnn_target = 0;
    m_yolo_dnn_target_isSet = false;
    object_device_settings = nullptr;
    m_object_device_settings_isSet = false;
    audio_mute = 0;
    m_audio_mute_isSet = false;
    audio_device_name = nullptr;
    m_audio_device_name_isSet = false;
    white_balance_mode = 0;
    m_white_balance_mode_isSet = false;
    exposure_compensation = 0.0;
    m_exposure_compensation_isSet = false;
    focus_mode = 0;
    m_focus_mode_isSet = false;
    focus_distance = 0.0;
    m_focus_distance_isSet = false;
    zoom_factor = 0.0;
    m_zoom_factor_isSet = false;
    use_reverse_api = 0;
    m_use_reverse_api_isSet = false;
    reverse_api_address = nullptr;
    m_reverse_api_address_isSet = false;
    reverse_api_port = 0;
    m_reverse_api_port_isSet = false;
    reverse_api_feature_set_index = 0;
    m_reverse_api_feature_set_index_isSet = false;
    reverse_api_feature_index = 0;
    m_reverse_api_feature_index_isSet = false;
    rollup_state = nullptr;
    m_rollup_state_isSet = false;
    workspace_index = 0;
    m_workspace_index_isSet = false;
}

SWGCameraSettings::~SWGCameraSettings() {
    this->cleanup();
}

void
SWGCameraSettings::init() {
    title = new QString("");
    m_title_isSet = false;
    rgb_color = 0;
    m_rgb_color_isSet = false;
    camera_protocol = new QString("");
    m_camera_protocol_isSet = false;
    camera_id = new QString("");
    m_camera_id_isSet = false;
    camera_description = new QString("");
    m_camera_description_isSet = false;
    resolution_width = 0;
    m_resolution_width_isSet = false;
    resolution_height = 0;
    m_resolution_height_isSet = false;
    frames_per_second = 0;
    m_frames_per_second_isSet = false;
    capture_mode = 0;
    m_capture_mode_isSet = false;
    capture_interval = 0.0;
    m_capture_interval_isSet = false;
    capture_interval_units = 0;
    m_capture_interval_units_isSet = false;
    exposure_time_ms = 0.0;
    m_exposure_time_ms_isSet = false;
    iso_sensitivity = 0;
    m_iso_sensitivity_isSet = false;
    alpaca_discovery_enabled = 0;
    m_alpaca_discovery_enabled_isSet = false;
    alpaca_api_log_enabled = 0;
    m_alpaca_api_log_enabled_isSet = false;
    alpaca_host = new QString("");
    m_alpaca_host_isSet = false;
    alpaca_port = 0;
    m_alpaca_port_isSet = false;
    alpaca_focuser_enabled = 0;
    m_alpaca_focuser_enabled_isSet = false;
    alpaca_focuser_host = new QString("");
    m_alpaca_focuser_host_isSet = false;
    alpaca_focuser_port = 0;
    m_alpaca_focuser_port_isSet = false;
    alpaca_focuser_device_number = 0;
    m_alpaca_focuser_device_number_isSet = false;
    alpaca_focus_position = 0;
    m_alpaca_focus_position_isSet = false;
    alpaca_focus_step_size = 0;
    m_alpaca_focus_step_size_isSet = false;
    alpaca_filter_wheel_enabled = 0;
    m_alpaca_filter_wheel_enabled_isSet = false;
    alpaca_filter_wheel_host = new QString("");
    m_alpaca_filter_wheel_host_isSet = false;
    alpaca_filter_wheel_port = 0;
    m_alpaca_filter_wheel_port_isSet = false;
    alpaca_filter_wheel_device_number = 0;
    m_alpaca_filter_wheel_device_number_isSet = false;
    alpaca_filter_wheel_position = 0;
    m_alpaca_filter_wheel_position_isSet = false;
    alpaca_bin_x = 0;
    m_alpaca_bin_x_isSet = false;
    alpaca_bin_y = 0;
    m_alpaca_bin_y_isSet = false;
    alpaca_num_x = 0;
    m_alpaca_num_x_isSet = false;
    alpaca_num_y = 0;
    m_alpaca_num_y_isSet = false;
    alpaca_start_x = 0;
    m_alpaca_start_x_isSet = false;
    alpaca_start_y = 0;
    m_alpaca_start_y_isSet = false;
    alpaca_gain = 0;
    m_alpaca_gain_isSet = false;
    alpaca_offset = 0;
    m_alpaca_offset_isSet = false;
    alpaca_readout_mode = 0;
    m_alpaca_readout_mode_isSet = false;
    save_image = 0;
    m_save_image_isSet = false;
    image_file_name = new QString("");
    m_image_file_name_isSet = false;
    save_video = 0;
    m_save_video_isSet = false;
    video_file_camera_path = new QString("");
    m_video_file_camera_path_isSet = false;
    video_file_name = new QString("");
    m_video_file_name_isSet = false;
    video_hw_acceleration = 0;
    m_video_hw_acceleration_isSet = false;
    post_process_white_balance_mode = 0;
    m_post_process_white_balance_mode_isSet = false;
    post_process_white_balance_red_gain = 0.0;
    m_post_process_white_balance_red_gain_isSet = false;
    post_process_white_balance_green_gain = 0.0;
    m_post_process_white_balance_green_gain_isSet = false;
    post_process_white_balance_blue_gain = 0.0;
    m_post_process_white_balance_blue_gain_isSet = false;
    saturation = 0.0;
    m_saturation_isSet = false;
    gamma = 0.0;
    m_gamma_isSet = false;
    brightness = 0.0;
    m_brightness_isSet = false;
    contrast = 0.0;
    m_contrast_isSet = false;
    gaussian_blur = 0;
    m_gaussian_blur_isSet = false;
    median_blur = 0;
    m_median_blur_isSet = false;
    sharpen = 0.0;
    m_sharpen_isSet = false;
    sobel_edge = 0.0;
    m_sobel_edge_isSet = false;
    flip_x = 0;
    m_flip_x_isSet = false;
    flip_y = 0;
    m_flip_y_isSet = false;
    invert_colors = 0;
    m_invert_colors_isSet = false;
    overlay_date_time = 0;
    m_overlay_date_time_isSet = false;
    date_time_color = 0;
    m_date_time_color_isSet = false;
    date_time_format = new QString("");
    m_date_time_format_isSet = false;
    date_time_pos_x = 0;
    m_date_time_pos_x_isSet = false;
    date_time_pos_y = 0;
    m_date_time_pos_y_isSet = false;
    overlay_text = 0;
    m_overlay_text_isSet = false;
    overlay_text_string = new QString("");
    m_overlay_text_string_isSet = false;
    overlay_text_color = 0;
    m_overlay_text_color_isSet = false;
    overlay_text_font_family = new QString("");
    m_overlay_text_font_family_isSet = false;
    overlay_text_font_scale = 0.0;
    m_overlay_text_font_scale_isSet = false;
    overlay_text_pos_x = 0;
    m_overlay_text_pos_x_isSet = false;
    overlay_text_pos_y = 0;
    m_overlay_text_pos_y_isSet = false;
    diff_mask = 0;
    m_diff_mask_isSet = false;
    diff_threshold = 0;
    m_diff_threshold_isSet = false;
    dilation_size = 0;
    m_dilation_size_isSet = false;
    diff_mask_history_frames = 0;
    m_diff_mask_history_frames_isSet = false;
    diff_mask_close_size = 0;
    m_diff_mask_close_size_isSet = false;
    detection_roi_x = 0;
    m_detection_roi_x_isSet = false;
    detection_roi_y = 0;
    m_detection_roi_y_isSet = false;
    detection_roi_width = 0;
    m_detection_roi_width_isSet = false;
    detection_roi_height = 0;
    m_detection_roi_height_isSet = false;
    motion_detect = 0;
    m_motion_detect_isSet = false;
    motion_history = 0;
    m_motion_history_isSet = false;
    motion_var_threshold = 0.0;
    m_motion_var_threshold_isSet = false;
    motion_detect_shadows = 0;
    m_motion_detect_shadows_isSet = false;
    motion_open_size = 0;
    m_motion_open_size_isSet = false;
    motion_close_size = 0;
    m_motion_close_size_isSet = false;
    motion_persistence_frames = 0;
    m_motion_persistence_frames_isSet = false;
    motion_box_color = 0;
    m_motion_box_color_isSet = false;
    min_contour_area = 0;
    m_min_contour_area_isSet = false;
    video_post_process = 0;
    m_video_post_process_isSet = false;
    overlay_spectrum = 0;
    m_overlay_spectrum_isSet = false;
    spectrum_device = new QString("");
    m_spectrum_device_isSet = false;
    spectrum_offset_x = 0;
    m_spectrum_offset_x_isSet = false;
    spectrum_offset_y = 0;
    m_spectrum_offset_y_isSet = false;
    spectrum_scale = 0.0;
    m_spectrum_scale_isSet = false;
    yolo_enabled = 0;
    m_yolo_enabled_isSet = false;
    yolo_model_path = new QString("");
    m_yolo_model_path_isSet = false;
    yolo_labels_path = new QString("");
    m_yolo_labels_path_isSet = false;
    yolo_conf_threshold = 0.0;
    m_yolo_conf_threshold_isSet = false;
    yolo_nms_threshold = 0.0;
    m_yolo_nms_threshold_isSet = false;
    yolo_box_color = 0;
    m_yolo_box_color_isSet = false;
    yolo_disappear_debounce = 0.0;
    m_yolo_disappear_debounce_isSet = false;
    yolo_dnn_target = 0;
    m_yolo_dnn_target_isSet = false;
    object_device_settings = new QList<SWGCameraObjectClassSettings*>();
    m_object_device_settings_isSet = false;
    audio_mute = 0;
    m_audio_mute_isSet = false;
    audio_device_name = new QString("");
    m_audio_device_name_isSet = false;
    white_balance_mode = 0;
    m_white_balance_mode_isSet = false;
    exposure_compensation = 0.0;
    m_exposure_compensation_isSet = false;
    focus_mode = 0;
    m_focus_mode_isSet = false;
    focus_distance = 0.0;
    m_focus_distance_isSet = false;
    zoom_factor = 0.0;
    m_zoom_factor_isSet = false;
    use_reverse_api = 0;
    m_use_reverse_api_isSet = false;
    reverse_api_address = new QString("");
    m_reverse_api_address_isSet = false;
    reverse_api_port = 0;
    m_reverse_api_port_isSet = false;
    reverse_api_feature_set_index = 0;
    m_reverse_api_feature_set_index_isSet = false;
    reverse_api_feature_index = 0;
    m_reverse_api_feature_index_isSet = false;
    rollup_state = new SWGRollupState();
    m_rollup_state_isSet = false;
    workspace_index = 0;
    m_workspace_index_isSet = false;
}

void
SWGCameraSettings::cleanup() {
    if(title != nullptr) { 
        delete title;
    }

    if(camera_protocol != nullptr) { 
        delete camera_protocol;
    }
    if(camera_id != nullptr) { 
        delete camera_id;
    }
    if(camera_description != nullptr) { 
        delete camera_description;
    }










    if(alpaca_host != nullptr) { 
        delete alpaca_host;
    }


    if(alpaca_focuser_host != nullptr) { 
        delete alpaca_focuser_host;
    }





    if(alpaca_filter_wheel_host != nullptr) { 
        delete alpaca_filter_wheel_host;
    }













    if(image_file_name != nullptr) { 
        delete image_file_name;
    }

    if(video_file_camera_path != nullptr) { 
        delete video_file_camera_path;
    }
    if(video_file_name != nullptr) { 
        delete video_file_name;
    }


















    if(date_time_format != nullptr) { 
        delete date_time_format;
    }



    if(overlay_text_string != nullptr) { 
        delete overlay_text_string;
    }

    if(overlay_text_font_family != nullptr) { 
        delete overlay_text_font_family;
    }























    if(spectrum_device != nullptr) { 
        delete spectrum_device;
    }




    if(yolo_model_path != nullptr) { 
        delete yolo_model_path;
    }
    if(yolo_labels_path != nullptr) { 
        delete yolo_labels_path;
    }





    if(object_device_settings != nullptr) { 
        auto arr = object_device_settings;
        for(auto o: *arr) { 
            delete o;
        }
        delete object_device_settings;
    }

    if(audio_device_name != nullptr) { 
        delete audio_device_name;
    }






    if(reverse_api_address != nullptr) { 
        delete reverse_api_address;
    }



    if(rollup_state != nullptr) { 
        delete rollup_state;
    }

}

SWGCameraSettings*
SWGCameraSettings::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGCameraSettings::fromJsonObject(QJsonObject &pJson) {
    ::SWGSDRangel::setValue(&title, pJson["title"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&rgb_color, pJson["rgbColor"], "qint32", "");
    
    ::SWGSDRangel::setValue(&camera_protocol, pJson["cameraProtocol"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&camera_id, pJson["cameraId"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&camera_description, pJson["cameraDescription"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&resolution_width, pJson["resolutionWidth"], "qint32", "");
    
    ::SWGSDRangel::setValue(&resolution_height, pJson["resolutionHeight"], "qint32", "");
    
    ::SWGSDRangel::setValue(&frames_per_second, pJson["framesPerSecond"], "qint32", "");
    
    ::SWGSDRangel::setValue(&capture_mode, pJson["captureMode"], "qint32", "");
    
    ::SWGSDRangel::setValue(&capture_interval, pJson["captureInterval"], "double", "");
    
    ::SWGSDRangel::setValue(&capture_interval_units, pJson["captureIntervalUnits"], "qint32", "");
    
    ::SWGSDRangel::setValue(&exposure_time_ms, pJson["exposureTimeMs"], "double", "");
    
    ::SWGSDRangel::setValue(&iso_sensitivity, pJson["isoSensitivity"], "qint32", "");
    
    ::SWGSDRangel::setValue(&alpaca_discovery_enabled, pJson["alpacaDiscoveryEnabled"], "qint32", "");
    
    ::SWGSDRangel::setValue(&alpaca_api_log_enabled, pJson["alpacaApiLogEnabled"], "qint32", "");
    
    ::SWGSDRangel::setValue(&alpaca_host, pJson["alpacaHost"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&alpaca_port, pJson["alpacaPort"], "qint32", "");
    
    ::SWGSDRangel::setValue(&alpaca_focuser_enabled, pJson["alpacaFocuserEnabled"], "qint32", "");
    
    ::SWGSDRangel::setValue(&alpaca_focuser_host, pJson["alpacaFocuserHost"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&alpaca_focuser_port, pJson["alpacaFocuserPort"], "qint32", "");
    
    ::SWGSDRangel::setValue(&alpaca_focuser_device_number, pJson["alpacaFocuserDeviceNumber"], "qint32", "");
    
    ::SWGSDRangel::setValue(&alpaca_focus_position, pJson["alpacaFocusPosition"], "qint32", "");
    
    ::SWGSDRangel::setValue(&alpaca_focus_step_size, pJson["alpacaFocusStepSize"], "qint32", "");
    
    ::SWGSDRangel::setValue(&alpaca_filter_wheel_enabled, pJson["alpacaFilterWheelEnabled"], "qint32", "");
    
    ::SWGSDRangel::setValue(&alpaca_filter_wheel_host, pJson["alpacaFilterWheelHost"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&alpaca_filter_wheel_port, pJson["alpacaFilterWheelPort"], "qint32", "");
    
    ::SWGSDRangel::setValue(&alpaca_filter_wheel_device_number, pJson["alpacaFilterWheelDeviceNumber"], "qint32", "");
    
    ::SWGSDRangel::setValue(&alpaca_filter_wheel_position, pJson["alpacaFilterWheelPosition"], "qint32", "");
    
    ::SWGSDRangel::setValue(&alpaca_bin_x, pJson["alpacaBinX"], "qint32", "");
    
    ::SWGSDRangel::setValue(&alpaca_bin_y, pJson["alpacaBinY"], "qint32", "");
    
    ::SWGSDRangel::setValue(&alpaca_num_x, pJson["alpacaNumX"], "qint32", "");
    
    ::SWGSDRangel::setValue(&alpaca_num_y, pJson["alpacaNumY"], "qint32", "");
    
    ::SWGSDRangel::setValue(&alpaca_start_x, pJson["alpacaStartX"], "qint32", "");
    
    ::SWGSDRangel::setValue(&alpaca_start_y, pJson["alpacaStartY"], "qint32", "");
    
    ::SWGSDRangel::setValue(&alpaca_gain, pJson["alpacaGain"], "qint32", "");
    
    ::SWGSDRangel::setValue(&alpaca_offset, pJson["alpacaOffset"], "qint32", "");
    
    ::SWGSDRangel::setValue(&alpaca_readout_mode, pJson["alpacaReadoutMode"], "qint32", "");
    
    ::SWGSDRangel::setValue(&save_image, pJson["saveImage"], "qint32", "");
    
    ::SWGSDRangel::setValue(&image_file_name, pJson["imageFileName"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&save_video, pJson["saveVideo"], "qint32", "");
    
    ::SWGSDRangel::setValue(&video_file_camera_path, pJson["videoFileCameraPath"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&video_file_name, pJson["videoFileName"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&video_hw_acceleration, pJson["videoHwAcceleration"], "qint32", "");
    
    ::SWGSDRangel::setValue(&post_process_white_balance_mode, pJson["postProcessWhiteBalanceMode"], "qint32", "");
    
    ::SWGSDRangel::setValue(&post_process_white_balance_red_gain, pJson["postProcessWhiteBalanceRedGain"], "double", "");
    
    ::SWGSDRangel::setValue(&post_process_white_balance_green_gain, pJson["postProcessWhiteBalanceGreenGain"], "double", "");
    
    ::SWGSDRangel::setValue(&post_process_white_balance_blue_gain, pJson["postProcessWhiteBalanceBlueGain"], "double", "");
    
    ::SWGSDRangel::setValue(&saturation, pJson["saturation"], "double", "");
    
    ::SWGSDRangel::setValue(&gamma, pJson["gamma"], "double", "");
    
    ::SWGSDRangel::setValue(&brightness, pJson["brightness"], "double", "");
    
    ::SWGSDRangel::setValue(&contrast, pJson["contrast"], "double", "");
    
    ::SWGSDRangel::setValue(&gaussian_blur, pJson["gaussianBlur"], "qint32", "");
    
    ::SWGSDRangel::setValue(&median_blur, pJson["medianBlur"], "qint32", "");
    
    ::SWGSDRangel::setValue(&sharpen, pJson["sharpen"], "double", "");
    
    ::SWGSDRangel::setValue(&sobel_edge, pJson["sobelEdge"], "double", "");
    
    ::SWGSDRangel::setValue(&flip_x, pJson["flipX"], "qint32", "");
    
    ::SWGSDRangel::setValue(&flip_y, pJson["flipY"], "qint32", "");
    
    ::SWGSDRangel::setValue(&invert_colors, pJson["invertColors"], "qint32", "");
    
    ::SWGSDRangel::setValue(&overlay_date_time, pJson["overlayDateTime"], "qint32", "");
    
    ::SWGSDRangel::setValue(&date_time_color, pJson["dateTimeColor"], "qint32", "");
    
    ::SWGSDRangel::setValue(&date_time_format, pJson["dateTimeFormat"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&date_time_pos_x, pJson["dateTimePosX"], "qint32", "");
    
    ::SWGSDRangel::setValue(&date_time_pos_y, pJson["dateTimePosY"], "qint32", "");
    
    ::SWGSDRangel::setValue(&overlay_text, pJson["overlayText"], "qint32", "");
    
    ::SWGSDRangel::setValue(&overlay_text_string, pJson["overlayTextString"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&overlay_text_color, pJson["overlayTextColor"], "qint32", "");
    
    ::SWGSDRangel::setValue(&overlay_text_font_family, pJson["overlayTextFontFamily"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&overlay_text_font_scale, pJson["overlayTextFontScale"], "double", "");
    
    ::SWGSDRangel::setValue(&overlay_text_pos_x, pJson["overlayTextPosX"], "qint32", "");
    
    ::SWGSDRangel::setValue(&overlay_text_pos_y, pJson["overlayTextPosY"], "qint32", "");
    
    ::SWGSDRangel::setValue(&diff_mask, pJson["diffMask"], "qint32", "");
    
    ::SWGSDRangel::setValue(&diff_threshold, pJson["diffThreshold"], "qint32", "");
    
    ::SWGSDRangel::setValue(&dilation_size, pJson["dilationSize"], "qint32", "");
    
    ::SWGSDRangel::setValue(&diff_mask_history_frames, pJson["diffMaskHistoryFrames"], "qint32", "");
    
    ::SWGSDRangel::setValue(&diff_mask_close_size, pJson["diffMaskCloseSize"], "qint32", "");
    
    ::SWGSDRangel::setValue(&detection_roi_x, pJson["detectionRoiX"], "qint32", "");
    
    ::SWGSDRangel::setValue(&detection_roi_y, pJson["detectionRoiY"], "qint32", "");
    
    ::SWGSDRangel::setValue(&detection_roi_width, pJson["detectionRoiWidth"], "qint32", "");
    
    ::SWGSDRangel::setValue(&detection_roi_height, pJson["detectionRoiHeight"], "qint32", "");
    
    ::SWGSDRangel::setValue(&motion_detect, pJson["motionDetect"], "qint32", "");
    
    ::SWGSDRangel::setValue(&motion_history, pJson["motionHistory"], "qint32", "");
    
    ::SWGSDRangel::setValue(&motion_var_threshold, pJson["motionVarThreshold"], "double", "");
    
    ::SWGSDRangel::setValue(&motion_detect_shadows, pJson["motionDetectShadows"], "qint32", "");
    
    ::SWGSDRangel::setValue(&motion_open_size, pJson["motionOpenSize"], "qint32", "");
    
    ::SWGSDRangel::setValue(&motion_close_size, pJson["motionCloseSize"], "qint32", "");
    
    ::SWGSDRangel::setValue(&motion_persistence_frames, pJson["motionPersistenceFrames"], "qint32", "");
    
    ::SWGSDRangel::setValue(&motion_box_color, pJson["motionBoxColor"], "qint32", "");
    
    ::SWGSDRangel::setValue(&min_contour_area, pJson["minContourArea"], "qint32", "");
    
    ::SWGSDRangel::setValue(&video_post_process, pJson["videoPostProcess"], "qint32", "");
    
    ::SWGSDRangel::setValue(&overlay_spectrum, pJson["overlaySpectrum"], "qint32", "");
    
    ::SWGSDRangel::setValue(&spectrum_device, pJson["spectrumDevice"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&spectrum_offset_x, pJson["spectrumOffsetX"], "qint32", "");
    
    ::SWGSDRangel::setValue(&spectrum_offset_y, pJson["spectrumOffsetY"], "qint32", "");
    
    ::SWGSDRangel::setValue(&spectrum_scale, pJson["spectrumScale"], "double", "");
    
    ::SWGSDRangel::setValue(&yolo_enabled, pJson["yoloEnabled"], "qint32", "");
    
    ::SWGSDRangel::setValue(&yolo_model_path, pJson["yoloModelPath"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&yolo_labels_path, pJson["yoloLabelsPath"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&yolo_conf_threshold, pJson["yoloConfThreshold"], "double", "");
    
    ::SWGSDRangel::setValue(&yolo_nms_threshold, pJson["yoloNmsThreshold"], "double", "");
    
    ::SWGSDRangel::setValue(&yolo_box_color, pJson["yoloBoxColor"], "qint32", "");
    
    ::SWGSDRangel::setValue(&yolo_disappear_debounce, pJson["yoloDisappearDebounce"], "double", "");
    
    ::SWGSDRangel::setValue(&yolo_dnn_target, pJson["yoloDnnTarget"], "qint32", "");
    
    
    ::SWGSDRangel::setValue(&object_device_settings, pJson["objectDeviceSettings"], "QList", "SWGCameraObjectClassSettings");
    ::SWGSDRangel::setValue(&audio_mute, pJson["audioMute"], "qint32", "");
    
    ::SWGSDRangel::setValue(&audio_device_name, pJson["audioDeviceName"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&white_balance_mode, pJson["whiteBalanceMode"], "qint32", "");
    
    ::SWGSDRangel::setValue(&exposure_compensation, pJson["exposureCompensation"], "double", "");
    
    ::SWGSDRangel::setValue(&focus_mode, pJson["focusMode"], "qint32", "");
    
    ::SWGSDRangel::setValue(&focus_distance, pJson["focusDistance"], "double", "");
    
    ::SWGSDRangel::setValue(&zoom_factor, pJson["zoomFactor"], "double", "");
    
    ::SWGSDRangel::setValue(&use_reverse_api, pJson["useReverseAPI"], "qint32", "");
    
    ::SWGSDRangel::setValue(&reverse_api_address, pJson["reverseAPIAddress"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&reverse_api_port, pJson["reverseAPIPort"], "qint32", "");
    
    ::SWGSDRangel::setValue(&reverse_api_feature_set_index, pJson["reverseAPIFeatureSetIndex"], "qint32", "");
    
    ::SWGSDRangel::setValue(&reverse_api_feature_index, pJson["reverseAPIFeatureIndex"], "qint32", "");
    
    ::SWGSDRangel::setValue(&rollup_state, pJson["rollupState"], "SWGRollupState", "SWGRollupState");
    
    ::SWGSDRangel::setValue(&workspace_index, pJson["workspaceIndex"], "qint32", "");
    
}

QString
SWGCameraSettings::asJson ()
{
    QJsonObject* obj = this->asJsonObject();

    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    delete obj;
    return QString(bytes);
}

QJsonObject*
SWGCameraSettings::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    if(title != nullptr && *title != QString("")){
        toJsonValue(QString("title"), title, obj, QString("QString"));
    }
    if(m_rgb_color_isSet){
        obj->insert("rgbColor", QJsonValue(rgb_color));
    }
    if(camera_protocol != nullptr && *camera_protocol != QString("")){
        toJsonValue(QString("cameraProtocol"), camera_protocol, obj, QString("QString"));
    }
    if(camera_id != nullptr && *camera_id != QString("")){
        toJsonValue(QString("cameraId"), camera_id, obj, QString("QString"));
    }
    if(camera_description != nullptr && *camera_description != QString("")){
        toJsonValue(QString("cameraDescription"), camera_description, obj, QString("QString"));
    }
    if(m_resolution_width_isSet){
        obj->insert("resolutionWidth", QJsonValue(resolution_width));
    }
    if(m_resolution_height_isSet){
        obj->insert("resolutionHeight", QJsonValue(resolution_height));
    }
    if(m_frames_per_second_isSet){
        obj->insert("framesPerSecond", QJsonValue(frames_per_second));
    }
    if(m_capture_mode_isSet){
        obj->insert("captureMode", QJsonValue(capture_mode));
    }
    if(m_capture_interval_isSet){
        obj->insert("captureInterval", QJsonValue(capture_interval));
    }
    if(m_capture_interval_units_isSet){
        obj->insert("captureIntervalUnits", QJsonValue(capture_interval_units));
    }
    if(m_exposure_time_ms_isSet){
        obj->insert("exposureTimeMs", QJsonValue(exposure_time_ms));
    }
    if(m_iso_sensitivity_isSet){
        obj->insert("isoSensitivity", QJsonValue(iso_sensitivity));
    }
    if(m_alpaca_discovery_enabled_isSet){
        obj->insert("alpacaDiscoveryEnabled", QJsonValue(alpaca_discovery_enabled));
    }
    if(m_alpaca_api_log_enabled_isSet){
        obj->insert("alpacaApiLogEnabled", QJsonValue(alpaca_api_log_enabled));
    }
    if(alpaca_host != nullptr && *alpaca_host != QString("")){
        toJsonValue(QString("alpacaHost"), alpaca_host, obj, QString("QString"));
    }
    if(m_alpaca_port_isSet){
        obj->insert("alpacaPort", QJsonValue(alpaca_port));
    }
    if(m_alpaca_focuser_enabled_isSet){
        obj->insert("alpacaFocuserEnabled", QJsonValue(alpaca_focuser_enabled));
    }
    if(alpaca_focuser_host != nullptr && *alpaca_focuser_host != QString("")){
        toJsonValue(QString("alpacaFocuserHost"), alpaca_focuser_host, obj, QString("QString"));
    }
    if(m_alpaca_focuser_port_isSet){
        obj->insert("alpacaFocuserPort", QJsonValue(alpaca_focuser_port));
    }
    if(m_alpaca_focuser_device_number_isSet){
        obj->insert("alpacaFocuserDeviceNumber", QJsonValue(alpaca_focuser_device_number));
    }
    if(m_alpaca_focus_position_isSet){
        obj->insert("alpacaFocusPosition", QJsonValue(alpaca_focus_position));
    }
    if(m_alpaca_focus_step_size_isSet){
        obj->insert("alpacaFocusStepSize", QJsonValue(alpaca_focus_step_size));
    }
    if(m_alpaca_filter_wheel_enabled_isSet){
        obj->insert("alpacaFilterWheelEnabled", QJsonValue(alpaca_filter_wheel_enabled));
    }
    if(alpaca_filter_wheel_host != nullptr && *alpaca_filter_wheel_host != QString("")){
        toJsonValue(QString("alpacaFilterWheelHost"), alpaca_filter_wheel_host, obj, QString("QString"));
    }
    if(m_alpaca_filter_wheel_port_isSet){
        obj->insert("alpacaFilterWheelPort", QJsonValue(alpaca_filter_wheel_port));
    }
    if(m_alpaca_filter_wheel_device_number_isSet){
        obj->insert("alpacaFilterWheelDeviceNumber", QJsonValue(alpaca_filter_wheel_device_number));
    }
    if(m_alpaca_filter_wheel_position_isSet){
        obj->insert("alpacaFilterWheelPosition", QJsonValue(alpaca_filter_wheel_position));
    }
    if(m_alpaca_bin_x_isSet){
        obj->insert("alpacaBinX", QJsonValue(alpaca_bin_x));
    }
    if(m_alpaca_bin_y_isSet){
        obj->insert("alpacaBinY", QJsonValue(alpaca_bin_y));
    }
    if(m_alpaca_num_x_isSet){
        obj->insert("alpacaNumX", QJsonValue(alpaca_num_x));
    }
    if(m_alpaca_num_y_isSet){
        obj->insert("alpacaNumY", QJsonValue(alpaca_num_y));
    }
    if(m_alpaca_start_x_isSet){
        obj->insert("alpacaStartX", QJsonValue(alpaca_start_x));
    }
    if(m_alpaca_start_y_isSet){
        obj->insert("alpacaStartY", QJsonValue(alpaca_start_y));
    }
    if(m_alpaca_gain_isSet){
        obj->insert("alpacaGain", QJsonValue(alpaca_gain));
    }
    if(m_alpaca_offset_isSet){
        obj->insert("alpacaOffset", QJsonValue(alpaca_offset));
    }
    if(m_alpaca_readout_mode_isSet){
        obj->insert("alpacaReadoutMode", QJsonValue(alpaca_readout_mode));
    }
    if(m_save_image_isSet){
        obj->insert("saveImage", QJsonValue(save_image));
    }
    if(image_file_name != nullptr && *image_file_name != QString("")){
        toJsonValue(QString("imageFileName"), image_file_name, obj, QString("QString"));
    }
    if(m_save_video_isSet){
        obj->insert("saveVideo", QJsonValue(save_video));
    }
    if(video_file_camera_path != nullptr && *video_file_camera_path != QString("")){
        toJsonValue(QString("videoFileCameraPath"), video_file_camera_path, obj, QString("QString"));
    }
    if(video_file_name != nullptr && *video_file_name != QString("")){
        toJsonValue(QString("videoFileName"), video_file_name, obj, QString("QString"));
    }
    if(m_video_hw_acceleration_isSet){
        obj->insert("videoHwAcceleration", QJsonValue(video_hw_acceleration));
    }
    if(m_post_process_white_balance_mode_isSet){
        obj->insert("postProcessWhiteBalanceMode", QJsonValue(post_process_white_balance_mode));
    }
    if(m_post_process_white_balance_red_gain_isSet){
        obj->insert("postProcessWhiteBalanceRedGain", QJsonValue(post_process_white_balance_red_gain));
    }
    if(m_post_process_white_balance_green_gain_isSet){
        obj->insert("postProcessWhiteBalanceGreenGain", QJsonValue(post_process_white_balance_green_gain));
    }
    if(m_post_process_white_balance_blue_gain_isSet){
        obj->insert("postProcessWhiteBalanceBlueGain", QJsonValue(post_process_white_balance_blue_gain));
    }
    if(m_saturation_isSet){
        obj->insert("saturation", QJsonValue(saturation));
    }
    if(m_gamma_isSet){
        obj->insert("gamma", QJsonValue(gamma));
    }
    if(m_brightness_isSet){
        obj->insert("brightness", QJsonValue(brightness));
    }
    if(m_contrast_isSet){
        obj->insert("contrast", QJsonValue(contrast));
    }
    if(m_gaussian_blur_isSet){
        obj->insert("gaussianBlur", QJsonValue(gaussian_blur));
    }
    if(m_median_blur_isSet){
        obj->insert("medianBlur", QJsonValue(median_blur));
    }
    if(m_sharpen_isSet){
        obj->insert("sharpen", QJsonValue(sharpen));
    }
    if(m_sobel_edge_isSet){
        obj->insert("sobelEdge", QJsonValue(sobel_edge));
    }
    if(m_flip_x_isSet){
        obj->insert("flipX", QJsonValue(flip_x));
    }
    if(m_flip_y_isSet){
        obj->insert("flipY", QJsonValue(flip_y));
    }
    if(m_invert_colors_isSet){
        obj->insert("invertColors", QJsonValue(invert_colors));
    }
    if(m_overlay_date_time_isSet){
        obj->insert("overlayDateTime", QJsonValue(overlay_date_time));
    }
    if(m_date_time_color_isSet){
        obj->insert("dateTimeColor", QJsonValue(date_time_color));
    }
    if(date_time_format != nullptr && *date_time_format != QString("")){
        toJsonValue(QString("dateTimeFormat"), date_time_format, obj, QString("QString"));
    }
    if(m_date_time_pos_x_isSet){
        obj->insert("dateTimePosX", QJsonValue(date_time_pos_x));
    }
    if(m_date_time_pos_y_isSet){
        obj->insert("dateTimePosY", QJsonValue(date_time_pos_y));
    }
    if(m_overlay_text_isSet){
        obj->insert("overlayText", QJsonValue(overlay_text));
    }
    if(overlay_text_string != nullptr && *overlay_text_string != QString("")){
        toJsonValue(QString("overlayTextString"), overlay_text_string, obj, QString("QString"));
    }
    if(m_overlay_text_color_isSet){
        obj->insert("overlayTextColor", QJsonValue(overlay_text_color));
    }
    if(overlay_text_font_family != nullptr && *overlay_text_font_family != QString("")){
        toJsonValue(QString("overlayTextFontFamily"), overlay_text_font_family, obj, QString("QString"));
    }
    if(m_overlay_text_font_scale_isSet){
        obj->insert("overlayTextFontScale", QJsonValue(overlay_text_font_scale));
    }
    if(m_overlay_text_pos_x_isSet){
        obj->insert("overlayTextPosX", QJsonValue(overlay_text_pos_x));
    }
    if(m_overlay_text_pos_y_isSet){
        obj->insert("overlayTextPosY", QJsonValue(overlay_text_pos_y));
    }
    if(m_diff_mask_isSet){
        obj->insert("diffMask", QJsonValue(diff_mask));
    }
    if(m_diff_threshold_isSet){
        obj->insert("diffThreshold", QJsonValue(diff_threshold));
    }
    if(m_dilation_size_isSet){
        obj->insert("dilationSize", QJsonValue(dilation_size));
    }
    if(m_diff_mask_history_frames_isSet){
        obj->insert("diffMaskHistoryFrames", QJsonValue(diff_mask_history_frames));
    }
    if(m_diff_mask_close_size_isSet){
        obj->insert("diffMaskCloseSize", QJsonValue(diff_mask_close_size));
    }
    if(m_detection_roi_x_isSet){
        obj->insert("detectionRoiX", QJsonValue(detection_roi_x));
    }
    if(m_detection_roi_y_isSet){
        obj->insert("detectionRoiY", QJsonValue(detection_roi_y));
    }
    if(m_detection_roi_width_isSet){
        obj->insert("detectionRoiWidth", QJsonValue(detection_roi_width));
    }
    if(m_detection_roi_height_isSet){
        obj->insert("detectionRoiHeight", QJsonValue(detection_roi_height));
    }
    if(m_motion_detect_isSet){
        obj->insert("motionDetect", QJsonValue(motion_detect));
    }
    if(m_motion_history_isSet){
        obj->insert("motionHistory", QJsonValue(motion_history));
    }
    if(m_motion_var_threshold_isSet){
        obj->insert("motionVarThreshold", QJsonValue(motion_var_threshold));
    }
    if(m_motion_detect_shadows_isSet){
        obj->insert("motionDetectShadows", QJsonValue(motion_detect_shadows));
    }
    if(m_motion_open_size_isSet){
        obj->insert("motionOpenSize", QJsonValue(motion_open_size));
    }
    if(m_motion_close_size_isSet){
        obj->insert("motionCloseSize", QJsonValue(motion_close_size));
    }
    if(m_motion_persistence_frames_isSet){
        obj->insert("motionPersistenceFrames", QJsonValue(motion_persistence_frames));
    }
    if(m_motion_box_color_isSet){
        obj->insert("motionBoxColor", QJsonValue(motion_box_color));
    }
    if(m_min_contour_area_isSet){
        obj->insert("minContourArea", QJsonValue(min_contour_area));
    }
    if(m_video_post_process_isSet){
        obj->insert("videoPostProcess", QJsonValue(video_post_process));
    }
    if(m_overlay_spectrum_isSet){
        obj->insert("overlaySpectrum", QJsonValue(overlay_spectrum));
    }
    if(spectrum_device != nullptr && *spectrum_device != QString("")){
        toJsonValue(QString("spectrumDevice"), spectrum_device, obj, QString("QString"));
    }
    if(m_spectrum_offset_x_isSet){
        obj->insert("spectrumOffsetX", QJsonValue(spectrum_offset_x));
    }
    if(m_spectrum_offset_y_isSet){
        obj->insert("spectrumOffsetY", QJsonValue(spectrum_offset_y));
    }
    if(m_spectrum_scale_isSet){
        obj->insert("spectrumScale", QJsonValue(spectrum_scale));
    }
    if(m_yolo_enabled_isSet){
        obj->insert("yoloEnabled", QJsonValue(yolo_enabled));
    }
    if(yolo_model_path != nullptr && *yolo_model_path != QString("")){
        toJsonValue(QString("yoloModelPath"), yolo_model_path, obj, QString("QString"));
    }
    if(yolo_labels_path != nullptr && *yolo_labels_path != QString("")){
        toJsonValue(QString("yoloLabelsPath"), yolo_labels_path, obj, QString("QString"));
    }
    if(m_yolo_conf_threshold_isSet){
        obj->insert("yoloConfThreshold", QJsonValue(yolo_conf_threshold));
    }
    if(m_yolo_nms_threshold_isSet){
        obj->insert("yoloNmsThreshold", QJsonValue(yolo_nms_threshold));
    }
    if(m_yolo_box_color_isSet){
        obj->insert("yoloBoxColor", QJsonValue(yolo_box_color));
    }
    if(m_yolo_disappear_debounce_isSet){
        obj->insert("yoloDisappearDebounce", QJsonValue(yolo_disappear_debounce));
    }
    if(m_yolo_dnn_target_isSet){
        obj->insert("yoloDnnTarget", QJsonValue(yolo_dnn_target));
    }
    if(object_device_settings && object_device_settings->size() > 0){
        toJsonArray((QList<void*>*)object_device_settings, obj, "objectDeviceSettings", "SWGCameraObjectClassSettings");
    }
    if(m_audio_mute_isSet){
        obj->insert("audioMute", QJsonValue(audio_mute));
    }
    if(audio_device_name != nullptr && *audio_device_name != QString("")){
        toJsonValue(QString("audioDeviceName"), audio_device_name, obj, QString("QString"));
    }
    if(m_white_balance_mode_isSet){
        obj->insert("whiteBalanceMode", QJsonValue(white_balance_mode));
    }
    if(m_exposure_compensation_isSet){
        obj->insert("exposureCompensation", QJsonValue(exposure_compensation));
    }
    if(m_focus_mode_isSet){
        obj->insert("focusMode", QJsonValue(focus_mode));
    }
    if(m_focus_distance_isSet){
        obj->insert("focusDistance", QJsonValue(focus_distance));
    }
    if(m_zoom_factor_isSet){
        obj->insert("zoomFactor", QJsonValue(zoom_factor));
    }
    if(m_use_reverse_api_isSet){
        obj->insert("useReverseAPI", QJsonValue(use_reverse_api));
    }
    if(reverse_api_address != nullptr && *reverse_api_address != QString("")){
        toJsonValue(QString("reverseAPIAddress"), reverse_api_address, obj, QString("QString"));
    }
    if(m_reverse_api_port_isSet){
        obj->insert("reverseAPIPort", QJsonValue(reverse_api_port));
    }
    if(m_reverse_api_feature_set_index_isSet){
        obj->insert("reverseAPIFeatureSetIndex", QJsonValue(reverse_api_feature_set_index));
    }
    if(m_reverse_api_feature_index_isSet){
        obj->insert("reverseAPIFeatureIndex", QJsonValue(reverse_api_feature_index));
    }
    if((rollup_state != nullptr) && (rollup_state->isSet())){
        toJsonValue(QString("rollupState"), rollup_state, obj, QString("SWGRollupState"));
    }
    if(m_workspace_index_isSet){
        obj->insert("workspaceIndex", QJsonValue(workspace_index));
    }

    return obj;
}

QString*
SWGCameraSettings::getTitle() {
    return title;
}
void
SWGCameraSettings::setTitle(QString* title) {
    this->title = title;
    this->m_title_isSet = true;
}

qint32
SWGCameraSettings::getRgbColor() {
    return rgb_color;
}
void
SWGCameraSettings::setRgbColor(qint32 rgb_color) {
    this->rgb_color = rgb_color;
    this->m_rgb_color_isSet = true;
}

QString*
SWGCameraSettings::getCameraProtocol() {
    return camera_protocol;
}
void
SWGCameraSettings::setCameraProtocol(QString* camera_protocol) {
    this->camera_protocol = camera_protocol;
    this->m_camera_protocol_isSet = true;
}

QString*
SWGCameraSettings::getCameraId() {
    return camera_id;
}
void
SWGCameraSettings::setCameraId(QString* camera_id) {
    this->camera_id = camera_id;
    this->m_camera_id_isSet = true;
}

QString*
SWGCameraSettings::getCameraDescription() {
    return camera_description;
}
void
SWGCameraSettings::setCameraDescription(QString* camera_description) {
    this->camera_description = camera_description;
    this->m_camera_description_isSet = true;
}

qint32
SWGCameraSettings::getResolutionWidth() {
    return resolution_width;
}
void
SWGCameraSettings::setResolutionWidth(qint32 resolution_width) {
    this->resolution_width = resolution_width;
    this->m_resolution_width_isSet = true;
}

qint32
SWGCameraSettings::getResolutionHeight() {
    return resolution_height;
}
void
SWGCameraSettings::setResolutionHeight(qint32 resolution_height) {
    this->resolution_height = resolution_height;
    this->m_resolution_height_isSet = true;
}

qint32
SWGCameraSettings::getFramesPerSecond() {
    return frames_per_second;
}
void
SWGCameraSettings::setFramesPerSecond(qint32 frames_per_second) {
    this->frames_per_second = frames_per_second;
    this->m_frames_per_second_isSet = true;
}

qint32
SWGCameraSettings::getCaptureMode() {
    return capture_mode;
}
void
SWGCameraSettings::setCaptureMode(qint32 capture_mode) {
    this->capture_mode = capture_mode;
    this->m_capture_mode_isSet = true;
}

double
SWGCameraSettings::getCaptureInterval() {
    return capture_interval;
}
void
SWGCameraSettings::setCaptureInterval(double capture_interval) {
    this->capture_interval = capture_interval;
    this->m_capture_interval_isSet = true;
}

qint32
SWGCameraSettings::getCaptureIntervalUnits() {
    return capture_interval_units;
}
void
SWGCameraSettings::setCaptureIntervalUnits(qint32 capture_interval_units) {
    this->capture_interval_units = capture_interval_units;
    this->m_capture_interval_units_isSet = true;
}

double
SWGCameraSettings::getExposureTimeMs() {
    return exposure_time_ms;
}
void
SWGCameraSettings::setExposureTimeMs(double exposure_time_ms) {
    this->exposure_time_ms = exposure_time_ms;
    this->m_exposure_time_ms_isSet = true;
}

qint32
SWGCameraSettings::getIsoSensitivity() {
    return iso_sensitivity;
}
void
SWGCameraSettings::setIsoSensitivity(qint32 iso_sensitivity) {
    this->iso_sensitivity = iso_sensitivity;
    this->m_iso_sensitivity_isSet = true;
}

qint32
SWGCameraSettings::getAlpacaDiscoveryEnabled() {
    return alpaca_discovery_enabled;
}
void
SWGCameraSettings::setAlpacaDiscoveryEnabled(qint32 alpaca_discovery_enabled) {
    this->alpaca_discovery_enabled = alpaca_discovery_enabled;
    this->m_alpaca_discovery_enabled_isSet = true;
}

qint32
SWGCameraSettings::getAlpacaApiLogEnabled() {
    return alpaca_api_log_enabled;
}
void
SWGCameraSettings::setAlpacaApiLogEnabled(qint32 alpaca_api_log_enabled) {
    this->alpaca_api_log_enabled = alpaca_api_log_enabled;
    this->m_alpaca_api_log_enabled_isSet = true;
}

QString*
SWGCameraSettings::getAlpacaHost() {
    return alpaca_host;
}
void
SWGCameraSettings::setAlpacaHost(QString* alpaca_host) {
    this->alpaca_host = alpaca_host;
    this->m_alpaca_host_isSet = true;
}

qint32
SWGCameraSettings::getAlpacaPort() {
    return alpaca_port;
}
void
SWGCameraSettings::setAlpacaPort(qint32 alpaca_port) {
    this->alpaca_port = alpaca_port;
    this->m_alpaca_port_isSet = true;
}

qint32
SWGCameraSettings::getAlpacaFocuserEnabled() {
    return alpaca_focuser_enabled;
}
void
SWGCameraSettings::setAlpacaFocuserEnabled(qint32 alpaca_focuser_enabled) {
    this->alpaca_focuser_enabled = alpaca_focuser_enabled;
    this->m_alpaca_focuser_enabled_isSet = true;
}

QString*
SWGCameraSettings::getAlpacaFocuserHost() {
    return alpaca_focuser_host;
}
void
SWGCameraSettings::setAlpacaFocuserHost(QString* alpaca_focuser_host) {
    this->alpaca_focuser_host = alpaca_focuser_host;
    this->m_alpaca_focuser_host_isSet = true;
}

qint32
SWGCameraSettings::getAlpacaFocuserPort() {
    return alpaca_focuser_port;
}
void
SWGCameraSettings::setAlpacaFocuserPort(qint32 alpaca_focuser_port) {
    this->alpaca_focuser_port = alpaca_focuser_port;
    this->m_alpaca_focuser_port_isSet = true;
}

qint32
SWGCameraSettings::getAlpacaFocuserDeviceNumber() {
    return alpaca_focuser_device_number;
}
void
SWGCameraSettings::setAlpacaFocuserDeviceNumber(qint32 alpaca_focuser_device_number) {
    this->alpaca_focuser_device_number = alpaca_focuser_device_number;
    this->m_alpaca_focuser_device_number_isSet = true;
}

qint32
SWGCameraSettings::getAlpacaFocusPosition() {
    return alpaca_focus_position;
}
void
SWGCameraSettings::setAlpacaFocusPosition(qint32 alpaca_focus_position) {
    this->alpaca_focus_position = alpaca_focus_position;
    this->m_alpaca_focus_position_isSet = true;
}

qint32
SWGCameraSettings::getAlpacaFocusStepSize() {
    return alpaca_focus_step_size;
}
void
SWGCameraSettings::setAlpacaFocusStepSize(qint32 alpaca_focus_step_size) {
    this->alpaca_focus_step_size = alpaca_focus_step_size;
    this->m_alpaca_focus_step_size_isSet = true;
}

qint32
SWGCameraSettings::getAlpacaFilterWheelEnabled() {
    return alpaca_filter_wheel_enabled;
}
void
SWGCameraSettings::setAlpacaFilterWheelEnabled(qint32 alpaca_filter_wheel_enabled) {
    this->alpaca_filter_wheel_enabled = alpaca_filter_wheel_enabled;
    this->m_alpaca_filter_wheel_enabled_isSet = true;
}

QString*
SWGCameraSettings::getAlpacaFilterWheelHost() {
    return alpaca_filter_wheel_host;
}
void
SWGCameraSettings::setAlpacaFilterWheelHost(QString* alpaca_filter_wheel_host) {
    this->alpaca_filter_wheel_host = alpaca_filter_wheel_host;
    this->m_alpaca_filter_wheel_host_isSet = true;
}

qint32
SWGCameraSettings::getAlpacaFilterWheelPort() {
    return alpaca_filter_wheel_port;
}
void
SWGCameraSettings::setAlpacaFilterWheelPort(qint32 alpaca_filter_wheel_port) {
    this->alpaca_filter_wheel_port = alpaca_filter_wheel_port;
    this->m_alpaca_filter_wheel_port_isSet = true;
}

qint32
SWGCameraSettings::getAlpacaFilterWheelDeviceNumber() {
    return alpaca_filter_wheel_device_number;
}
void
SWGCameraSettings::setAlpacaFilterWheelDeviceNumber(qint32 alpaca_filter_wheel_device_number) {
    this->alpaca_filter_wheel_device_number = alpaca_filter_wheel_device_number;
    this->m_alpaca_filter_wheel_device_number_isSet = true;
}

qint32
SWGCameraSettings::getAlpacaFilterWheelPosition() {
    return alpaca_filter_wheel_position;
}
void
SWGCameraSettings::setAlpacaFilterWheelPosition(qint32 alpaca_filter_wheel_position) {
    this->alpaca_filter_wheel_position = alpaca_filter_wheel_position;
    this->m_alpaca_filter_wheel_position_isSet = true;
}

qint32
SWGCameraSettings::getAlpacaBinX() {
    return alpaca_bin_x;
}
void
SWGCameraSettings::setAlpacaBinX(qint32 alpaca_bin_x) {
    this->alpaca_bin_x = alpaca_bin_x;
    this->m_alpaca_bin_x_isSet = true;
}

qint32
SWGCameraSettings::getAlpacaBinY() {
    return alpaca_bin_y;
}
void
SWGCameraSettings::setAlpacaBinY(qint32 alpaca_bin_y) {
    this->alpaca_bin_y = alpaca_bin_y;
    this->m_alpaca_bin_y_isSet = true;
}

qint32
SWGCameraSettings::getAlpacaNumX() {
    return alpaca_num_x;
}
void
SWGCameraSettings::setAlpacaNumX(qint32 alpaca_num_x) {
    this->alpaca_num_x = alpaca_num_x;
    this->m_alpaca_num_x_isSet = true;
}

qint32
SWGCameraSettings::getAlpacaNumY() {
    return alpaca_num_y;
}
void
SWGCameraSettings::setAlpacaNumY(qint32 alpaca_num_y) {
    this->alpaca_num_y = alpaca_num_y;
    this->m_alpaca_num_y_isSet = true;
}

qint32
SWGCameraSettings::getAlpacaStartX() {
    return alpaca_start_x;
}
void
SWGCameraSettings::setAlpacaStartX(qint32 alpaca_start_x) {
    this->alpaca_start_x = alpaca_start_x;
    this->m_alpaca_start_x_isSet = true;
}

qint32
SWGCameraSettings::getAlpacaStartY() {
    return alpaca_start_y;
}
void
SWGCameraSettings::setAlpacaStartY(qint32 alpaca_start_y) {
    this->alpaca_start_y = alpaca_start_y;
    this->m_alpaca_start_y_isSet = true;
}

qint32
SWGCameraSettings::getAlpacaGain() {
    return alpaca_gain;
}
void
SWGCameraSettings::setAlpacaGain(qint32 alpaca_gain) {
    this->alpaca_gain = alpaca_gain;
    this->m_alpaca_gain_isSet = true;
}

qint32
SWGCameraSettings::getAlpacaOffset() {
    return alpaca_offset;
}
void
SWGCameraSettings::setAlpacaOffset(qint32 alpaca_offset) {
    this->alpaca_offset = alpaca_offset;
    this->m_alpaca_offset_isSet = true;
}

qint32
SWGCameraSettings::getAlpacaReadoutMode() {
    return alpaca_readout_mode;
}
void
SWGCameraSettings::setAlpacaReadoutMode(qint32 alpaca_readout_mode) {
    this->alpaca_readout_mode = alpaca_readout_mode;
    this->m_alpaca_readout_mode_isSet = true;
}

qint32
SWGCameraSettings::getSaveImage() {
    return save_image;
}
void
SWGCameraSettings::setSaveImage(qint32 save_image) {
    this->save_image = save_image;
    this->m_save_image_isSet = true;
}

QString*
SWGCameraSettings::getImageFileName() {
    return image_file_name;
}
void
SWGCameraSettings::setImageFileName(QString* image_file_name) {
    this->image_file_name = image_file_name;
    this->m_image_file_name_isSet = true;
}

qint32
SWGCameraSettings::getSaveVideo() {
    return save_video;
}
void
SWGCameraSettings::setSaveVideo(qint32 save_video) {
    this->save_video = save_video;
    this->m_save_video_isSet = true;
}

QString*
SWGCameraSettings::getVideoFileCameraPath() {
    return video_file_camera_path;
}
void
SWGCameraSettings::setVideoFileCameraPath(QString* video_file_camera_path) {
    this->video_file_camera_path = video_file_camera_path;
    this->m_video_file_camera_path_isSet = true;
}

QString*
SWGCameraSettings::getVideoFileName() {
    return video_file_name;
}
void
SWGCameraSettings::setVideoFileName(QString* video_file_name) {
    this->video_file_name = video_file_name;
    this->m_video_file_name_isSet = true;
}

qint32
SWGCameraSettings::getVideoHwAcceleration() {
    return video_hw_acceleration;
}
void
SWGCameraSettings::setVideoHwAcceleration(qint32 video_hw_acceleration) {
    this->video_hw_acceleration = video_hw_acceleration;
    this->m_video_hw_acceleration_isSet = true;
}

qint32
SWGCameraSettings::getPostProcessWhiteBalanceMode() {
    return post_process_white_balance_mode;
}
void
SWGCameraSettings::setPostProcessWhiteBalanceMode(qint32 post_process_white_balance_mode) {
    this->post_process_white_balance_mode = post_process_white_balance_mode;
    this->m_post_process_white_balance_mode_isSet = true;
}

double
SWGCameraSettings::getPostProcessWhiteBalanceRedGain() {
    return post_process_white_balance_red_gain;
}
void
SWGCameraSettings::setPostProcessWhiteBalanceRedGain(double post_process_white_balance_red_gain) {
    this->post_process_white_balance_red_gain = post_process_white_balance_red_gain;
    this->m_post_process_white_balance_red_gain_isSet = true;
}

double
SWGCameraSettings::getPostProcessWhiteBalanceGreenGain() {
    return post_process_white_balance_green_gain;
}
void
SWGCameraSettings::setPostProcessWhiteBalanceGreenGain(double post_process_white_balance_green_gain) {
    this->post_process_white_balance_green_gain = post_process_white_balance_green_gain;
    this->m_post_process_white_balance_green_gain_isSet = true;
}

double
SWGCameraSettings::getPostProcessWhiteBalanceBlueGain() {
    return post_process_white_balance_blue_gain;
}
void
SWGCameraSettings::setPostProcessWhiteBalanceBlueGain(double post_process_white_balance_blue_gain) {
    this->post_process_white_balance_blue_gain = post_process_white_balance_blue_gain;
    this->m_post_process_white_balance_blue_gain_isSet = true;
}

double
SWGCameraSettings::getSaturation() {
    return saturation;
}
void
SWGCameraSettings::setSaturation(double saturation) {
    this->saturation = saturation;
    this->m_saturation_isSet = true;
}

double
SWGCameraSettings::getGamma() {
    return gamma;
}
void
SWGCameraSettings::setGamma(double gamma) {
    this->gamma = gamma;
    this->m_gamma_isSet = true;
}

double
SWGCameraSettings::getBrightness() {
    return brightness;
}
void
SWGCameraSettings::setBrightness(double brightness) {
    this->brightness = brightness;
    this->m_brightness_isSet = true;
}

double
SWGCameraSettings::getContrast() {
    return contrast;
}
void
SWGCameraSettings::setContrast(double contrast) {
    this->contrast = contrast;
    this->m_contrast_isSet = true;
}

qint32
SWGCameraSettings::getGaussianBlur() {
    return gaussian_blur;
}
void
SWGCameraSettings::setGaussianBlur(qint32 gaussian_blur) {
    this->gaussian_blur = gaussian_blur;
    this->m_gaussian_blur_isSet = true;
}

qint32
SWGCameraSettings::getMedianBlur() {
    return median_blur;
}
void
SWGCameraSettings::setMedianBlur(qint32 median_blur) {
    this->median_blur = median_blur;
    this->m_median_blur_isSet = true;
}

double
SWGCameraSettings::getSharpen() {
    return sharpen;
}
void
SWGCameraSettings::setSharpen(double sharpen) {
    this->sharpen = sharpen;
    this->m_sharpen_isSet = true;
}

double
SWGCameraSettings::getSobelEdge() {
    return sobel_edge;
}
void
SWGCameraSettings::setSobelEdge(double sobel_edge) {
    this->sobel_edge = sobel_edge;
    this->m_sobel_edge_isSet = true;
}

qint32
SWGCameraSettings::getFlipX() {
    return flip_x;
}
void
SWGCameraSettings::setFlipX(qint32 flip_x) {
    this->flip_x = flip_x;
    this->m_flip_x_isSet = true;
}

qint32
SWGCameraSettings::getFlipY() {
    return flip_y;
}
void
SWGCameraSettings::setFlipY(qint32 flip_y) {
    this->flip_y = flip_y;
    this->m_flip_y_isSet = true;
}

qint32
SWGCameraSettings::getInvertColors() {
    return invert_colors;
}
void
SWGCameraSettings::setInvertColors(qint32 invert_colors) {
    this->invert_colors = invert_colors;
    this->m_invert_colors_isSet = true;
}

qint32
SWGCameraSettings::getOverlayDateTime() {
    return overlay_date_time;
}
void
SWGCameraSettings::setOverlayDateTime(qint32 overlay_date_time) {
    this->overlay_date_time = overlay_date_time;
    this->m_overlay_date_time_isSet = true;
}

qint32
SWGCameraSettings::getDateTimeColor() {
    return date_time_color;
}
void
SWGCameraSettings::setDateTimeColor(qint32 date_time_color) {
    this->date_time_color = date_time_color;
    this->m_date_time_color_isSet = true;
}

QString*
SWGCameraSettings::getDateTimeFormat() {
    return date_time_format;
}
void
SWGCameraSettings::setDateTimeFormat(QString* date_time_format) {
    this->date_time_format = date_time_format;
    this->m_date_time_format_isSet = true;
}

qint32
SWGCameraSettings::getDateTimePosX() {
    return date_time_pos_x;
}
void
SWGCameraSettings::setDateTimePosX(qint32 date_time_pos_x) {
    this->date_time_pos_x = date_time_pos_x;
    this->m_date_time_pos_x_isSet = true;
}

qint32
SWGCameraSettings::getDateTimePosY() {
    return date_time_pos_y;
}
void
SWGCameraSettings::setDateTimePosY(qint32 date_time_pos_y) {
    this->date_time_pos_y = date_time_pos_y;
    this->m_date_time_pos_y_isSet = true;
}

qint32
SWGCameraSettings::getOverlayText() {
    return overlay_text;
}
void
SWGCameraSettings::setOverlayText(qint32 overlay_text) {
    this->overlay_text = overlay_text;
    this->m_overlay_text_isSet = true;
}

QString*
SWGCameraSettings::getOverlayTextString() {
    return overlay_text_string;
}
void
SWGCameraSettings::setOverlayTextString(QString* overlay_text_string) {
    this->overlay_text_string = overlay_text_string;
    this->m_overlay_text_string_isSet = true;
}

qint32
SWGCameraSettings::getOverlayTextColor() {
    return overlay_text_color;
}
void
SWGCameraSettings::setOverlayTextColor(qint32 overlay_text_color) {
    this->overlay_text_color = overlay_text_color;
    this->m_overlay_text_color_isSet = true;
}

QString*
SWGCameraSettings::getOverlayTextFontFamily() {
    return overlay_text_font_family;
}
void
SWGCameraSettings::setOverlayTextFontFamily(QString* overlay_text_font_family) {
    this->overlay_text_font_family = overlay_text_font_family;
    this->m_overlay_text_font_family_isSet = true;
}

double
SWGCameraSettings::getOverlayTextFontScale() {
    return overlay_text_font_scale;
}
void
SWGCameraSettings::setOverlayTextFontScale(double overlay_text_font_scale) {
    this->overlay_text_font_scale = overlay_text_font_scale;
    this->m_overlay_text_font_scale_isSet = true;
}

qint32
SWGCameraSettings::getOverlayTextPosX() {
    return overlay_text_pos_x;
}
void
SWGCameraSettings::setOverlayTextPosX(qint32 overlay_text_pos_x) {
    this->overlay_text_pos_x = overlay_text_pos_x;
    this->m_overlay_text_pos_x_isSet = true;
}

qint32
SWGCameraSettings::getOverlayTextPosY() {
    return overlay_text_pos_y;
}
void
SWGCameraSettings::setOverlayTextPosY(qint32 overlay_text_pos_y) {
    this->overlay_text_pos_y = overlay_text_pos_y;
    this->m_overlay_text_pos_y_isSet = true;
}

qint32
SWGCameraSettings::getDiffMask() {
    return diff_mask;
}
void
SWGCameraSettings::setDiffMask(qint32 diff_mask) {
    this->diff_mask = diff_mask;
    this->m_diff_mask_isSet = true;
}

qint32
SWGCameraSettings::getDiffThreshold() {
    return diff_threshold;
}
void
SWGCameraSettings::setDiffThreshold(qint32 diff_threshold) {
    this->diff_threshold = diff_threshold;
    this->m_diff_threshold_isSet = true;
}

qint32
SWGCameraSettings::getDilationSize() {
    return dilation_size;
}
void
SWGCameraSettings::setDilationSize(qint32 dilation_size) {
    this->dilation_size = dilation_size;
    this->m_dilation_size_isSet = true;
}

qint32
SWGCameraSettings::getDiffMaskHistoryFrames() {
    return diff_mask_history_frames;
}
void
SWGCameraSettings::setDiffMaskHistoryFrames(qint32 diff_mask_history_frames) {
    this->diff_mask_history_frames = diff_mask_history_frames;
    this->m_diff_mask_history_frames_isSet = true;
}

qint32
SWGCameraSettings::getDiffMaskCloseSize() {
    return diff_mask_close_size;
}
void
SWGCameraSettings::setDiffMaskCloseSize(qint32 diff_mask_close_size) {
    this->diff_mask_close_size = diff_mask_close_size;
    this->m_diff_mask_close_size_isSet = true;
}

qint32
SWGCameraSettings::getDetectionRoiX() {
    return detection_roi_x;
}
void
SWGCameraSettings::setDetectionRoiX(qint32 detection_roi_x) {
    this->detection_roi_x = detection_roi_x;
    this->m_detection_roi_x_isSet = true;
}

qint32
SWGCameraSettings::getDetectionRoiY() {
    return detection_roi_y;
}
void
SWGCameraSettings::setDetectionRoiY(qint32 detection_roi_y) {
    this->detection_roi_y = detection_roi_y;
    this->m_detection_roi_y_isSet = true;
}

qint32
SWGCameraSettings::getDetectionRoiWidth() {
    return detection_roi_width;
}
void
SWGCameraSettings::setDetectionRoiWidth(qint32 detection_roi_width) {
    this->detection_roi_width = detection_roi_width;
    this->m_detection_roi_width_isSet = true;
}

qint32
SWGCameraSettings::getDetectionRoiHeight() {
    return detection_roi_height;
}
void
SWGCameraSettings::setDetectionRoiHeight(qint32 detection_roi_height) {
    this->detection_roi_height = detection_roi_height;
    this->m_detection_roi_height_isSet = true;
}

qint32
SWGCameraSettings::getMotionDetect() {
    return motion_detect;
}
void
SWGCameraSettings::setMotionDetect(qint32 motion_detect) {
    this->motion_detect = motion_detect;
    this->m_motion_detect_isSet = true;
}

qint32
SWGCameraSettings::getMotionHistory() {
    return motion_history;
}
void
SWGCameraSettings::setMotionHistory(qint32 motion_history) {
    this->motion_history = motion_history;
    this->m_motion_history_isSet = true;
}

double
SWGCameraSettings::getMotionVarThreshold() {
    return motion_var_threshold;
}
void
SWGCameraSettings::setMotionVarThreshold(double motion_var_threshold) {
    this->motion_var_threshold = motion_var_threshold;
    this->m_motion_var_threshold_isSet = true;
}

qint32
SWGCameraSettings::getMotionDetectShadows() {
    return motion_detect_shadows;
}
void
SWGCameraSettings::setMotionDetectShadows(qint32 motion_detect_shadows) {
    this->motion_detect_shadows = motion_detect_shadows;
    this->m_motion_detect_shadows_isSet = true;
}

qint32
SWGCameraSettings::getMotionOpenSize() {
    return motion_open_size;
}
void
SWGCameraSettings::setMotionOpenSize(qint32 motion_open_size) {
    this->motion_open_size = motion_open_size;
    this->m_motion_open_size_isSet = true;
}

qint32
SWGCameraSettings::getMotionCloseSize() {
    return motion_close_size;
}
void
SWGCameraSettings::setMotionCloseSize(qint32 motion_close_size) {
    this->motion_close_size = motion_close_size;
    this->m_motion_close_size_isSet = true;
}

qint32
SWGCameraSettings::getMotionPersistenceFrames() {
    return motion_persistence_frames;
}
void
SWGCameraSettings::setMotionPersistenceFrames(qint32 motion_persistence_frames) {
    this->motion_persistence_frames = motion_persistence_frames;
    this->m_motion_persistence_frames_isSet = true;
}

qint32
SWGCameraSettings::getMotionBoxColor() {
    return motion_box_color;
}
void
SWGCameraSettings::setMotionBoxColor(qint32 motion_box_color) {
    this->motion_box_color = motion_box_color;
    this->m_motion_box_color_isSet = true;
}

qint32
SWGCameraSettings::getMinContourArea() {
    return min_contour_area;
}
void
SWGCameraSettings::setMinContourArea(qint32 min_contour_area) {
    this->min_contour_area = min_contour_area;
    this->m_min_contour_area_isSet = true;
}

qint32
SWGCameraSettings::getVideoPostProcess() {
    return video_post_process;
}
void
SWGCameraSettings::setVideoPostProcess(qint32 video_post_process) {
    this->video_post_process = video_post_process;
    this->m_video_post_process_isSet = true;
}

qint32
SWGCameraSettings::getOverlaySpectrum() {
    return overlay_spectrum;
}
void
SWGCameraSettings::setOverlaySpectrum(qint32 overlay_spectrum) {
    this->overlay_spectrum = overlay_spectrum;
    this->m_overlay_spectrum_isSet = true;
}

QString*
SWGCameraSettings::getSpectrumDevice() {
    return spectrum_device;
}
void
SWGCameraSettings::setSpectrumDevice(QString* spectrum_device) {
    this->spectrum_device = spectrum_device;
    this->m_spectrum_device_isSet = true;
}

qint32
SWGCameraSettings::getSpectrumOffsetX() {
    return spectrum_offset_x;
}
void
SWGCameraSettings::setSpectrumOffsetX(qint32 spectrum_offset_x) {
    this->spectrum_offset_x = spectrum_offset_x;
    this->m_spectrum_offset_x_isSet = true;
}

qint32
SWGCameraSettings::getSpectrumOffsetY() {
    return spectrum_offset_y;
}
void
SWGCameraSettings::setSpectrumOffsetY(qint32 spectrum_offset_y) {
    this->spectrum_offset_y = spectrum_offset_y;
    this->m_spectrum_offset_y_isSet = true;
}

double
SWGCameraSettings::getSpectrumScale() {
    return spectrum_scale;
}
void
SWGCameraSettings::setSpectrumScale(double spectrum_scale) {
    this->spectrum_scale = spectrum_scale;
    this->m_spectrum_scale_isSet = true;
}

qint32
SWGCameraSettings::getYoloEnabled() {
    return yolo_enabled;
}
void
SWGCameraSettings::setYoloEnabled(qint32 yolo_enabled) {
    this->yolo_enabled = yolo_enabled;
    this->m_yolo_enabled_isSet = true;
}

QString*
SWGCameraSettings::getYoloModelPath() {
    return yolo_model_path;
}
void
SWGCameraSettings::setYoloModelPath(QString* yolo_model_path) {
    this->yolo_model_path = yolo_model_path;
    this->m_yolo_model_path_isSet = true;
}

QString*
SWGCameraSettings::getYoloLabelsPath() {
    return yolo_labels_path;
}
void
SWGCameraSettings::setYoloLabelsPath(QString* yolo_labels_path) {
    this->yolo_labels_path = yolo_labels_path;
    this->m_yolo_labels_path_isSet = true;
}

double
SWGCameraSettings::getYoloConfThreshold() {
    return yolo_conf_threshold;
}
void
SWGCameraSettings::setYoloConfThreshold(double yolo_conf_threshold) {
    this->yolo_conf_threshold = yolo_conf_threshold;
    this->m_yolo_conf_threshold_isSet = true;
}

double
SWGCameraSettings::getYoloNmsThreshold() {
    return yolo_nms_threshold;
}
void
SWGCameraSettings::setYoloNmsThreshold(double yolo_nms_threshold) {
    this->yolo_nms_threshold = yolo_nms_threshold;
    this->m_yolo_nms_threshold_isSet = true;
}

qint32
SWGCameraSettings::getYoloBoxColor() {
    return yolo_box_color;
}
void
SWGCameraSettings::setYoloBoxColor(qint32 yolo_box_color) {
    this->yolo_box_color = yolo_box_color;
    this->m_yolo_box_color_isSet = true;
}

double
SWGCameraSettings::getYoloDisappearDebounce() {
    return yolo_disappear_debounce;
}
void
SWGCameraSettings::setYoloDisappearDebounce(double yolo_disappear_debounce) {
    this->yolo_disappear_debounce = yolo_disappear_debounce;
    this->m_yolo_disappear_debounce_isSet = true;
}

qint32
SWGCameraSettings::getYoloDnnTarget() {
    return yolo_dnn_target;
}
void
SWGCameraSettings::setYoloDnnTarget(qint32 yolo_dnn_target) {
    this->yolo_dnn_target = yolo_dnn_target;
    this->m_yolo_dnn_target_isSet = true;
}

QList<SWGCameraObjectClassSettings*>*
SWGCameraSettings::getObjectDeviceSettings() {
    return object_device_settings;
}
void
SWGCameraSettings::setObjectDeviceSettings(QList<SWGCameraObjectClassSettings*>* object_device_settings) {
    this->object_device_settings = object_device_settings;
    this->m_object_device_settings_isSet = true;
}

qint32
SWGCameraSettings::getAudioMute() {
    return audio_mute;
}
void
SWGCameraSettings::setAudioMute(qint32 audio_mute) {
    this->audio_mute = audio_mute;
    this->m_audio_mute_isSet = true;
}

QString*
SWGCameraSettings::getAudioDeviceName() {
    return audio_device_name;
}
void
SWGCameraSettings::setAudioDeviceName(QString* audio_device_name) {
    this->audio_device_name = audio_device_name;
    this->m_audio_device_name_isSet = true;
}

qint32
SWGCameraSettings::getWhiteBalanceMode() {
    return white_balance_mode;
}
void
SWGCameraSettings::setWhiteBalanceMode(qint32 white_balance_mode) {
    this->white_balance_mode = white_balance_mode;
    this->m_white_balance_mode_isSet = true;
}

double
SWGCameraSettings::getExposureCompensation() {
    return exposure_compensation;
}
void
SWGCameraSettings::setExposureCompensation(double exposure_compensation) {
    this->exposure_compensation = exposure_compensation;
    this->m_exposure_compensation_isSet = true;
}

qint32
SWGCameraSettings::getFocusMode() {
    return focus_mode;
}
void
SWGCameraSettings::setFocusMode(qint32 focus_mode) {
    this->focus_mode = focus_mode;
    this->m_focus_mode_isSet = true;
}

double
SWGCameraSettings::getFocusDistance() {
    return focus_distance;
}
void
SWGCameraSettings::setFocusDistance(double focus_distance) {
    this->focus_distance = focus_distance;
    this->m_focus_distance_isSet = true;
}

double
SWGCameraSettings::getZoomFactor() {
    return zoom_factor;
}
void
SWGCameraSettings::setZoomFactor(double zoom_factor) {
    this->zoom_factor = zoom_factor;
    this->m_zoom_factor_isSet = true;
}

qint32
SWGCameraSettings::getUseReverseApi() {
    return use_reverse_api;
}
void
SWGCameraSettings::setUseReverseApi(qint32 use_reverse_api) {
    this->use_reverse_api = use_reverse_api;
    this->m_use_reverse_api_isSet = true;
}

QString*
SWGCameraSettings::getReverseApiAddress() {
    return reverse_api_address;
}
void
SWGCameraSettings::setReverseApiAddress(QString* reverse_api_address) {
    this->reverse_api_address = reverse_api_address;
    this->m_reverse_api_address_isSet = true;
}

qint32
SWGCameraSettings::getReverseApiPort() {
    return reverse_api_port;
}
void
SWGCameraSettings::setReverseApiPort(qint32 reverse_api_port) {
    this->reverse_api_port = reverse_api_port;
    this->m_reverse_api_port_isSet = true;
}

qint32
SWGCameraSettings::getReverseApiFeatureSetIndex() {
    return reverse_api_feature_set_index;
}
void
SWGCameraSettings::setReverseApiFeatureSetIndex(qint32 reverse_api_feature_set_index) {
    this->reverse_api_feature_set_index = reverse_api_feature_set_index;
    this->m_reverse_api_feature_set_index_isSet = true;
}

qint32
SWGCameraSettings::getReverseApiFeatureIndex() {
    return reverse_api_feature_index;
}
void
SWGCameraSettings::setReverseApiFeatureIndex(qint32 reverse_api_feature_index) {
    this->reverse_api_feature_index = reverse_api_feature_index;
    this->m_reverse_api_feature_index_isSet = true;
}

SWGRollupState*
SWGCameraSettings::getRollupState() {
    return rollup_state;
}
void
SWGCameraSettings::setRollupState(SWGRollupState* rollup_state) {
    this->rollup_state = rollup_state;
    this->m_rollup_state_isSet = true;
}

qint32
SWGCameraSettings::getWorkspaceIndex() {
    return workspace_index;
}
void
SWGCameraSettings::setWorkspaceIndex(qint32 workspace_index) {
    this->workspace_index = workspace_index;
    this->m_workspace_index_isSet = true;
}


bool
SWGCameraSettings::isSet(){
    bool isObjectUpdated = false;
    do{
        if(title && *title != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_rgb_color_isSet){
            isObjectUpdated = true; break;
        }
        if(camera_protocol && *camera_protocol != QString("")){
            isObjectUpdated = true; break;
        }
        if(camera_id && *camera_id != QString("")){
            isObjectUpdated = true; break;
        }
        if(camera_description && *camera_description != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_resolution_width_isSet){
            isObjectUpdated = true; break;
        }
        if(m_resolution_height_isSet){
            isObjectUpdated = true; break;
        }
        if(m_frames_per_second_isSet){
            isObjectUpdated = true; break;
        }
        if(m_capture_mode_isSet){
            isObjectUpdated = true; break;
        }
        if(m_capture_interval_isSet){
            isObjectUpdated = true; break;
        }
        if(m_capture_interval_units_isSet){
            isObjectUpdated = true; break;
        }
        if(m_exposure_time_ms_isSet){
            isObjectUpdated = true; break;
        }
        if(m_iso_sensitivity_isSet){
            isObjectUpdated = true; break;
        }
        if(m_alpaca_discovery_enabled_isSet){
            isObjectUpdated = true; break;
        }
        if(m_alpaca_api_log_enabled_isSet){
            isObjectUpdated = true; break;
        }
        if(alpaca_host && *alpaca_host != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_alpaca_port_isSet){
            isObjectUpdated = true; break;
        }
        if(m_alpaca_focuser_enabled_isSet){
            isObjectUpdated = true; break;
        }
        if(alpaca_focuser_host && *alpaca_focuser_host != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_alpaca_focuser_port_isSet){
            isObjectUpdated = true; break;
        }
        if(m_alpaca_focuser_device_number_isSet){
            isObjectUpdated = true; break;
        }
        if(m_alpaca_focus_position_isSet){
            isObjectUpdated = true; break;
        }
        if(m_alpaca_focus_step_size_isSet){
            isObjectUpdated = true; break;
        }
        if(m_alpaca_filter_wheel_enabled_isSet){
            isObjectUpdated = true; break;
        }
        if(alpaca_filter_wheel_host && *alpaca_filter_wheel_host != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_alpaca_filter_wheel_port_isSet){
            isObjectUpdated = true; break;
        }
        if(m_alpaca_filter_wheel_device_number_isSet){
            isObjectUpdated = true; break;
        }
        if(m_alpaca_filter_wheel_position_isSet){
            isObjectUpdated = true; break;
        }
        if(m_alpaca_bin_x_isSet){
            isObjectUpdated = true; break;
        }
        if(m_alpaca_bin_y_isSet){
            isObjectUpdated = true; break;
        }
        if(m_alpaca_num_x_isSet){
            isObjectUpdated = true; break;
        }
        if(m_alpaca_num_y_isSet){
            isObjectUpdated = true; break;
        }
        if(m_alpaca_start_x_isSet){
            isObjectUpdated = true; break;
        }
        if(m_alpaca_start_y_isSet){
            isObjectUpdated = true; break;
        }
        if(m_alpaca_gain_isSet){
            isObjectUpdated = true; break;
        }
        if(m_alpaca_offset_isSet){
            isObjectUpdated = true; break;
        }
        if(m_alpaca_readout_mode_isSet){
            isObjectUpdated = true; break;
        }
        if(m_save_image_isSet){
            isObjectUpdated = true; break;
        }
        if(image_file_name && *image_file_name != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_save_video_isSet){
            isObjectUpdated = true; break;
        }
        if(video_file_camera_path && *video_file_camera_path != QString("")){
            isObjectUpdated = true; break;
        }
        if(video_file_name && *video_file_name != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_video_hw_acceleration_isSet){
            isObjectUpdated = true; break;
        }
        if(m_post_process_white_balance_mode_isSet){
            isObjectUpdated = true; break;
        }
        if(m_post_process_white_balance_red_gain_isSet){
            isObjectUpdated = true; break;
        }
        if(m_post_process_white_balance_green_gain_isSet){
            isObjectUpdated = true; break;
        }
        if(m_post_process_white_balance_blue_gain_isSet){
            isObjectUpdated = true; break;
        }
        if(m_saturation_isSet){
            isObjectUpdated = true; break;
        }
        if(m_gamma_isSet){
            isObjectUpdated = true; break;
        }
        if(m_brightness_isSet){
            isObjectUpdated = true; break;
        }
        if(m_contrast_isSet){
            isObjectUpdated = true; break;
        }
        if(m_gaussian_blur_isSet){
            isObjectUpdated = true; break;
        }
        if(m_median_blur_isSet){
            isObjectUpdated = true; break;
        }
        if(m_sharpen_isSet){
            isObjectUpdated = true; break;
        }
        if(m_sobel_edge_isSet){
            isObjectUpdated = true; break;
        }
        if(m_flip_x_isSet){
            isObjectUpdated = true; break;
        }
        if(m_flip_y_isSet){
            isObjectUpdated = true; break;
        }
        if(m_invert_colors_isSet){
            isObjectUpdated = true; break;
        }
        if(m_overlay_date_time_isSet){
            isObjectUpdated = true; break;
        }
        if(m_date_time_color_isSet){
            isObjectUpdated = true; break;
        }
        if(date_time_format && *date_time_format != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_date_time_pos_x_isSet){
            isObjectUpdated = true; break;
        }
        if(m_date_time_pos_y_isSet){
            isObjectUpdated = true; break;
        }
        if(m_overlay_text_isSet){
            isObjectUpdated = true; break;
        }
        if(overlay_text_string && *overlay_text_string != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_overlay_text_color_isSet){
            isObjectUpdated = true; break;
        }
        if(overlay_text_font_family && *overlay_text_font_family != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_overlay_text_font_scale_isSet){
            isObjectUpdated = true; break;
        }
        if(m_overlay_text_pos_x_isSet){
            isObjectUpdated = true; break;
        }
        if(m_overlay_text_pos_y_isSet){
            isObjectUpdated = true; break;
        }
        if(m_diff_mask_isSet){
            isObjectUpdated = true; break;
        }
        if(m_diff_threshold_isSet){
            isObjectUpdated = true; break;
        }
        if(m_dilation_size_isSet){
            isObjectUpdated = true; break;
        }
        if(m_diff_mask_history_frames_isSet){
            isObjectUpdated = true; break;
        }
        if(m_diff_mask_close_size_isSet){
            isObjectUpdated = true; break;
        }
        if(m_detection_roi_x_isSet){
            isObjectUpdated = true; break;
        }
        if(m_detection_roi_y_isSet){
            isObjectUpdated = true; break;
        }
        if(m_detection_roi_width_isSet){
            isObjectUpdated = true; break;
        }
        if(m_detection_roi_height_isSet){
            isObjectUpdated = true; break;
        }
        if(m_motion_detect_isSet){
            isObjectUpdated = true; break;
        }
        if(m_motion_history_isSet){
            isObjectUpdated = true; break;
        }
        if(m_motion_var_threshold_isSet){
            isObjectUpdated = true; break;
        }
        if(m_motion_detect_shadows_isSet){
            isObjectUpdated = true; break;
        }
        if(m_motion_open_size_isSet){
            isObjectUpdated = true; break;
        }
        if(m_motion_close_size_isSet){
            isObjectUpdated = true; break;
        }
        if(m_motion_persistence_frames_isSet){
            isObjectUpdated = true; break;
        }
        if(m_motion_box_color_isSet){
            isObjectUpdated = true; break;
        }
        if(m_min_contour_area_isSet){
            isObjectUpdated = true; break;
        }
        if(m_video_post_process_isSet){
            isObjectUpdated = true; break;
        }
        if(m_overlay_spectrum_isSet){
            isObjectUpdated = true; break;
        }
        if(spectrum_device && *spectrum_device != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_spectrum_offset_x_isSet){
            isObjectUpdated = true; break;
        }
        if(m_spectrum_offset_y_isSet){
            isObjectUpdated = true; break;
        }
        if(m_spectrum_scale_isSet){
            isObjectUpdated = true; break;
        }
        if(m_yolo_enabled_isSet){
            isObjectUpdated = true; break;
        }
        if(yolo_model_path && *yolo_model_path != QString("")){
            isObjectUpdated = true; break;
        }
        if(yolo_labels_path && *yolo_labels_path != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_yolo_conf_threshold_isSet){
            isObjectUpdated = true; break;
        }
        if(m_yolo_nms_threshold_isSet){
            isObjectUpdated = true; break;
        }
        if(m_yolo_box_color_isSet){
            isObjectUpdated = true; break;
        }
        if(m_yolo_disappear_debounce_isSet){
            isObjectUpdated = true; break;
        }
        if(m_yolo_dnn_target_isSet){
            isObjectUpdated = true; break;
        }
        if(object_device_settings && (object_device_settings->size() > 0)){
            isObjectUpdated = true; break;
        }
        if(m_audio_mute_isSet){
            isObjectUpdated = true; break;
        }
        if(audio_device_name && *audio_device_name != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_white_balance_mode_isSet){
            isObjectUpdated = true; break;
        }
        if(m_exposure_compensation_isSet){
            isObjectUpdated = true; break;
        }
        if(m_focus_mode_isSet){
            isObjectUpdated = true; break;
        }
        if(m_focus_distance_isSet){
            isObjectUpdated = true; break;
        }
        if(m_zoom_factor_isSet){
            isObjectUpdated = true; break;
        }
        if(m_use_reverse_api_isSet){
            isObjectUpdated = true; break;
        }
        if(reverse_api_address && *reverse_api_address != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_reverse_api_port_isSet){
            isObjectUpdated = true; break;
        }
        if(m_reverse_api_feature_set_index_isSet){
            isObjectUpdated = true; break;
        }
        if(m_reverse_api_feature_index_isSet){
            isObjectUpdated = true; break;
        }
        if(rollup_state && rollup_state->isSet()){
            isObjectUpdated = true; break;
        }
        if(m_workspace_index_isSet){
            isObjectUpdated = true; break;
        }
    }while(false);
    return isObjectUpdated;
}
}

