/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGCameraActions_recordVideo.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace SWGSDRangel {

SWGCameraActions_recordVideo::SWGCameraActions_recordVideo(QString* json) {
    init();
    this->fromJson(*json);
}

SWGCameraActions_recordVideo::SWGCameraActions_recordVideo() {
    filename = nullptr;
    m_filename_isSet = false;
    record_calibrated_media = 0;
    m_record_calibrated_media_isSet = false;
    record_filtered_media = 0;
    m_record_filtered_media_isSet = false;
    record_post_processed_media = 0;
    m_record_post_processed_media_isSet = false;
    duration = 0;
    m_duration_isSet = false;
}

SWGCameraActions_recordVideo::~SWGCameraActions_recordVideo() {
    this->cleanup();
}

void
SWGCameraActions_recordVideo::init() {
    filename = new QString("");
    m_filename_isSet = false;
    record_calibrated_media = 0;
    m_record_calibrated_media_isSet = false;
    record_filtered_media = 0;
    m_record_filtered_media_isSet = false;
    record_post_processed_media = 0;
    m_record_post_processed_media_isSet = false;
    duration = 0;
    m_duration_isSet = false;
}

void
SWGCameraActions_recordVideo::cleanup() {
    if(filename != nullptr) { 
        delete filename;
    }




}

SWGCameraActions_recordVideo*
SWGCameraActions_recordVideo::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGCameraActions_recordVideo::fromJsonObject(QJsonObject &pJson) {
    ::SWGSDRangel::setValue(&filename, pJson["filename"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&record_calibrated_media, pJson["recordCalibratedMedia"], "qint32", "");
    
    ::SWGSDRangel::setValue(&record_filtered_media, pJson["recordFilteredMedia"], "qint32", "");
    
    ::SWGSDRangel::setValue(&record_post_processed_media, pJson["recordPostProcessedMedia"], "qint32", "");
    
    ::SWGSDRangel::setValue(&duration, pJson["duration"], "qint32", "");
    
}

QString
SWGCameraActions_recordVideo::asJson ()
{
    QJsonObject* obj = this->asJsonObject();

    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    delete obj;
    return QString(bytes);
}

QJsonObject*
SWGCameraActions_recordVideo::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    if(filename != nullptr && *filename != QString("")){
        toJsonValue(QString("filename"), filename, obj, QString("QString"));
    }
    if(m_record_calibrated_media_isSet){
        obj->insert("recordCalibratedMedia", QJsonValue(record_calibrated_media));
    }
    if(m_record_filtered_media_isSet){
        obj->insert("recordFilteredMedia", QJsonValue(record_filtered_media));
    }
    if(m_record_post_processed_media_isSet){
        obj->insert("recordPostProcessedMedia", QJsonValue(record_post_processed_media));
    }
    if(m_duration_isSet){
        obj->insert("duration", QJsonValue(duration));
    }

    return obj;
}

QString*
SWGCameraActions_recordVideo::getFilename() {
    return filename;
}
void
SWGCameraActions_recordVideo::setFilename(QString* filename) {
    this->filename = filename;
    this->m_filename_isSet = true;
}

qint32
SWGCameraActions_recordVideo::getRecordCalibratedMedia() {
    return record_calibrated_media;
}
void
SWGCameraActions_recordVideo::setRecordCalibratedMedia(qint32 record_calibrated_media) {
    this->record_calibrated_media = record_calibrated_media;
    this->m_record_calibrated_media_isSet = true;
}

qint32
SWGCameraActions_recordVideo::getRecordFilteredMedia() {
    return record_filtered_media;
}
void
SWGCameraActions_recordVideo::setRecordFilteredMedia(qint32 record_filtered_media) {
    this->record_filtered_media = record_filtered_media;
    this->m_record_filtered_media_isSet = true;
}

qint32
SWGCameraActions_recordVideo::getRecordPostProcessedMedia() {
    return record_post_processed_media;
}
void
SWGCameraActions_recordVideo::setRecordPostProcessedMedia(qint32 record_post_processed_media) {
    this->record_post_processed_media = record_post_processed_media;
    this->m_record_post_processed_media_isSet = true;
}

qint32
SWGCameraActions_recordVideo::getDuration() {
    return duration;
}
void
SWGCameraActions_recordVideo::setDuration(qint32 duration) {
    this->duration = duration;
    this->m_duration_isSet = true;
}


bool
SWGCameraActions_recordVideo::isSet(){
    bool isObjectUpdated = false;
    do{
        if(filename && *filename != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_record_calibrated_media_isSet){
            isObjectUpdated = true; break;
        }
        if(m_record_filtered_media_isSet){
            isObjectUpdated = true; break;
        }
        if(m_record_post_processed_media_isSet){
            isObjectUpdated = true; break;
        }
        if(m_duration_isSet){
            isObjectUpdated = true; break;
        }
    }while(false);
    return isObjectUpdated;
}
}

