/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGCameraReport.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace SWGSDRangel {

SWGCameraReport::SWGCameraReport(QString* json) {
    init();
    this->fromJson(*json);
}

SWGCameraReport::SWGCameraReport() {
    running_state = 0;
    m_running_state_isSet = false;
    cloud_coverage_percent = 0.0f;
    m_cloud_coverage_percent_isSet = false;
    cloud_coverage_valid = 0;
    m_cloud_coverage_valid_isSet = false;
}

SWGCameraReport::~SWGCameraReport() {
    this->cleanup();
}

void
SWGCameraReport::init() {
    running_state = 0;
    m_running_state_isSet = false;
    cloud_coverage_percent = 0.0f;
    m_cloud_coverage_percent_isSet = false;
    cloud_coverage_valid = 0;
    m_cloud_coverage_valid_isSet = false;
}

void
SWGCameraReport::cleanup() {

}

SWGCameraReport*
SWGCameraReport::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGCameraReport::fromJsonObject(QJsonObject &pJson) {
    ::SWGSDRangel::setValue(&running_state, pJson["runningState"], "qint32", "");

    ::SWGSDRangel::setValue(&cloud_coverage_percent, pJson["cloudCoveragePercent"], "float", "");

    ::SWGSDRangel::setValue(&cloud_coverage_valid, pJson["cloudCoverageValid"], "qint32", "");

}

QString
SWGCameraReport::asJson ()
{
    QJsonObject* obj = this->asJsonObject();

    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    delete obj;
    return QString(bytes);
}

QJsonObject*
SWGCameraReport::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    if(m_running_state_isSet){
        obj->insert("runningState", QJsonValue(running_state));
    }
    if(m_cloud_coverage_percent_isSet){
        obj->insert("cloudCoveragePercent", QJsonValue(cloud_coverage_percent));
    }
    if(m_cloud_coverage_valid_isSet){
        obj->insert("cloudCoverageValid", QJsonValue(cloud_coverage_valid));
    }

    return obj;
}

qint32
SWGCameraReport::getRunningState() {
    return running_state;
}
void
SWGCameraReport::setRunningState(qint32 running_state) {
    this->running_state = running_state;
    this->m_running_state_isSet = true;
}

float
SWGCameraReport::getCloudCoveragePercent() {
    return cloud_coverage_percent;
}
void
SWGCameraReport::setCloudCoveragePercent(float cloud_coverage_percent) {
    this->cloud_coverage_percent = cloud_coverage_percent;
    this->m_cloud_coverage_percent_isSet = true;
}

qint32
SWGCameraReport::getCloudCoverageValid() {
    return cloud_coverage_valid;
}
void
SWGCameraReport::setCloudCoverageValid(qint32 cloud_coverage_valid) {
    this->cloud_coverage_valid = cloud_coverage_valid;
    this->m_cloud_coverage_valid_isSet = true;
}


bool
SWGCameraReport::isSet(){
    bool isObjectUpdated = false;
    do{
        if(m_running_state_isSet){
            isObjectUpdated = true; break;
        }
        if(m_cloud_coverage_percent_isSet){
            isObjectUpdated = true; break;
        }
        if(m_cloud_coverage_valid_isSet){
            isObjectUpdated = true; break;
        }
    }while(false);
    return isObjectUpdated;
}
}

