/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGCameraObjectDeviceSettings.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace SWGSDRangel {

SWGCameraObjectDeviceSettings::SWGCameraObjectDeviceSettings(QString* json) {
    init();
    this->fromJson(*json);
}

SWGCameraObjectDeviceSettings::SWGCameraObjectDeviceSettings() {
    device_set_index = 0;
    m_device_set_index_isSet = false;
    preset_group = nullptr;
    m_preset_group_isSet = false;
    preset_frequency = 0L;
    m_preset_frequency_isSet = false;
    preset_description = nullptr;
    m_preset_description_isSet = false;
    start_on_detect = 0;
    m_start_on_detect_isSet = false;
    stop_on_disappear = 0;
    m_stop_on_disappear_isSet = false;
    start_stop_file_sink = 0;
    m_start_stop_file_sink_isSet = false;
    record_video = 0;
    m_record_video_isSet = false;
    detect_command = nullptr;
    m_detect_command_isSet = false;
    disappear_command = nullptr;
    m_disappear_command_isSet = false;
    detect_speech = nullptr;
    m_detect_speech_isSet = false;
    disappear_speech = nullptr;
    m_disappear_speech_isSet = false;
}

SWGCameraObjectDeviceSettings::~SWGCameraObjectDeviceSettings() {
    this->cleanup();
}

void
SWGCameraObjectDeviceSettings::init() {
    device_set_index = 0;
    m_device_set_index_isSet = false;
    preset_group = new QString("");
    m_preset_group_isSet = false;
    preset_frequency = 0L;
    m_preset_frequency_isSet = false;
    preset_description = new QString("");
    m_preset_description_isSet = false;
    start_on_detect = 0;
    m_start_on_detect_isSet = false;
    stop_on_disappear = 0;
    m_stop_on_disappear_isSet = false;
    start_stop_file_sink = 0;
    m_start_stop_file_sink_isSet = false;
    record_video = 0;
    m_record_video_isSet = false;
    detect_command = new QString("");
    m_detect_command_isSet = false;
    disappear_command = new QString("");
    m_disappear_command_isSet = false;
    detect_speech = new QString("");
    m_detect_speech_isSet = false;
    disappear_speech = new QString("");
    m_disappear_speech_isSet = false;
}

void
SWGCameraObjectDeviceSettings::cleanup() {

    if(preset_group != nullptr) { 
        delete preset_group;
    }

    if(preset_description != nullptr) { 
        delete preset_description;
    }




    if(detect_command != nullptr) { 
        delete detect_command;
    }
    if(disappear_command != nullptr) { 
        delete disappear_command;
    }
    if(detect_speech != nullptr) { 
        delete detect_speech;
    }
    if(disappear_speech != nullptr) { 
        delete disappear_speech;
    }
}

SWGCameraObjectDeviceSettings*
SWGCameraObjectDeviceSettings::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGCameraObjectDeviceSettings::fromJsonObject(QJsonObject &pJson) {
    ::SWGSDRangel::setValue(&device_set_index, pJson["deviceSetIndex"], "qint32", "");
    
    ::SWGSDRangel::setValue(&preset_group, pJson["presetGroup"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&preset_frequency, pJson["presetFrequency"], "qint64", "");
    
    ::SWGSDRangel::setValue(&preset_description, pJson["presetDescription"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&start_on_detect, pJson["startOnDetect"], "qint32", "");
    
    ::SWGSDRangel::setValue(&stop_on_disappear, pJson["stopOnDisappear"], "qint32", "");
    
    ::SWGSDRangel::setValue(&start_stop_file_sink, pJson["startStopFileSink"], "qint32", "");
    
    ::SWGSDRangel::setValue(&record_video, pJson["recordVideo"], "qint32", "");
    
    ::SWGSDRangel::setValue(&detect_command, pJson["detectCommand"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&disappear_command, pJson["disappearCommand"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&detect_speech, pJson["detectSpeech"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&disappear_speech, pJson["disappearSpeech"], "QString", "QString");
    
}

QString
SWGCameraObjectDeviceSettings::asJson ()
{
    QJsonObject* obj = this->asJsonObject();

    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    delete obj;
    return QString(bytes);
}

QJsonObject*
SWGCameraObjectDeviceSettings::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    if(m_device_set_index_isSet){
        obj->insert("deviceSetIndex", QJsonValue(device_set_index));
    }
    if(preset_group != nullptr && *preset_group != QString("")){
        toJsonValue(QString("presetGroup"), preset_group, obj, QString("QString"));
    }
    if(m_preset_frequency_isSet){
        obj->insert("presetFrequency", QJsonValue(preset_frequency));
    }
    if(preset_description != nullptr && *preset_description != QString("")){
        toJsonValue(QString("presetDescription"), preset_description, obj, QString("QString"));
    }
    if(m_start_on_detect_isSet){
        obj->insert("startOnDetect", QJsonValue(start_on_detect));
    }
    if(m_stop_on_disappear_isSet){
        obj->insert("stopOnDisappear", QJsonValue(stop_on_disappear));
    }
    if(m_start_stop_file_sink_isSet){
        obj->insert("startStopFileSink", QJsonValue(start_stop_file_sink));
    }
    if(m_record_video_isSet){
        obj->insert("recordVideo", QJsonValue(record_video));
    }
    if(detect_command != nullptr && *detect_command != QString("")){
        toJsonValue(QString("detectCommand"), detect_command, obj, QString("QString"));
    }
    if(disappear_command != nullptr && *disappear_command != QString("")){
        toJsonValue(QString("disappearCommand"), disappear_command, obj, QString("QString"));
    }
    if(detect_speech != nullptr && *detect_speech != QString("")){
        toJsonValue(QString("detectSpeech"), detect_speech, obj, QString("QString"));
    }
    if(disappear_speech != nullptr && *disappear_speech != QString("")){
        toJsonValue(QString("disappearSpeech"), disappear_speech, obj, QString("QString"));
    }

    return obj;
}

qint32
SWGCameraObjectDeviceSettings::getDeviceSetIndex() {
    return device_set_index;
}
void
SWGCameraObjectDeviceSettings::setDeviceSetIndex(qint32 device_set_index) {
    this->device_set_index = device_set_index;
    this->m_device_set_index_isSet = true;
}

QString*
SWGCameraObjectDeviceSettings::getPresetGroup() {
    return preset_group;
}
void
SWGCameraObjectDeviceSettings::setPresetGroup(QString* preset_group) {
    this->preset_group = preset_group;
    this->m_preset_group_isSet = true;
}

qint64
SWGCameraObjectDeviceSettings::getPresetFrequency() {
    return preset_frequency;
}
void
SWGCameraObjectDeviceSettings::setPresetFrequency(qint64 preset_frequency) {
    this->preset_frequency = preset_frequency;
    this->m_preset_frequency_isSet = true;
}

QString*
SWGCameraObjectDeviceSettings::getPresetDescription() {
    return preset_description;
}
void
SWGCameraObjectDeviceSettings::setPresetDescription(QString* preset_description) {
    this->preset_description = preset_description;
    this->m_preset_description_isSet = true;
}

qint32
SWGCameraObjectDeviceSettings::getStartOnDetect() {
    return start_on_detect;
}
void
SWGCameraObjectDeviceSettings::setStartOnDetect(qint32 start_on_detect) {
    this->start_on_detect = start_on_detect;
    this->m_start_on_detect_isSet = true;
}

qint32
SWGCameraObjectDeviceSettings::getStopOnDisappear() {
    return stop_on_disappear;
}
void
SWGCameraObjectDeviceSettings::setStopOnDisappear(qint32 stop_on_disappear) {
    this->stop_on_disappear = stop_on_disappear;
    this->m_stop_on_disappear_isSet = true;
}

qint32
SWGCameraObjectDeviceSettings::getStartStopFileSink() {
    return start_stop_file_sink;
}
void
SWGCameraObjectDeviceSettings::setStartStopFileSink(qint32 start_stop_file_sink) {
    this->start_stop_file_sink = start_stop_file_sink;
    this->m_start_stop_file_sink_isSet = true;
}

qint32
SWGCameraObjectDeviceSettings::getRecordVideo() {
    return record_video;
}
void
SWGCameraObjectDeviceSettings::setRecordVideo(qint32 record_video) {
    this->record_video = record_video;
    this->m_record_video_isSet = true;
}

QString*
SWGCameraObjectDeviceSettings::getDetectCommand() {
    return detect_command;
}
void
SWGCameraObjectDeviceSettings::setDetectCommand(QString* detect_command) {
    this->detect_command = detect_command;
    this->m_detect_command_isSet = true;
}

QString*
SWGCameraObjectDeviceSettings::getDisappearCommand() {
    return disappear_command;
}
void
SWGCameraObjectDeviceSettings::setDisappearCommand(QString* disappear_command) {
    this->disappear_command = disappear_command;
    this->m_disappear_command_isSet = true;
}

QString*
SWGCameraObjectDeviceSettings::getDetectSpeech() {
    return detect_speech;
}
void
SWGCameraObjectDeviceSettings::setDetectSpeech(QString* detect_speech) {
    this->detect_speech = detect_speech;
    this->m_detect_speech_isSet = true;
}

QString*
SWGCameraObjectDeviceSettings::getDisappearSpeech() {
    return disappear_speech;
}
void
SWGCameraObjectDeviceSettings::setDisappearSpeech(QString* disappear_speech) {
    this->disappear_speech = disappear_speech;
    this->m_disappear_speech_isSet = true;
}


bool
SWGCameraObjectDeviceSettings::isSet(){
    bool isObjectUpdated = false;
    do{
        if(m_device_set_index_isSet){
            isObjectUpdated = true; break;
        }
        if(preset_group && *preset_group != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_preset_frequency_isSet){
            isObjectUpdated = true; break;
        }
        if(preset_description && *preset_description != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_start_on_detect_isSet){
            isObjectUpdated = true; break;
        }
        if(m_stop_on_disappear_isSet){
            isObjectUpdated = true; break;
        }
        if(m_start_stop_file_sink_isSet){
            isObjectUpdated = true; break;
        }
        if(m_record_video_isSet){
            isObjectUpdated = true; break;
        }
        if(detect_command && *detect_command != QString("")){
            isObjectUpdated = true; break;
        }
        if(disappear_command && *disappear_command != QString("")){
            isObjectUpdated = true; break;
        }
        if(detect_speech && *detect_speech != QString("")){
            isObjectUpdated = true; break;
        }
        if(disappear_speech && *disappear_speech != QString("")){
            isObjectUpdated = true; break;
        }
    }while(false);
    return isObjectUpdated;
}
}

