/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGCameraSettings.h
 *
 * Camera feature settings
 */

#ifndef SWGCameraSettings_H_
#define SWGCameraSettings_H_

#include <QJsonObject>


#include "SWGCameraObjectClassSettings.h"
#include "SWGRollupState.h"
#include <QList>
#include <QString>

#include "SWGObject.h"
#include "export.h"

namespace SWGSDRangel {

class SWG_API SWGCameraSettings: public SWGObject {
public:
    SWGCameraSettings();
    SWGCameraSettings(QString* json);
    virtual ~SWGCameraSettings();
    void init();
    void cleanup();

    virtual QString asJson () override;
    virtual QJsonObject* asJsonObject() override;
    virtual void fromJsonObject(QJsonObject &json) override;
    virtual SWGCameraSettings* fromJson(QString &jsonString) override;

    QString* getTitle();
    void setTitle(QString* title);

    qint32 getRgbColor();
    void setRgbColor(qint32 rgb_color);

    QString* getCameraProtocol();
    void setCameraProtocol(QString* camera_protocol);

    QString* getCameraId();
    void setCameraId(QString* camera_id);

    QString* getCameraDescription();
    void setCameraDescription(QString* camera_description);

    qint32 getResolutionWidth();
    void setResolutionWidth(qint32 resolution_width);

    qint32 getResolutionHeight();
    void setResolutionHeight(qint32 resolution_height);

    qint32 getFramesPerSecond();
    void setFramesPerSecond(qint32 frames_per_second);

    qint32 getCaptureMode();
    void setCaptureMode(qint32 capture_mode);

    double getCaptureInterval();
    void setCaptureInterval(double capture_interval);

    qint32 getCaptureIntervalUnits();
    void setCaptureIntervalUnits(qint32 capture_interval_units);

    double getExposureTimeMs();
    void setExposureTimeMs(double exposure_time_ms);

    qint32 getIsoSensitivity();
    void setIsoSensitivity(qint32 iso_sensitivity);

    qint32 getAlpacaDiscoveryEnabled();
    void setAlpacaDiscoveryEnabled(qint32 alpaca_discovery_enabled);

    qint32 getAlpacaApiLogEnabled();
    void setAlpacaApiLogEnabled(qint32 alpaca_api_log_enabled);

    QString* getAlpacaHost();
    void setAlpacaHost(QString* alpaca_host);

    qint32 getAlpacaPort();
    void setAlpacaPort(qint32 alpaca_port);

    qint32 getAlpacaFocuserEnabled();
    void setAlpacaFocuserEnabled(qint32 alpaca_focuser_enabled);

    QString* getAlpacaFocuserHost();
    void setAlpacaFocuserHost(QString* alpaca_focuser_host);

    qint32 getAlpacaFocuserPort();
    void setAlpacaFocuserPort(qint32 alpaca_focuser_port);

    qint32 getAlpacaFocuserDeviceNumber();
    void setAlpacaFocuserDeviceNumber(qint32 alpaca_focuser_device_number);

    qint32 getAlpacaFocusPosition();
    void setAlpacaFocusPosition(qint32 alpaca_focus_position);

    qint32 getAlpacaFocusStepSize();
    void setAlpacaFocusStepSize(qint32 alpaca_focus_step_size);

    qint32 getAlpacaFilterWheelEnabled();
    void setAlpacaFilterWheelEnabled(qint32 alpaca_filter_wheel_enabled);

    QString* getAlpacaFilterWheelHost();
    void setAlpacaFilterWheelHost(QString* alpaca_filter_wheel_host);

    qint32 getAlpacaFilterWheelPort();
    void setAlpacaFilterWheelPort(qint32 alpaca_filter_wheel_port);

    qint32 getAlpacaFilterWheelDeviceNumber();
    void setAlpacaFilterWheelDeviceNumber(qint32 alpaca_filter_wheel_device_number);

    qint32 getAlpacaFilterWheelPosition();
    void setAlpacaFilterWheelPosition(qint32 alpaca_filter_wheel_position);

    qint32 getAlpacaBinX();
    void setAlpacaBinX(qint32 alpaca_bin_x);

    qint32 getAlpacaBinY();
    void setAlpacaBinY(qint32 alpaca_bin_y);

    qint32 getAlpacaNumX();
    void setAlpacaNumX(qint32 alpaca_num_x);

    qint32 getAlpacaNumY();
    void setAlpacaNumY(qint32 alpaca_num_y);

    qint32 getAlpacaStartX();
    void setAlpacaStartX(qint32 alpaca_start_x);

    qint32 getAlpacaStartY();
    void setAlpacaStartY(qint32 alpaca_start_y);

    qint32 getAlpacaGain();
    void setAlpacaGain(qint32 alpaca_gain);

    qint32 getAlpacaOffset();
    void setAlpacaOffset(qint32 alpaca_offset);

    qint32 getAlpacaReadoutMode();
    void setAlpacaReadoutMode(qint32 alpaca_readout_mode);

    qint32 getSaveImage();
    void setSaveImage(qint32 save_image);

    QString* getImageFileName();
    void setImageFileName(QString* image_file_name);

    qint32 getSaveVideo();
    void setSaveVideo(qint32 save_video);

    QString* getVideoFileCameraPath();
    void setVideoFileCameraPath(QString* video_file_camera_path);

    QString* getVideoFileName();
    void setVideoFileName(QString* video_file_name);

    qint32 getVideoHwAcceleration();
    void setVideoHwAcceleration(qint32 video_hw_acceleration);

    qint32 getPostProcessWhiteBalanceMode();
    void setPostProcessWhiteBalanceMode(qint32 post_process_white_balance_mode);

    double getPostProcessWhiteBalanceRedGain();
    void setPostProcessWhiteBalanceRedGain(double post_process_white_balance_red_gain);

    double getPostProcessWhiteBalanceGreenGain();
    void setPostProcessWhiteBalanceGreenGain(double post_process_white_balance_green_gain);

    double getPostProcessWhiteBalanceBlueGain();
    void setPostProcessWhiteBalanceBlueGain(double post_process_white_balance_blue_gain);

    double getSaturation();
    void setSaturation(double saturation);

    double getGamma();
    void setGamma(double gamma);

    double getBrightness();
    void setBrightness(double brightness);

    double getContrast();
    void setContrast(double contrast);

    qint32 getGaussianBlur();
    void setGaussianBlur(qint32 gaussian_blur);

    qint32 getMedianBlur();
    void setMedianBlur(qint32 median_blur);

    double getSharpen();
    void setSharpen(double sharpen);

    double getSobelEdge();
    void setSobelEdge(double sobel_edge);

    qint32 getFlipX();
    void setFlipX(qint32 flip_x);

    qint32 getFlipY();
    void setFlipY(qint32 flip_y);

    qint32 getInvertColors();
    void setInvertColors(qint32 invert_colors);

    qint32 getOverlayDateTime();
    void setOverlayDateTime(qint32 overlay_date_time);

    qint32 getDateTimeColor();
    void setDateTimeColor(qint32 date_time_color);

    QString* getDateTimeFormat();
    void setDateTimeFormat(QString* date_time_format);

    qint32 getDateTimePosX();
    void setDateTimePosX(qint32 date_time_pos_x);

    qint32 getDateTimePosY();
    void setDateTimePosY(qint32 date_time_pos_y);

    qint32 getOverlayText();
    void setOverlayText(qint32 overlay_text);

    QString* getOverlayTextString();
    void setOverlayTextString(QString* overlay_text_string);

    qint32 getOverlayTextColor();
    void setOverlayTextColor(qint32 overlay_text_color);

    QString* getOverlayTextFontFamily();
    void setOverlayTextFontFamily(QString* overlay_text_font_family);

    double getOverlayTextFontScale();
    void setOverlayTextFontScale(double overlay_text_font_scale);

    qint32 getOverlayTextPosX();
    void setOverlayTextPosX(qint32 overlay_text_pos_x);

    qint32 getOverlayTextPosY();
    void setOverlayTextPosY(qint32 overlay_text_pos_y);

    qint32 getDiffMask();
    void setDiffMask(qint32 diff_mask);

    qint32 getDiffThreshold();
    void setDiffThreshold(qint32 diff_threshold);

    qint32 getDilationSize();
    void setDilationSize(qint32 dilation_size);

    qint32 getDiffMaskHistoryFrames();
    void setDiffMaskHistoryFrames(qint32 diff_mask_history_frames);

    qint32 getDiffMaskCloseSize();
    void setDiffMaskCloseSize(qint32 diff_mask_close_size);

    qint32 getDetectionRoiX();
    void setDetectionRoiX(qint32 detection_roi_x);

    qint32 getDetectionRoiY();
    void setDetectionRoiY(qint32 detection_roi_y);

    qint32 getDetectionRoiWidth();
    void setDetectionRoiWidth(qint32 detection_roi_width);

    qint32 getDetectionRoiHeight();
    void setDetectionRoiHeight(qint32 detection_roi_height);

    qint32 getMotionDetect();
    void setMotionDetect(qint32 motion_detect);

    qint32 getMotionHistory();
    void setMotionHistory(qint32 motion_history);

    double getMotionVarThreshold();
    void setMotionVarThreshold(double motion_var_threshold);

    qint32 getMotionDetectShadows();
    void setMotionDetectShadows(qint32 motion_detect_shadows);

    qint32 getMotionOpenSize();
    void setMotionOpenSize(qint32 motion_open_size);

    qint32 getMotionCloseSize();
    void setMotionCloseSize(qint32 motion_close_size);

    qint32 getMotionPersistenceFrames();
    void setMotionPersistenceFrames(qint32 motion_persistence_frames);

    qint32 getMotionBoxColor();
    void setMotionBoxColor(qint32 motion_box_color);

    qint32 getMinContourArea();
    void setMinContourArea(qint32 min_contour_area);

    qint32 getVideoPostProcess();
    void setVideoPostProcess(qint32 video_post_process);

    qint32 getOverlaySpectrum();
    void setOverlaySpectrum(qint32 overlay_spectrum);

    QString* getSpectrumDevice();
    void setSpectrumDevice(QString* spectrum_device);

    qint32 getSpectrumOffsetX();
    void setSpectrumOffsetX(qint32 spectrum_offset_x);

    qint32 getSpectrumOffsetY();
    void setSpectrumOffsetY(qint32 spectrum_offset_y);

    double getSpectrumScale();
    void setSpectrumScale(double spectrum_scale);

    qint32 getYoloEnabled();
    void setYoloEnabled(qint32 yolo_enabled);

    QString* getYoloModelPath();
    void setYoloModelPath(QString* yolo_model_path);

    QString* getYoloLabelsPath();
    void setYoloLabelsPath(QString* yolo_labels_path);

    double getYoloConfThreshold();
    void setYoloConfThreshold(double yolo_conf_threshold);

    double getYoloNmsThreshold();
    void setYoloNmsThreshold(double yolo_nms_threshold);

    qint32 getYoloBoxColor();
    void setYoloBoxColor(qint32 yolo_box_color);

    double getYoloDisappearDebounce();
    void setYoloDisappearDebounce(double yolo_disappear_debounce);

    qint32 getYoloDnnTarget();
    void setYoloDnnTarget(qint32 yolo_dnn_target);

    QList<SWGCameraObjectClassSettings*>* getObjectDeviceSettings();
    void setObjectDeviceSettings(QList<SWGCameraObjectClassSettings*>* object_device_settings);

    qint32 getAudioMute();
    void setAudioMute(qint32 audio_mute);

    QString* getAudioDeviceName();
    void setAudioDeviceName(QString* audio_device_name);

    qint32 getWhiteBalanceMode();
    void setWhiteBalanceMode(qint32 white_balance_mode);

    double getExposureCompensation();
    void setExposureCompensation(double exposure_compensation);

    qint32 getFocusMode();
    void setFocusMode(qint32 focus_mode);

    double getFocusDistance();
    void setFocusDistance(double focus_distance);

    double getZoomFactor();
    void setZoomFactor(double zoom_factor);

    qint32 getUseReverseApi();
    void setUseReverseApi(qint32 use_reverse_api);

    QString* getReverseApiAddress();
    void setReverseApiAddress(QString* reverse_api_address);

    qint32 getReverseApiPort();
    void setReverseApiPort(qint32 reverse_api_port);

    qint32 getReverseApiFeatureSetIndex();
    void setReverseApiFeatureSetIndex(qint32 reverse_api_feature_set_index);

    qint32 getReverseApiFeatureIndex();
    void setReverseApiFeatureIndex(qint32 reverse_api_feature_index);

    SWGRollupState* getRollupState();
    void setRollupState(SWGRollupState* rollup_state);

    qint32 getWorkspaceIndex();
    void setWorkspaceIndex(qint32 workspace_index);


    virtual bool isSet() override;

private:
    QString* title;
    bool m_title_isSet;

    qint32 rgb_color;
    bool m_rgb_color_isSet;

    QString* camera_protocol;
    bool m_camera_protocol_isSet;

    QString* camera_id;
    bool m_camera_id_isSet;

    QString* camera_description;
    bool m_camera_description_isSet;

    qint32 resolution_width;
    bool m_resolution_width_isSet;

    qint32 resolution_height;
    bool m_resolution_height_isSet;

    qint32 frames_per_second;
    bool m_frames_per_second_isSet;

    qint32 capture_mode;
    bool m_capture_mode_isSet;

    double capture_interval;
    bool m_capture_interval_isSet;

    qint32 capture_interval_units;
    bool m_capture_interval_units_isSet;

    double exposure_time_ms;
    bool m_exposure_time_ms_isSet;

    qint32 iso_sensitivity;
    bool m_iso_sensitivity_isSet;

    qint32 alpaca_discovery_enabled;
    bool m_alpaca_discovery_enabled_isSet;

    qint32 alpaca_api_log_enabled;
    bool m_alpaca_api_log_enabled_isSet;

    QString* alpaca_host;
    bool m_alpaca_host_isSet;

    qint32 alpaca_port;
    bool m_alpaca_port_isSet;

    qint32 alpaca_focuser_enabled;
    bool m_alpaca_focuser_enabled_isSet;

    QString* alpaca_focuser_host;
    bool m_alpaca_focuser_host_isSet;

    qint32 alpaca_focuser_port;
    bool m_alpaca_focuser_port_isSet;

    qint32 alpaca_focuser_device_number;
    bool m_alpaca_focuser_device_number_isSet;

    qint32 alpaca_focus_position;
    bool m_alpaca_focus_position_isSet;

    qint32 alpaca_focus_step_size;
    bool m_alpaca_focus_step_size_isSet;

    qint32 alpaca_filter_wheel_enabled;
    bool m_alpaca_filter_wheel_enabled_isSet;

    QString* alpaca_filter_wheel_host;
    bool m_alpaca_filter_wheel_host_isSet;

    qint32 alpaca_filter_wheel_port;
    bool m_alpaca_filter_wheel_port_isSet;

    qint32 alpaca_filter_wheel_device_number;
    bool m_alpaca_filter_wheel_device_number_isSet;

    qint32 alpaca_filter_wheel_position;
    bool m_alpaca_filter_wheel_position_isSet;

    qint32 alpaca_bin_x;
    bool m_alpaca_bin_x_isSet;

    qint32 alpaca_bin_y;
    bool m_alpaca_bin_y_isSet;

    qint32 alpaca_num_x;
    bool m_alpaca_num_x_isSet;

    qint32 alpaca_num_y;
    bool m_alpaca_num_y_isSet;

    qint32 alpaca_start_x;
    bool m_alpaca_start_x_isSet;

    qint32 alpaca_start_y;
    bool m_alpaca_start_y_isSet;

    qint32 alpaca_gain;
    bool m_alpaca_gain_isSet;

    qint32 alpaca_offset;
    bool m_alpaca_offset_isSet;

    qint32 alpaca_readout_mode;
    bool m_alpaca_readout_mode_isSet;

    qint32 save_image;
    bool m_save_image_isSet;

    QString* image_file_name;
    bool m_image_file_name_isSet;

    qint32 save_video;
    bool m_save_video_isSet;

    QString* video_file_camera_path;
    bool m_video_file_camera_path_isSet;

    QString* video_file_name;
    bool m_video_file_name_isSet;

    qint32 video_hw_acceleration;
    bool m_video_hw_acceleration_isSet;

    qint32 post_process_white_balance_mode;
    bool m_post_process_white_balance_mode_isSet;

    double post_process_white_balance_red_gain;
    bool m_post_process_white_balance_red_gain_isSet;

    double post_process_white_balance_green_gain;
    bool m_post_process_white_balance_green_gain_isSet;

    double post_process_white_balance_blue_gain;
    bool m_post_process_white_balance_blue_gain_isSet;

    double saturation;
    bool m_saturation_isSet;

    double gamma;
    bool m_gamma_isSet;

    double brightness;
    bool m_brightness_isSet;

    double contrast;
    bool m_contrast_isSet;

    qint32 gaussian_blur;
    bool m_gaussian_blur_isSet;

    qint32 median_blur;
    bool m_median_blur_isSet;

    double sharpen;
    bool m_sharpen_isSet;

    double sobel_edge;
    bool m_sobel_edge_isSet;

    qint32 flip_x;
    bool m_flip_x_isSet;

    qint32 flip_y;
    bool m_flip_y_isSet;

    qint32 invert_colors;
    bool m_invert_colors_isSet;

    qint32 overlay_date_time;
    bool m_overlay_date_time_isSet;

    qint32 date_time_color;
    bool m_date_time_color_isSet;

    QString* date_time_format;
    bool m_date_time_format_isSet;

    qint32 date_time_pos_x;
    bool m_date_time_pos_x_isSet;

    qint32 date_time_pos_y;
    bool m_date_time_pos_y_isSet;

    qint32 overlay_text;
    bool m_overlay_text_isSet;

    QString* overlay_text_string;
    bool m_overlay_text_string_isSet;

    qint32 overlay_text_color;
    bool m_overlay_text_color_isSet;

    QString* overlay_text_font_family;
    bool m_overlay_text_font_family_isSet;

    double overlay_text_font_scale;
    bool m_overlay_text_font_scale_isSet;

    qint32 overlay_text_pos_x;
    bool m_overlay_text_pos_x_isSet;

    qint32 overlay_text_pos_y;
    bool m_overlay_text_pos_y_isSet;

    qint32 diff_mask;
    bool m_diff_mask_isSet;

    qint32 diff_threshold;
    bool m_diff_threshold_isSet;

    qint32 dilation_size;
    bool m_dilation_size_isSet;

    qint32 diff_mask_history_frames;
    bool m_diff_mask_history_frames_isSet;

    qint32 diff_mask_close_size;
    bool m_diff_mask_close_size_isSet;

    qint32 detection_roi_x;
    bool m_detection_roi_x_isSet;

    qint32 detection_roi_y;
    bool m_detection_roi_y_isSet;

    qint32 detection_roi_width;
    bool m_detection_roi_width_isSet;

    qint32 detection_roi_height;
    bool m_detection_roi_height_isSet;

    qint32 motion_detect;
    bool m_motion_detect_isSet;

    qint32 motion_history;
    bool m_motion_history_isSet;

    double motion_var_threshold;
    bool m_motion_var_threshold_isSet;

    qint32 motion_detect_shadows;
    bool m_motion_detect_shadows_isSet;

    qint32 motion_open_size;
    bool m_motion_open_size_isSet;

    qint32 motion_close_size;
    bool m_motion_close_size_isSet;

    qint32 motion_persistence_frames;
    bool m_motion_persistence_frames_isSet;

    qint32 motion_box_color;
    bool m_motion_box_color_isSet;

    qint32 min_contour_area;
    bool m_min_contour_area_isSet;

    qint32 video_post_process;
    bool m_video_post_process_isSet;

    qint32 overlay_spectrum;
    bool m_overlay_spectrum_isSet;

    QString* spectrum_device;
    bool m_spectrum_device_isSet;

    qint32 spectrum_offset_x;
    bool m_spectrum_offset_x_isSet;

    qint32 spectrum_offset_y;
    bool m_spectrum_offset_y_isSet;

    double spectrum_scale;
    bool m_spectrum_scale_isSet;

    qint32 yolo_enabled;
    bool m_yolo_enabled_isSet;

    QString* yolo_model_path;
    bool m_yolo_model_path_isSet;

    QString* yolo_labels_path;
    bool m_yolo_labels_path_isSet;

    double yolo_conf_threshold;
    bool m_yolo_conf_threshold_isSet;

    double yolo_nms_threshold;
    bool m_yolo_nms_threshold_isSet;

    qint32 yolo_box_color;
    bool m_yolo_box_color_isSet;

    double yolo_disappear_debounce;
    bool m_yolo_disappear_debounce_isSet;

    qint32 yolo_dnn_target;
    bool m_yolo_dnn_target_isSet;

    QList<SWGCameraObjectClassSettings*>* object_device_settings;
    bool m_object_device_settings_isSet;

    qint32 audio_mute;
    bool m_audio_mute_isSet;

    QString* audio_device_name;
    bool m_audio_device_name_isSet;

    qint32 white_balance_mode;
    bool m_white_balance_mode_isSet;

    double exposure_compensation;
    bool m_exposure_compensation_isSet;

    qint32 focus_mode;
    bool m_focus_mode_isSet;

    double focus_distance;
    bool m_focus_distance_isSet;

    double zoom_factor;
    bool m_zoom_factor_isSet;

    qint32 use_reverse_api;
    bool m_use_reverse_api_isSet;

    QString* reverse_api_address;
    bool m_reverse_api_address_isSet;

    qint32 reverse_api_port;
    bool m_reverse_api_port_isSet;

    qint32 reverse_api_feature_set_index;
    bool m_reverse_api_feature_set_index_isSet;

    qint32 reverse_api_feature_index;
    bool m_reverse_api_feature_index_isSet;

    SWGRollupState* rollup_state;
    bool m_rollup_state_isSet;

    qint32 workspace_index;
    bool m_workspace_index_isSet;

};

}

#endif /* SWGCameraSettings_H_ */
