/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGCameraSettings.h
 *
 * Camera feature settings
 */

#ifndef SWGCameraSettings_H_
#define SWGCameraSettings_H_

#include <QJsonObject>


#include "SWGCameraRect.h"
#include "SWGRollupState.h"
#include <QList>
#include <QString>

#include "SWGObject.h"
#include "export.h"

namespace SWGSDRangel {

class SWG_API SWGCameraSettings: public SWGObject {
public:
    SWGCameraSettings();
    SWGCameraSettings(QString* json);
    virtual ~SWGCameraSettings();
    void init();
    void cleanup();

    virtual QString asJson () override;
    virtual QJsonObject* asJsonObject() override;
    virtual void fromJsonObject(QJsonObject &json) override;
    virtual SWGCameraSettings* fromJson(QString &jsonString) override;

    QString* getTitle();
    void setTitle(QString* title);

    qint32 getRgbColor();
    void setRgbColor(qint32 rgb_color);

    QString* getCameraProtocol();
    void setCameraProtocol(QString* camera_protocol);

    QString* getCameraId();
    void setCameraId(QString* camera_id);

    QString* getCameraDescription();
    void setCameraDescription(QString* camera_description);

    qint32 getResolutionWidth();
    void setResolutionWidth(qint32 resolution_width);

    qint32 getResolutionHeight();
    void setResolutionHeight(qint32 resolution_height);

    qint32 getFramesPerSecond();
    void setFramesPerSecond(qint32 frames_per_second);

    qint32 getCaptureMode();
    void setCaptureMode(qint32 capture_mode);

    double getCaptureInterval();
    void setCaptureInterval(double capture_interval);

    qint32 getCaptureIntervalUnits();
    void setCaptureIntervalUnits(qint32 capture_interval_units);

    double getExposureTimeMs();
    void setExposureTimeMs(double exposure_time_ms);

    qint32 getIsoSensitivity();
    void setIsoSensitivity(qint32 iso_sensitivity);

    qint32 getAlpacaDiscoveryEnabled();
    void setAlpacaDiscoveryEnabled(qint32 alpaca_discovery_enabled);

    qint32 getAlpacaApiLogEnabled();
    void setAlpacaApiLogEnabled(qint32 alpaca_api_log_enabled);

    QString* getAlpacaHost();
    void setAlpacaHost(QString* alpaca_host);

    qint32 getAlpacaPort();
    void setAlpacaPort(qint32 alpaca_port);

    qint32 getAlpacaFocuserEnabled();
    void setAlpacaFocuserEnabled(qint32 alpaca_focuser_enabled);

    QString* getAlpacaFocuserHost();
    void setAlpacaFocuserHost(QString* alpaca_focuser_host);

    qint32 getAlpacaFocuserPort();
    void setAlpacaFocuserPort(qint32 alpaca_focuser_port);

    qint32 getAlpacaFocuserDeviceNumber();
    void setAlpacaFocuserDeviceNumber(qint32 alpaca_focuser_device_number);

    qint32 getAlpacaFocusPosition();
    void setAlpacaFocusPosition(qint32 alpaca_focus_position);

    qint32 getAlpacaFocusStepSize();
    void setAlpacaFocusStepSize(qint32 alpaca_focus_step_size);

    qint32 getAlpacaFilterWheelEnabled();
    void setAlpacaFilterWheelEnabled(qint32 alpaca_filter_wheel_enabled);

    QString* getAlpacaFilterWheelHost();
    void setAlpacaFilterWheelHost(QString* alpaca_filter_wheel_host);

    qint32 getAlpacaFilterWheelPort();
    void setAlpacaFilterWheelPort(qint32 alpaca_filter_wheel_port);

    qint32 getAlpacaFilterWheelDeviceNumber();
    void setAlpacaFilterWheelDeviceNumber(qint32 alpaca_filter_wheel_device_number);

    qint32 getAlpacaFilterWheelPosition();
    void setAlpacaFilterWheelPosition(qint32 alpaca_filter_wheel_position);

    qint32 getCameraBinX();
    void setCameraBinX(qint32 camera_bin_x);

    qint32 getCameraBinY();
    void setCameraBinY(qint32 camera_bin_y);

    qint32 getCameraNumX();
    void setCameraNumX(qint32 camera_num_x);

    qint32 getCameraNumY();
    void setCameraNumY(qint32 camera_num_y);

    qint32 getCameraStartX();
    void setCameraStartX(qint32 camera_start_x);

    qint32 getCameraStartY();
    void setCameraStartY(qint32 camera_start_y);

    qint32 getCameraGain();
    void setCameraGain(qint32 camera_gain);

    qint32 getCameraOffset();
    void setCameraOffset(qint32 camera_offset);

    qint32 getCameraReadoutMode();
    void setCameraReadoutMode(qint32 camera_readout_mode);

    qint32 getAsiCoolerOn();
    void setAsiCoolerOn(qint32 asi_cooler_on);

    qint32 getAsiTargetTemp();
    void setAsiTargetTemp(qint32 asi_target_temp);

    qint32 getAsiUsbBandwidth();
    void setAsiUsbBandwidth(qint32 asi_usb_bandwidth);

    qint32 getAsiHighSpeedMode();
    void setAsiHighSpeedMode(qint32 asi_high_speed_mode);

    qint32 getAsiAutoExposureGain();
    void setAsiAutoExposureGain(qint32 asi_auto_exposure_gain);

    qint32 getAutoExposureGainEnabled();
    void setAutoExposureGainEnabled(qint32 auto_exposure_gain_enabled);

    qint32 getAutoExposureGainMode();
    void setAutoExposureGainMode(qint32 auto_exposure_gain_mode);

    double getAutoExposureTargetPercentile();
    void setAutoExposureTargetPercentile(double auto_exposure_target_percentile);

    double getAutoExposureTargetBrightness();
    void setAutoExposureTargetBrightness(double auto_exposure_target_brightness);

    double getAutoExposureMaxChangePercent();
    void setAutoExposureMaxChangePercent(double auto_exposure_max_change_percent);

    double getAutoExposureMinMs();
    void setAutoExposureMinMs(double auto_exposure_min_ms);

    double getAutoExposureMaxMs();
    void setAutoExposureMaxMs(double auto_exposure_max_ms);

    qint32 getAutoExposureMinGain();
    void setAutoExposureMinGain(qint32 auto_exposure_min_gain);

    qint32 getAutoExposureMaxGain();
    void setAutoExposureMaxGain(qint32 auto_exposure_max_gain);

    qint32 getAsiColorImageType();
    void setAsiColorImageType(qint32 asi_color_image_type);

    qint32 getSaveImage();
    void setSaveImage(qint32 save_image);

    QString* getImageFileName();
    void setImageFileName(QString* image_file_name);

    qint32 getSaveVideo();
    void setSaveVideo(qint32 save_video);

    QString* getVideoFileCameraPath();
    void setVideoFileCameraPath(QString* video_file_camera_path);

    QString* getStreamUrl();
    void setStreamUrl(QString* stream_url);

    QList<QString*>* getStreamUrlHistory();
    void setStreamUrlHistory(QList<QString*>* stream_url_history);

    double getStreamBufferingSeconds();
    void setStreamBufferingSeconds(double stream_buffering_seconds);

    QList<QString*>* getImageFileCameraPaths();
    void setImageFileCameraPaths(QList<QString*>* image_file_camera_paths);

    QString* getVideoFileName();
    void setVideoFileName(QString* video_file_name);

    QString* getRecordingOutputDirectoryUri();
    void setRecordingOutputDirectoryUri(QString* recording_output_directory_uri);

    qint32 getVideoCodec();
    void setVideoCodec(qint32 video_codec);

    qint32 getVideoRecordBitrateKbps();
    void setVideoRecordBitrateKbps(qint32 video_record_bitrate_kbps);

    qint32 getRecordRawFits();
    void setRecordRawFits(qint32 record_raw_fits);

    qint32 getRecordCalibratedMedia();
    void setRecordCalibratedMedia(qint32 record_calibrated_media);

    qint32 getRecordFilteredMedia();
    void setRecordFilteredMedia(qint32 record_filtered_media);

    qint32 getRecordPostProcessedMedia();
    void setRecordPostProcessedMedia(qint32 record_post_processed_media);

    qint32 getKeogramEnabled();
    void setKeogramEnabled(qint32 keogram_enabled);

    QString* getKeogramFileName();
    void setKeogramFileName(QString* keogram_file_name);

    qint32 getKeogramDirection();
    void setKeogramDirection(qint32 keogram_direction);

    qint32 getKeogramDayMode();
    void setKeogramDayMode(qint32 keogram_day_mode);

    qint32 getKeogramSamplePeriodMinutes();
    void setKeogramSamplePeriodMinutes(qint32 keogram_sample_period_minutes);

    qint32 getKeogramShowPreview();
    void setKeogramShowPreview(qint32 keogram_show_preview);

    qint32 getYoutubeStreamEnabled();
    void setYoutubeStreamEnabled(qint32 youtube_stream_enabled);

    QString* getYoutubeStreamUrl();
    void setYoutubeStreamUrl(QString* youtube_stream_url);

    QString* getYoutubeStreamKey();
    void setYoutubeStreamKey(QString* youtube_stream_key);

    qint32 getYoutubeStreamPostProcessed();
    void setYoutubeStreamPostProcessed(qint32 youtube_stream_post_processed);

    qint32 getYoutubeStreamBitrateKbps();
    void setYoutubeStreamBitrateKbps(qint32 youtube_stream_bitrate_kbps);

    qint32 getYoutubeStreamFps();
    void setYoutubeStreamFps(qint32 youtube_stream_fps);

    qint32 getYoutubeStreamWidth();
    void setYoutubeStreamWidth(qint32 youtube_stream_width);

    qint32 getYoutubeStreamHeight();
    void setYoutubeStreamHeight(qint32 youtube_stream_height);

    qint32 getVideoHwAcceleration();
    void setVideoHwAcceleration(qint32 video_hw_acceleration);

    qint32 getVideoLoop();
    void setVideoLoop(qint32 video_loop);

    double getVideoPlaybackRate();
    void setVideoPlaybackRate(double video_playback_rate);

    qint32 getVideoPlaybackAudioOffsetMs();
    void setVideoPlaybackAudioOffsetMs(qint32 video_playback_audio_offset_ms);

    qint32 getVideoPreRecordBufferSeconds();
    void setVideoPreRecordBufferSeconds(qint32 video_pre_record_buffer_seconds);

    qint32 getImageRecordLimit();
    void setImageRecordLimit(qint32 image_record_limit);

    qint32 getVideoRecordLimitSeconds();
    void setVideoRecordLimitSeconds(qint32 video_record_limit_seconds);

    qint32 getStackEnabled();
    void setStackEnabled(qint32 stack_enabled);

    qint32 getStackFrameCount();
    void setStackFrameCount(qint32 stack_frame_count);

    qint32 getStackMethod();
    void setStackMethod(qint32 stack_method);

    qint32 getStackHdrAlgorithm();
    void setStackHdrAlgorithm(qint32 stack_hdr_algorithm);

    qint32 getStackHdrExposureCount();
    void setStackHdrExposureCount(qint32 stack_hdr_exposure_count);

    QList<double>* getStackHdrExposureTimesMs();
    void setStackHdrExposureTimesMs(QList<double>* stack_hdr_exposure_times_ms);

    qint32 getStackAlignmentMethod();
    void setStackAlignmentMethod(qint32 stack_alignment_method);

    qint32 getStackDisplayMode();
    void setStackDisplayMode(qint32 stack_display_mode);

    qint32 getStackDisplayFrameIndex();
    void setStackDisplayFrameIndex(qint32 stack_display_frame_index);

    qint32 getStackRejectBadFrames();
    void setStackRejectBadFrames(qint32 stack_reject_bad_frames);

    qint32 getScaleEnabled();
    void setScaleEnabled(qint32 scale_enabled);

    qint32 getScaleWidth();
    void setScaleWidth(qint32 scale_width);

    qint32 getScaleHeight();
    void setScaleHeight(qint32 scale_height);

    qint32 getScaleKeepAspectRatio();
    void setScaleKeepAspectRatio(qint32 scale_keep_aspect_ratio);

    qint32 getScaleJustification();
    void setScaleJustification(qint32 scale_justification);

    QString* getStackDarkFileName();
    void setStackDarkFileName(QString* stack_dark_file_name);

    QString* getStackFlatFileName();
    void setStackFlatFileName(QString* stack_flat_file_name);

    QString* getStackBiasFileName();
    void setStackBiasFileName(QString* stack_bias_file_name);

    float getLatitude();
    void setLatitude(float latitude);

    float getLongitude();
    void setLongitude(float longitude);

    float getAltitude();
    void setAltitude(float altitude);

    qint32 getPositionSync();
    void setPositionSync(qint32 position_sync);

    QString* getOwmApiKey();
    void setOwmApiKey(QString* owm_api_key);

    float getAzimuth();
    void setAzimuth(float azimuth);

    float getElevation();
    void setElevation(float elevation);

    float getRoll();
    void setRoll(float roll);

    QString* getRotator();
    void setRotator(QString* rotator);

    float getFov();
    void setFov(float fov);

    qint32 getFovMode();
    void setFovMode(qint32 fov_mode);

    double getFovSensorWidthMm();
    void setFovSensorWidthMm(double fov_sensor_width_mm);

    double getFovSensorHeightMm();
    void setFovSensorHeightMm(double fov_sensor_height_mm);

    double getFovFocalLengthMm();
    void setFovFocalLengthMm(double fov_focal_length_mm);

    qint32 getLensProjection();
    void setLensProjection(qint32 lens_projection);

    double getLensCenterOffsetX();
    void setLensCenterOffsetX(double lens_center_offset_x);

    double getLensCenterOffsetY();
    void setLensCenterOffsetY(double lens_center_offset_y);

    double getLensDistortionK1();
    void setLensDistortionK1(double lens_distortion_k1);

    qint32 getLensMirror();
    void setLensMirror(qint32 lens_mirror);

    qint32 getPlaybackProjectionEnabled();
    void setPlaybackProjectionEnabled(qint32 playback_projection_enabled);

    qint32 getPlaybackProjectionX();
    void setPlaybackProjectionX(qint32 playback_projection_x);

    qint32 getPlaybackProjectionY();
    void setPlaybackProjectionY(qint32 playback_projection_y);

    qint32 getPlaybackProjectionWidth();
    void setPlaybackProjectionWidth(qint32 playback_projection_width);

    qint32 getPlaybackProjectionHeight();
    void setPlaybackProjectionHeight(qint32 playback_projection_height);

    qint32 getPostProcessWhiteBalanceMode();
    void setPostProcessWhiteBalanceMode(qint32 post_process_white_balance_mode);

    double getPostProcessWhiteBalanceRedGain();
    void setPostProcessWhiteBalanceRedGain(double post_process_white_balance_red_gain);

    double getPostProcessWhiteBalanceGreenGain();
    void setPostProcessWhiteBalanceGreenGain(double post_process_white_balance_green_gain);

    double getPostProcessWhiteBalanceBlueGain();
    void setPostProcessWhiteBalanceBlueGain(double post_process_white_balance_blue_gain);

    double getPostProcessWhiteBalanceHighlightProtection();
    void setPostProcessWhiteBalanceHighlightProtection(double post_process_white_balance_highlight_protection);

    qint32 getPostProcessUseCuda();
    void setPostProcessUseCuda(qint32 post_process_use_cuda);

    qint32 getPostProcessUnwarp();
    void setPostProcessUnwarp(qint32 post_process_unwarp);

    qint32 getHistogramStretch();
    void setHistogramStretch(qint32 histogram_stretch);

    double getHistogramStretchBlackPoint();
    void setHistogramStretchBlackPoint(double histogram_stretch_black_point);

    double getHistogramStretchWhitePoint();
    void setHistogramStretchWhitePoint(double histogram_stretch_white_point);

    double getHistogramStretchGamma();
    void setHistogramStretchGamma(double histogram_stretch_gamma);

    double getHistogramStretchAsinhStrength();
    void setHistogramStretchAsinhStrength(double histogram_stretch_asinh_strength);

    double getHistogramStretchLogStrength();
    void setHistogramStretchLogStrength(double histogram_stretch_log_strength);

    qint32 getPostProcessGreyscale();
    void setPostProcessGreyscale(qint32 post_process_greyscale);

    double getSaturation();
    void setSaturation(double saturation);

    double getGamma();
    void setGamma(double gamma);

    double getBrightness();
    void setBrightness(double brightness);

    double getContrast();
    void setContrast(double contrast);

    qint32 getGaussianBlur();
    void setGaussianBlur(qint32 gaussian_blur);

    qint32 getMedianBlur();
    void setMedianBlur(qint32 median_blur);

    double getSharpen();
    void setSharpen(double sharpen);

    qint32 getEdgeDisplayMode();
    void setEdgeDisplayMode(qint32 edge_display_mode);

    double getSobelEdge();
    void setSobelEdge(double sobel_edge);

    double getCannyEdge();
    void setCannyEdge(double canny_edge);

    qint32 getFlipX();
    void setFlipX(qint32 flip_x);

    qint32 getFlipY();
    void setFlipY(qint32 flip_y);

    qint32 getImageRotation();
    void setImageRotation(qint32 image_rotation);

    qint32 getInvertColors();
    void setInvertColors(qint32 invert_colors);

    qint32 getOverlayDateTime();
    void setOverlayDateTime(qint32 overlay_date_time);

    qint32 getDateTimeColor();
    void setDateTimeColor(qint32 date_time_color);

    QString* getDateTimeFormat();
    void setDateTimeFormat(QString* date_time_format);

    qint32 getDateTimeUtc();
    void setDateTimeUtc(qint32 date_time_utc);

    qint32 getDateTimePosX();
    void setDateTimePosX(qint32 date_time_pos_x);

    qint32 getDateTimePosY();
    void setDateTimePosY(qint32 date_time_pos_y);

    qint32 getOverlayText();
    void setOverlayText(qint32 overlay_text);

    qint32 getEquatorialGrid();
    void setEquatorialGrid(qint32 equatorial_grid);

    qint32 getEquatorialGridColor();
    void setEquatorialGridColor(qint32 equatorial_grid_color);

    qint32 getAltAzGrid();
    void setAltAzGrid(qint32 alt_az_grid);

    qint32 getAltAzGridColor();
    void setAltAzGridColor(qint32 alt_az_grid_color);

    qint32 getConstellation();
    void setConstellation(qint32 constellation);

    qint32 getConstellationColor();
    void setConstellationColor(qint32 constellation_color);

    qint32 getConstellationOverlay();
    void setConstellationOverlay(qint32 constellation_overlay);

    qint32 getMessier();
    void setMessier(qint32 messier);

    qint32 getMessierColor();
    void setMessierColor(qint32 messier_color);

    double getMessierMaxMagnitude();
    void setMessierMaxMagnitude(double messier_max_magnitude);

    qint32 getMessierDetect();
    void setMessierDetect(qint32 messier_detect);

    qint32 getTrackObjects();
    void setTrackObjects(qint32 track_objects);

    double getTrackObjectMinElevation();
    void setTrackObjectMinElevation(double track_object_min_elevation);

    double getTrackObjectMaxRangeKm();
    void setTrackObjectMaxRangeKm(double track_object_max_range_km);

    qint32 getTrackObjectLabelDisplay();
    void setTrackObjectLabelDisplay(qint32 track_object_label_display);

    double getTrackObjectLabelDetectionRadius();
    void setTrackObjectLabelDetectionRadius(double track_object_label_detection_radius);

    qint32 getTrackObjectColor();
    void setTrackObjectColor(qint32 track_object_color);

    double getTrackObjectFontScale();
    void setTrackObjectFontScale(double track_object_font_scale);

    qint32 getTrackObjectTrails();
    void setTrackObjectTrails(qint32 track_object_trails);

    qint32 getTrackObjectHeatMap();
    void setTrackObjectHeatMap(qint32 track_object_heat_map);

    qint32 getTrackObjectRange();
    void setTrackObjectRange(qint32 track_object_range);

    QString* getGridLabelFontFamily();
    void setGridLabelFontFamily(QString* grid_label_font_family);

    double getGridLabelFontScale();
    void setGridLabelFontScale(double grid_label_font_scale);

    QString* getOverlayTextString();
    void setOverlayTextString(QString* overlay_text_string);

    qint32 getOverlayTextColor();
    void setOverlayTextColor(qint32 overlay_text_color);

    QString* getOverlayTextFontFamily();
    void setOverlayTextFontFamily(QString* overlay_text_font_family);

    double getOverlayTextFontScale();
    void setOverlayTextFontScale(double overlay_text_font_scale);

    qint32 getOverlayTextPosX();
    void setOverlayTextPosX(qint32 overlay_text_pos_x);

    qint32 getOverlayTextPosY();
    void setOverlayTextPosY(qint32 overlay_text_pos_y);

    qint32 getDiffMask();
    void setDiffMask(qint32 diff_mask);

    qint32 getDiffThreshold();
    void setDiffThreshold(qint32 diff_threshold);

    qint32 getDiffMaskOpenSize();
    void setDiffMaskOpenSize(qint32 diff_mask_open_size);

    qint32 getDilationSize();
    void setDilationSize(qint32 dilation_size);

    qint32 getDiffMaskHistoryFrames();
    void setDiffMaskHistoryFrames(qint32 diff_mask_history_frames);

    qint32 getDiffMaskCloseSize();
    void setDiffMaskCloseSize(qint32 diff_mask_close_size);

    QString* getOverlayFontFamily();
    void setOverlayFontFamily(QString* overlay_font_family);

    double getOverlayFontScale();
    void setOverlayFontScale(double overlay_font_scale);

    qint32 getDetectionRoiX();
    void setDetectionRoiX(qint32 detection_roi_x);

    qint32 getDetectionRoiY();
    void setDetectionRoiY(qint32 detection_roi_y);

    qint32 getDetectionRoiWidth();
    void setDetectionRoiWidth(qint32 detection_roi_width);

    qint32 getDetectionRoiHeight();
    void setDetectionRoiHeight(qint32 detection_roi_height);

    qint32 getShowDetectionRoi();
    void setShowDetectionRoi(qint32 show_detection_roi);

    qint32 getMotionDetect();
    void setMotionDetect(qint32 motion_detect);

    qint32 getMotionBackgroundSubtractor();
    void setMotionBackgroundSubtractor(qint32 motion_background_subtractor);

    qint32 getMotionMaskView();
    void setMotionMaskView(qint32 motion_mask_view);

    qint32 getMotionHistory();
    void setMotionHistory(qint32 motion_history);

    double getMotionVarThreshold();
    void setMotionVarThreshold(double motion_var_threshold);

    double getMotionLearningRate();
    void setMotionLearningRate(double motion_learning_rate);

    qint32 getMotionConfirmFrames();
    void setMotionConfirmFrames(qint32 motion_confirm_frames);

    double getMotionDownscale();
    void setMotionDownscale(double motion_downscale);

    qint32 getMotionDetectShadows();
    void setMotionDetectShadows(qint32 motion_detect_shadows);

    qint32 getMotionOpenSize();
    void setMotionOpenSize(qint32 motion_open_size);

    qint32 getMotionCloseSize();
    void setMotionCloseSize(qint32 motion_close_size);

    qint32 getMotionPersistenceFrames();
    void setMotionPersistenceFrames(qint32 motion_persistence_frames);

    qint32 getMotionBoxColor();
    void setMotionBoxColor(qint32 motion_box_color);

    qint32 getMinContourArea();
    void setMinContourArea(qint32 min_contour_area);

    qint32 getShowMotionExclusionRects();
    void setShowMotionExclusionRects(qint32 show_motion_exclusion_rects);

    QList<SWGCameraRect*>* getMotionExclusionRects();
    void setMotionExclusionRects(QList<SWGCameraRect*>* motion_exclusion_rects);

    qint32 getCloudDetect();
    void setCloudDetect(qint32 cloud_detect);

    qint32 getCloudMode();
    void setCloudMode(qint32 cloud_mode);

    qint32 getCloudDebugView();
    void setCloudDebugView(qint32 cloud_debug_view);

    qint32 getCloudColor();
    void setCloudColor(qint32 cloud_color);

    qint32 getCloudShowOverlay();
    void setCloudShowOverlay(qint32 cloud_show_overlay);

    double getCloudDayThreshold();
    void setCloudDayThreshold(double cloud_day_threshold);

    qint32 getCloudTextureThreshold();
    void setCloudTextureThreshold(qint32 cloud_texture_threshold);

    qint32 getCloudNightThreshold();
    void setCloudNightThreshold(qint32 cloud_night_threshold);

    qint32 getCloudBackgroundBlur();
    void setCloudBackgroundBlur(qint32 cloud_background_blur);

    qint32 getCloudOpenSize();
    void setCloudOpenSize(qint32 cloud_open_size);

    qint32 getCloudCloseSize();
    void setCloudCloseSize(qint32 cloud_close_size);

    double getCloudDownscale();
    void setCloudDownscale(double cloud_downscale);

    qint32 getCloudUpdateIntervalFrames();
    void setCloudUpdateIntervalFrames(qint32 cloud_update_interval_frames);

    qint32 getCloudFilterStars();
    void setCloudFilterStars(qint32 cloud_filter_stars);

    qint32 getCloudFilterMotion();
    void setCloudFilterMotion(qint32 cloud_filter_motion);

    double getCloudMotionOverlapThreshold();
    void setCloudMotionOverlapThreshold(double cloud_motion_overlap_threshold);

    double getCloudEventThreshold();
    void setCloudEventThreshold(double cloud_event_threshold);

    double getCloudEdgeMarginPercent();
    void setCloudEdgeMarginPercent(double cloud_edge_margin_percent);

    double getCloudDayRelativeMargin();
    void setCloudDayRelativeMargin(double cloud_day_relative_margin);

    double getCloudMinElevation();
    void setCloudMinElevation(double cloud_min_elevation);

    qint32 getCloudMaskSunMoon();
    void setCloudMaskSunMoon(qint32 cloud_mask_sun_moon);

    qint32 getCloudStarSense();
    void setCloudStarSense(qint32 cloud_star_sense);

    double getCloudStarSenseMagnitude();
    void setCloudStarSenseMagnitude(double cloud_star_sense_magnitude);

    qint32 getCloudUseReference();
    void setCloudUseReference(qint32 cloud_use_reference);

    qint32 getCloudAutoReference();
    void setCloudAutoReference(qint32 cloud_auto_reference);

    qint32 getCloudUseDetectionRoi();
    void setCloudUseDetectionRoi(qint32 cloud_use_detection_roi);

    double getCloudSunMoonRadiusDeg();
    void setCloudSunMoonRadiusDeg(double cloud_sun_moon_radius_deg);

    qint32 getStarDetect();
    void setStarDetect(qint32 star_detect);

    qint32 getStarThreshold();
    void setStarThreshold(qint32 star_threshold);

    qint32 getStarBackgroundBlur();
    void setStarBackgroundBlur(qint32 star_background_blur);

    qint32 getStarMinArea();
    void setStarMinArea(qint32 star_min_area);

    qint32 getStarMaxArea();
    void setStarMaxArea(qint32 star_max_area);

    double getStarMaxAspectRatio();
    void setStarMaxAspectRatio(double star_max_aspect_ratio);

    qint32 getStarDebugView();
    void setStarDebugView(qint32 star_debug_view);

    qint32 getStarColor();
    void setStarColor(qint32 star_color);

    qint32 getPlateSolve();
    void setPlateSolve(qint32 plate_solve);

    double getPlateSolveMaxMagnitude();
    void setPlateSolveMaxMagnitude(double plate_solve_max_magnitude);

    qint32 getPlateSolveMinMatches();
    void setPlateSolveMinMatches(qint32 plate_solve_min_matches);

    double getPlateSolveMatchRadius();
    void setPlateSolveMatchRadius(double plate_solve_match_radius);

    double getPlateSolveFinalMatchRadius();
    void setPlateSolveFinalMatchRadius(double plate_solve_final_match_radius);

    double getPlateSolveSearchRadius();
    void setPlateSolveSearchRadius(double plate_solve_search_radius);

    double getPlateSolveFovTolerance();
    void setPlateSolveFovTolerance(double plate_solve_fov_tolerance);

    qint32 getPlateSolveStartMode();
    void setPlateSolveStartMode(qint32 plate_solve_start_mode);

    qint32 getPlateSolveLabelMode();
    void setPlateSolveLabelMode(qint32 plate_solve_label_mode);

    qint32 getPlateSolveUseCaptureDateTime();
    void setPlateSolveUseCaptureDateTime(qint32 plate_solve_use_capture_date_time);

    QString* getPlateSolveDateTime();
    void setPlateSolveDateTime(QString* plate_solve_date_time);

    qint32 getPlateSolveDateTimeUtc();
    void setPlateSolveDateTimeUtc(qint32 plate_solve_date_time_utc);

    qint32 getPlateSolveUseDownloadedCatalog();
    void setPlateSolveUseDownloadedCatalog(qint32 plate_solve_use_downloaded_catalog);

    qint32 getPlateSolveCatalogSource();
    void setPlateSolveCatalogSource(qint32 plate_solve_catalog_source);

    qint32 getPlateSolveApplyMode();
    void setPlateSolveApplyMode(qint32 plate_solve_apply_mode);

    qint32 getStarCatalogDiskCacheSizeGb();
    void setStarCatalogDiskCacheSizeGb(qint32 star_catalog_disk_cache_size_gb);

    qint32 getOverlaySpectrum();
    void setOverlaySpectrum(qint32 overlay_spectrum);

    QString* getSpectrumDevice();
    void setSpectrumDevice(QString* spectrum_device);

    qint32 getSpectrumOffsetX();
    void setSpectrumOffsetX(qint32 spectrum_offset_x);

    qint32 getSpectrumOffsetY();
    void setSpectrumOffsetY(qint32 spectrum_offset_y);

    double getSpectrumScale();
    void setSpectrumScale(double spectrum_scale);

    qint32 getYoloEnabled();
    void setYoloEnabled(qint32 yolo_enabled);

    QString* getYoloModelPath();
    void setYoloModelPath(QString* yolo_model_path);

    QString* getYoloTileModelPath();
    void setYoloTileModelPath(QString* yolo_tile_model_path);

    QString* getYoloLabelsPath();
    void setYoloLabelsPath(QString* yolo_labels_path);

    double getYoloConfThreshold();
    void setYoloConfThreshold(double yolo_conf_threshold);

    double getYoloNmsThreshold();
    void setYoloNmsThreshold(double yolo_nms_threshold);

    double getYoloDisappearDebounce();
    void setYoloDisappearDebounce(double yolo_disappear_debounce);

    qint32 getYoloBoxColor();
    void setYoloBoxColor(qint32 yolo_box_color);

    qint32 getYoloTileLargeImages();
    void setYoloTileLargeImages(qint32 yolo_tile_large_images);

    qint32 getYoloTileOverlapPercent();
    void setYoloTileOverlapPercent(qint32 yolo_tile_overlap_percent);

    QList<QString*>* getYoloIgnoredClassNames();
    void setYoloIgnoredClassNames(QList<QString*>* yolo_ignored_class_names);

    qint32 getYoloDnnTarget();
    void setYoloDnnTarget(qint32 yolo_dnn_target);

    qint32 getAudioMute();
    void setAudioMute(qint32 audio_mute);

    qint32 getAudioPreviewVolume();
    void setAudioPreviewVolume(qint32 audio_preview_volume);

    QString* getAudioDeviceName();
    void setAudioDeviceName(QString* audio_device_name);

    qint32 getWhiteBalanceMode();
    void setWhiteBalanceMode(qint32 white_balance_mode);

    double getExposureCompensation();
    void setExposureCompensation(double exposure_compensation);

    qint32 getFocusMode();
    void setFocusMode(qint32 focus_mode);

    double getFocusDistance();
    void setFocusDistance(double focus_distance);

    double getZoomFactor();
    void setZoomFactor(double zoom_factor);

    qint32 getThermalDecoder();
    void setThermalDecoder(qint32 thermal_decoder);

    qint32 getThermalPalette();
    void setThermalPalette(qint32 thermal_palette);

    qint32 getThermalUnits();
    void setThermalUnits(qint32 thermal_units);

    qint32 getThermalAutoRange();
    void setThermalAutoRange(qint32 thermal_auto_range);

    double getThermalMinimumC();
    void setThermalMinimumC(double thermal_minimum_c);

    double getThermalMaximumC();
    void setThermalMaximumC(double thermal_maximum_c);

    double getThermalAutoLowPercentile();
    void setThermalAutoLowPercentile(double thermal_auto_low_percentile);

    double getThermalAutoHighPercentile();
    void setThermalAutoHighPercentile(double thermal_auto_high_percentile);

    double getThermalAutoRangeSmoothing();
    void setThermalAutoRangeSmoothing(double thermal_auto_range_smoothing);

    qint32 getThermalMarkerEnabled();
    void setThermalMarkerEnabled(qint32 thermal_marker_enabled);

    double getThermalMarkerX();
    void setThermalMarkerX(double thermal_marker_x);

    double getThermalMarkerY();
    void setThermalMarkerY(double thermal_marker_y);

    qint32 getThermalShowMinMax();
    void setThermalShowMinMax(qint32 thermal_show_min_max);

    qint32 getThermalChartEnabled();
    void setThermalChartEnabled(qint32 thermal_chart_enabled);

    qint32 getThermalChartHistorySeconds();
    void setThermalChartHistorySeconds(qint32 thermal_chart_history_seconds);

    qint32 getThermalChartSampleIntervalMs();
    void setThermalChartSampleIntervalMs(qint32 thermal_chart_sample_interval_ms);

    qint32 getUseReverseApi();
    void setUseReverseApi(qint32 use_reverse_api);

    QString* getReverseApiAddress();
    void setReverseApiAddress(QString* reverse_api_address);

    qint32 getReverseApiPort();
    void setReverseApiPort(qint32 reverse_api_port);

    qint32 getReverseApiFeatureSetIndex();
    void setReverseApiFeatureSetIndex(qint32 reverse_api_feature_set_index);

    qint32 getReverseApiFeatureIndex();
    void setReverseApiFeatureIndex(qint32 reverse_api_feature_index);

    SWGRollupState* getRollupState();
    void setRollupState(SWGRollupState* rollup_state);

    qint32 getWorkspaceIndex();
    void setWorkspaceIndex(qint32 workspace_index);


    virtual bool isSet() override;

private:
    QString* title;
    bool m_title_isSet;

    qint32 rgb_color;
    bool m_rgb_color_isSet;

    QString* camera_protocol;
    bool m_camera_protocol_isSet;

    QString* camera_id;
    bool m_camera_id_isSet;

    QString* camera_description;
    bool m_camera_description_isSet;

    qint32 resolution_width;
    bool m_resolution_width_isSet;

    qint32 resolution_height;
    bool m_resolution_height_isSet;

    qint32 frames_per_second;
    bool m_frames_per_second_isSet;

    qint32 capture_mode;
    bool m_capture_mode_isSet;

    double capture_interval;
    bool m_capture_interval_isSet;

    qint32 capture_interval_units;
    bool m_capture_interval_units_isSet;

    double exposure_time_ms;
    bool m_exposure_time_ms_isSet;

    qint32 iso_sensitivity;
    bool m_iso_sensitivity_isSet;

    qint32 alpaca_discovery_enabled;
    bool m_alpaca_discovery_enabled_isSet;

    qint32 alpaca_api_log_enabled;
    bool m_alpaca_api_log_enabled_isSet;

    QString* alpaca_host;
    bool m_alpaca_host_isSet;

    qint32 alpaca_port;
    bool m_alpaca_port_isSet;

    qint32 alpaca_focuser_enabled;
    bool m_alpaca_focuser_enabled_isSet;

    QString* alpaca_focuser_host;
    bool m_alpaca_focuser_host_isSet;

    qint32 alpaca_focuser_port;
    bool m_alpaca_focuser_port_isSet;

    qint32 alpaca_focuser_device_number;
    bool m_alpaca_focuser_device_number_isSet;

    qint32 alpaca_focus_position;
    bool m_alpaca_focus_position_isSet;

    qint32 alpaca_focus_step_size;
    bool m_alpaca_focus_step_size_isSet;

    qint32 alpaca_filter_wheel_enabled;
    bool m_alpaca_filter_wheel_enabled_isSet;

    QString* alpaca_filter_wheel_host;
    bool m_alpaca_filter_wheel_host_isSet;

    qint32 alpaca_filter_wheel_port;
    bool m_alpaca_filter_wheel_port_isSet;

    qint32 alpaca_filter_wheel_device_number;
    bool m_alpaca_filter_wheel_device_number_isSet;

    qint32 alpaca_filter_wheel_position;
    bool m_alpaca_filter_wheel_position_isSet;

    qint32 camera_bin_x;
    bool m_camera_bin_x_isSet;

    qint32 camera_bin_y;
    bool m_camera_bin_y_isSet;

    qint32 camera_num_x;
    bool m_camera_num_x_isSet;

    qint32 camera_num_y;
    bool m_camera_num_y_isSet;

    qint32 camera_start_x;
    bool m_camera_start_x_isSet;

    qint32 camera_start_y;
    bool m_camera_start_y_isSet;

    qint32 camera_gain;
    bool m_camera_gain_isSet;

    qint32 camera_offset;
    bool m_camera_offset_isSet;

    qint32 camera_readout_mode;
    bool m_camera_readout_mode_isSet;

    qint32 asi_cooler_on;
    bool m_asi_cooler_on_isSet;

    qint32 asi_target_temp;
    bool m_asi_target_temp_isSet;

    qint32 asi_usb_bandwidth;
    bool m_asi_usb_bandwidth_isSet;

    qint32 asi_high_speed_mode;
    bool m_asi_high_speed_mode_isSet;

    qint32 asi_auto_exposure_gain;
    bool m_asi_auto_exposure_gain_isSet;

    qint32 auto_exposure_gain_enabled;
    bool m_auto_exposure_gain_enabled_isSet;

    qint32 auto_exposure_gain_mode;
    bool m_auto_exposure_gain_mode_isSet;

    double auto_exposure_target_percentile;
    bool m_auto_exposure_target_percentile_isSet;

    double auto_exposure_target_brightness;
    bool m_auto_exposure_target_brightness_isSet;

    double auto_exposure_max_change_percent;
    bool m_auto_exposure_max_change_percent_isSet;

    double auto_exposure_min_ms;
    bool m_auto_exposure_min_ms_isSet;

    double auto_exposure_max_ms;
    bool m_auto_exposure_max_ms_isSet;

    qint32 auto_exposure_min_gain;
    bool m_auto_exposure_min_gain_isSet;

    qint32 auto_exposure_max_gain;
    bool m_auto_exposure_max_gain_isSet;

    qint32 asi_color_image_type;
    bool m_asi_color_image_type_isSet;

    qint32 save_image;
    bool m_save_image_isSet;

    QString* image_file_name;
    bool m_image_file_name_isSet;

    qint32 save_video;
    bool m_save_video_isSet;

    QString* video_file_camera_path;
    bool m_video_file_camera_path_isSet;

    QString* stream_url;
    bool m_stream_url_isSet;

    QList<QString*>* stream_url_history;
    bool m_stream_url_history_isSet;

    double stream_buffering_seconds;
    bool m_stream_buffering_seconds_isSet;

    QList<QString*>* image_file_camera_paths;
    bool m_image_file_camera_paths_isSet;

    QString* video_file_name;
    bool m_video_file_name_isSet;

    QString* recording_output_directory_uri;
    bool m_recording_output_directory_uri_isSet;

    qint32 video_codec;
    bool m_video_codec_isSet;

    qint32 video_record_bitrate_kbps;
    bool m_video_record_bitrate_kbps_isSet;

    qint32 record_raw_fits;
    bool m_record_raw_fits_isSet;

    qint32 record_calibrated_media;
    bool m_record_calibrated_media_isSet;

    qint32 record_filtered_media;
    bool m_record_filtered_media_isSet;

    qint32 record_post_processed_media;
    bool m_record_post_processed_media_isSet;

    qint32 keogram_enabled;
    bool m_keogram_enabled_isSet;

    QString* keogram_file_name;
    bool m_keogram_file_name_isSet;

    qint32 keogram_direction;
    bool m_keogram_direction_isSet;

    qint32 keogram_day_mode;
    bool m_keogram_day_mode_isSet;

    qint32 keogram_sample_period_minutes;
    bool m_keogram_sample_period_minutes_isSet;

    qint32 keogram_show_preview;
    bool m_keogram_show_preview_isSet;

    qint32 youtube_stream_enabled;
    bool m_youtube_stream_enabled_isSet;

    QString* youtube_stream_url;
    bool m_youtube_stream_url_isSet;

    QString* youtube_stream_key;
    bool m_youtube_stream_key_isSet;

    qint32 youtube_stream_post_processed;
    bool m_youtube_stream_post_processed_isSet;

    qint32 youtube_stream_bitrate_kbps;
    bool m_youtube_stream_bitrate_kbps_isSet;

    qint32 youtube_stream_fps;
    bool m_youtube_stream_fps_isSet;

    qint32 youtube_stream_width;
    bool m_youtube_stream_width_isSet;

    qint32 youtube_stream_height;
    bool m_youtube_stream_height_isSet;

    qint32 video_hw_acceleration;
    bool m_video_hw_acceleration_isSet;

    qint32 video_loop;
    bool m_video_loop_isSet;

    double video_playback_rate;
    bool m_video_playback_rate_isSet;

    qint32 video_playback_audio_offset_ms;
    bool m_video_playback_audio_offset_ms_isSet;

    qint32 video_pre_record_buffer_seconds;
    bool m_video_pre_record_buffer_seconds_isSet;

    qint32 image_record_limit;
    bool m_image_record_limit_isSet;

    qint32 video_record_limit_seconds;
    bool m_video_record_limit_seconds_isSet;

    qint32 stack_enabled;
    bool m_stack_enabled_isSet;

    qint32 stack_frame_count;
    bool m_stack_frame_count_isSet;

    qint32 stack_method;
    bool m_stack_method_isSet;

    qint32 stack_hdr_algorithm;
    bool m_stack_hdr_algorithm_isSet;

    qint32 stack_hdr_exposure_count;
    bool m_stack_hdr_exposure_count_isSet;

    QList<double>* stack_hdr_exposure_times_ms;
    bool m_stack_hdr_exposure_times_ms_isSet;

    qint32 stack_alignment_method;
    bool m_stack_alignment_method_isSet;

    qint32 stack_display_mode;
    bool m_stack_display_mode_isSet;

    qint32 stack_display_frame_index;
    bool m_stack_display_frame_index_isSet;

    qint32 stack_reject_bad_frames;
    bool m_stack_reject_bad_frames_isSet;

    qint32 scale_enabled;
    bool m_scale_enabled_isSet;

    qint32 scale_width;
    bool m_scale_width_isSet;

    qint32 scale_height;
    bool m_scale_height_isSet;

    qint32 scale_keep_aspect_ratio;
    bool m_scale_keep_aspect_ratio_isSet;

    qint32 scale_justification;
    bool m_scale_justification_isSet;

    QString* stack_dark_file_name;
    bool m_stack_dark_file_name_isSet;

    QString* stack_flat_file_name;
    bool m_stack_flat_file_name_isSet;

    QString* stack_bias_file_name;
    bool m_stack_bias_file_name_isSet;

    float latitude;
    bool m_latitude_isSet;

    float longitude;
    bool m_longitude_isSet;

    float altitude;
    bool m_altitude_isSet;

    qint32 position_sync;
    bool m_position_sync_isSet;

    QString* owm_api_key;
    bool m_owm_api_key_isSet;

    float azimuth;
    bool m_azimuth_isSet;

    float elevation;
    bool m_elevation_isSet;

    float roll;
    bool m_roll_isSet;

    QString* rotator;
    bool m_rotator_isSet;

    float fov;
    bool m_fov_isSet;

    qint32 fov_mode;
    bool m_fov_mode_isSet;

    double fov_sensor_width_mm;
    bool m_fov_sensor_width_mm_isSet;

    double fov_sensor_height_mm;
    bool m_fov_sensor_height_mm_isSet;

    double fov_focal_length_mm;
    bool m_fov_focal_length_mm_isSet;

    qint32 lens_projection;
    bool m_lens_projection_isSet;

    double lens_center_offset_x;
    bool m_lens_center_offset_x_isSet;

    double lens_center_offset_y;
    bool m_lens_center_offset_y_isSet;

    double lens_distortion_k1;
    bool m_lens_distortion_k1_isSet;

    qint32 lens_mirror;
    bool m_lens_mirror_isSet;

    qint32 playback_projection_enabled;
    bool m_playback_projection_enabled_isSet;

    qint32 playback_projection_x;
    bool m_playback_projection_x_isSet;

    qint32 playback_projection_y;
    bool m_playback_projection_y_isSet;

    qint32 playback_projection_width;
    bool m_playback_projection_width_isSet;

    qint32 playback_projection_height;
    bool m_playback_projection_height_isSet;

    qint32 post_process_white_balance_mode;
    bool m_post_process_white_balance_mode_isSet;

    double post_process_white_balance_red_gain;
    bool m_post_process_white_balance_red_gain_isSet;

    double post_process_white_balance_green_gain;
    bool m_post_process_white_balance_green_gain_isSet;

    double post_process_white_balance_blue_gain;
    bool m_post_process_white_balance_blue_gain_isSet;

    double post_process_white_balance_highlight_protection;
    bool m_post_process_white_balance_highlight_protection_isSet;

    qint32 post_process_use_cuda;
    bool m_post_process_use_cuda_isSet;

    qint32 post_process_unwarp;
    bool m_post_process_unwarp_isSet;

    qint32 histogram_stretch;
    bool m_histogram_stretch_isSet;

    double histogram_stretch_black_point;
    bool m_histogram_stretch_black_point_isSet;

    double histogram_stretch_white_point;
    bool m_histogram_stretch_white_point_isSet;

    double histogram_stretch_gamma;
    bool m_histogram_stretch_gamma_isSet;

    double histogram_stretch_asinh_strength;
    bool m_histogram_stretch_asinh_strength_isSet;

    double histogram_stretch_log_strength;
    bool m_histogram_stretch_log_strength_isSet;

    qint32 post_process_greyscale;
    bool m_post_process_greyscale_isSet;

    double saturation;
    bool m_saturation_isSet;

    double gamma;
    bool m_gamma_isSet;

    double brightness;
    bool m_brightness_isSet;

    double contrast;
    bool m_contrast_isSet;

    qint32 gaussian_blur;
    bool m_gaussian_blur_isSet;

    qint32 median_blur;
    bool m_median_blur_isSet;

    double sharpen;
    bool m_sharpen_isSet;

    qint32 edge_display_mode;
    bool m_edge_display_mode_isSet;

    double sobel_edge;
    bool m_sobel_edge_isSet;

    double canny_edge;
    bool m_canny_edge_isSet;

    qint32 flip_x;
    bool m_flip_x_isSet;

    qint32 flip_y;
    bool m_flip_y_isSet;

    qint32 image_rotation;
    bool m_image_rotation_isSet;

    qint32 invert_colors;
    bool m_invert_colors_isSet;

    qint32 overlay_date_time;
    bool m_overlay_date_time_isSet;

    qint32 date_time_color;
    bool m_date_time_color_isSet;

    QString* date_time_format;
    bool m_date_time_format_isSet;

    qint32 date_time_utc;
    bool m_date_time_utc_isSet;

    qint32 date_time_pos_x;
    bool m_date_time_pos_x_isSet;

    qint32 date_time_pos_y;
    bool m_date_time_pos_y_isSet;

    qint32 overlay_text;
    bool m_overlay_text_isSet;

    qint32 equatorial_grid;
    bool m_equatorial_grid_isSet;

    qint32 equatorial_grid_color;
    bool m_equatorial_grid_color_isSet;

    qint32 alt_az_grid;
    bool m_alt_az_grid_isSet;

    qint32 alt_az_grid_color;
    bool m_alt_az_grid_color_isSet;

    qint32 constellation;
    bool m_constellation_isSet;

    qint32 constellation_color;
    bool m_constellation_color_isSet;

    qint32 constellation_overlay;
    bool m_constellation_overlay_isSet;

    qint32 messier;
    bool m_messier_isSet;

    qint32 messier_color;
    bool m_messier_color_isSet;

    double messier_max_magnitude;
    bool m_messier_max_magnitude_isSet;

    qint32 messier_detect;
    bool m_messier_detect_isSet;

    qint32 track_objects;
    bool m_track_objects_isSet;

    double track_object_min_elevation;
    bool m_track_object_min_elevation_isSet;

    double track_object_max_range_km;
    bool m_track_object_max_range_km_isSet;

    qint32 track_object_label_display;
    bool m_track_object_label_display_isSet;

    double track_object_label_detection_radius;
    bool m_track_object_label_detection_radius_isSet;

    qint32 track_object_color;
    bool m_track_object_color_isSet;

    double track_object_font_scale;
    bool m_track_object_font_scale_isSet;

    qint32 track_object_trails;
    bool m_track_object_trails_isSet;

    qint32 track_object_heat_map;
    bool m_track_object_heat_map_isSet;

    qint32 track_object_range;
    bool m_track_object_range_isSet;

    QString* grid_label_font_family;
    bool m_grid_label_font_family_isSet;

    double grid_label_font_scale;
    bool m_grid_label_font_scale_isSet;

    QString* overlay_text_string;
    bool m_overlay_text_string_isSet;

    qint32 overlay_text_color;
    bool m_overlay_text_color_isSet;

    QString* overlay_text_font_family;
    bool m_overlay_text_font_family_isSet;

    double overlay_text_font_scale;
    bool m_overlay_text_font_scale_isSet;

    qint32 overlay_text_pos_x;
    bool m_overlay_text_pos_x_isSet;

    qint32 overlay_text_pos_y;
    bool m_overlay_text_pos_y_isSet;

    qint32 diff_mask;
    bool m_diff_mask_isSet;

    qint32 diff_threshold;
    bool m_diff_threshold_isSet;

    qint32 diff_mask_open_size;
    bool m_diff_mask_open_size_isSet;

    qint32 dilation_size;
    bool m_dilation_size_isSet;

    qint32 diff_mask_history_frames;
    bool m_diff_mask_history_frames_isSet;

    qint32 diff_mask_close_size;
    bool m_diff_mask_close_size_isSet;

    QString* overlay_font_family;
    bool m_overlay_font_family_isSet;

    double overlay_font_scale;
    bool m_overlay_font_scale_isSet;

    qint32 detection_roi_x;
    bool m_detection_roi_x_isSet;

    qint32 detection_roi_y;
    bool m_detection_roi_y_isSet;

    qint32 detection_roi_width;
    bool m_detection_roi_width_isSet;

    qint32 detection_roi_height;
    bool m_detection_roi_height_isSet;

    qint32 show_detection_roi;
    bool m_show_detection_roi_isSet;

    qint32 motion_detect;
    bool m_motion_detect_isSet;

    qint32 motion_background_subtractor;
    bool m_motion_background_subtractor_isSet;

    qint32 motion_mask_view;
    bool m_motion_mask_view_isSet;

    qint32 motion_history;
    bool m_motion_history_isSet;

    double motion_var_threshold;
    bool m_motion_var_threshold_isSet;

    double motion_learning_rate;
    bool m_motion_learning_rate_isSet;

    qint32 motion_confirm_frames;
    bool m_motion_confirm_frames_isSet;

    double motion_downscale;
    bool m_motion_downscale_isSet;

    qint32 motion_detect_shadows;
    bool m_motion_detect_shadows_isSet;

    qint32 motion_open_size;
    bool m_motion_open_size_isSet;

    qint32 motion_close_size;
    bool m_motion_close_size_isSet;

    qint32 motion_persistence_frames;
    bool m_motion_persistence_frames_isSet;

    qint32 motion_box_color;
    bool m_motion_box_color_isSet;

    qint32 min_contour_area;
    bool m_min_contour_area_isSet;

    qint32 show_motion_exclusion_rects;
    bool m_show_motion_exclusion_rects_isSet;

    QList<SWGCameraRect*>* motion_exclusion_rects;
    bool m_motion_exclusion_rects_isSet;

    qint32 cloud_detect;
    bool m_cloud_detect_isSet;

    qint32 cloud_mode;
    bool m_cloud_mode_isSet;

    qint32 cloud_debug_view;
    bool m_cloud_debug_view_isSet;

    qint32 cloud_color;
    bool m_cloud_color_isSet;

    qint32 cloud_show_overlay;
    bool m_cloud_show_overlay_isSet;

    double cloud_day_threshold;
    bool m_cloud_day_threshold_isSet;

    qint32 cloud_texture_threshold;
    bool m_cloud_texture_threshold_isSet;

    qint32 cloud_night_threshold;
    bool m_cloud_night_threshold_isSet;

    qint32 cloud_background_blur;
    bool m_cloud_background_blur_isSet;

    qint32 cloud_open_size;
    bool m_cloud_open_size_isSet;

    qint32 cloud_close_size;
    bool m_cloud_close_size_isSet;

    double cloud_downscale;
    bool m_cloud_downscale_isSet;

    qint32 cloud_update_interval_frames;
    bool m_cloud_update_interval_frames_isSet;

    qint32 cloud_filter_stars;
    bool m_cloud_filter_stars_isSet;

    qint32 cloud_filter_motion;
    bool m_cloud_filter_motion_isSet;

    double cloud_motion_overlap_threshold;
    bool m_cloud_motion_overlap_threshold_isSet;

    double cloud_event_threshold;
    bool m_cloud_event_threshold_isSet;

    double cloud_edge_margin_percent;
    bool m_cloud_edge_margin_percent_isSet;

    double cloud_day_relative_margin;
    bool m_cloud_day_relative_margin_isSet;

    double cloud_min_elevation;
    bool m_cloud_min_elevation_isSet;

    qint32 cloud_mask_sun_moon;
    bool m_cloud_mask_sun_moon_isSet;

    qint32 cloud_star_sense;
    bool m_cloud_star_sense_isSet;

    double cloud_star_sense_magnitude;
    bool m_cloud_star_sense_magnitude_isSet;

    qint32 cloud_use_reference;
    bool m_cloud_use_reference_isSet;

    qint32 cloud_auto_reference;
    bool m_cloud_auto_reference_isSet;

    qint32 cloud_use_detection_roi;
    bool m_cloud_use_detection_roi_isSet;

    double cloud_sun_moon_radius_deg;
    bool m_cloud_sun_moon_radius_deg_isSet;

    qint32 star_detect;
    bool m_star_detect_isSet;

    qint32 star_threshold;
    bool m_star_threshold_isSet;

    qint32 star_background_blur;
    bool m_star_background_blur_isSet;

    qint32 star_min_area;
    bool m_star_min_area_isSet;

    qint32 star_max_area;
    bool m_star_max_area_isSet;

    double star_max_aspect_ratio;
    bool m_star_max_aspect_ratio_isSet;

    qint32 star_debug_view;
    bool m_star_debug_view_isSet;

    qint32 star_color;
    bool m_star_color_isSet;

    qint32 plate_solve;
    bool m_plate_solve_isSet;

    double plate_solve_max_magnitude;
    bool m_plate_solve_max_magnitude_isSet;

    qint32 plate_solve_min_matches;
    bool m_plate_solve_min_matches_isSet;

    double plate_solve_match_radius;
    bool m_plate_solve_match_radius_isSet;

    double plate_solve_final_match_radius;
    bool m_plate_solve_final_match_radius_isSet;

    double plate_solve_search_radius;
    bool m_plate_solve_search_radius_isSet;

    double plate_solve_fov_tolerance;
    bool m_plate_solve_fov_tolerance_isSet;

    qint32 plate_solve_start_mode;
    bool m_plate_solve_start_mode_isSet;

    qint32 plate_solve_label_mode;
    bool m_plate_solve_label_mode_isSet;

    qint32 plate_solve_use_capture_date_time;
    bool m_plate_solve_use_capture_date_time_isSet;

    QString* plate_solve_date_time;
    bool m_plate_solve_date_time_isSet;

    qint32 plate_solve_date_time_utc;
    bool m_plate_solve_date_time_utc_isSet;

    qint32 plate_solve_use_downloaded_catalog;
    bool m_plate_solve_use_downloaded_catalog_isSet;

    qint32 plate_solve_catalog_source;
    bool m_plate_solve_catalog_source_isSet;

    qint32 plate_solve_apply_mode;
    bool m_plate_solve_apply_mode_isSet;

    qint32 star_catalog_disk_cache_size_gb;
    bool m_star_catalog_disk_cache_size_gb_isSet;

    qint32 overlay_spectrum;
    bool m_overlay_spectrum_isSet;

    QString* spectrum_device;
    bool m_spectrum_device_isSet;

    qint32 spectrum_offset_x;
    bool m_spectrum_offset_x_isSet;

    qint32 spectrum_offset_y;
    bool m_spectrum_offset_y_isSet;

    double spectrum_scale;
    bool m_spectrum_scale_isSet;

    qint32 yolo_enabled;
    bool m_yolo_enabled_isSet;

    QString* yolo_model_path;
    bool m_yolo_model_path_isSet;

    QString* yolo_tile_model_path;
    bool m_yolo_tile_model_path_isSet;

    QString* yolo_labels_path;
    bool m_yolo_labels_path_isSet;

    double yolo_conf_threshold;
    bool m_yolo_conf_threshold_isSet;

    double yolo_nms_threshold;
    bool m_yolo_nms_threshold_isSet;

    double yolo_disappear_debounce;
    bool m_yolo_disappear_debounce_isSet;

    qint32 yolo_box_color;
    bool m_yolo_box_color_isSet;

    qint32 yolo_tile_large_images;
    bool m_yolo_tile_large_images_isSet;

    qint32 yolo_tile_overlap_percent;
    bool m_yolo_tile_overlap_percent_isSet;

    QList<QString*>* yolo_ignored_class_names;
    bool m_yolo_ignored_class_names_isSet;

    qint32 yolo_dnn_target;
    bool m_yolo_dnn_target_isSet;

    qint32 audio_mute;
    bool m_audio_mute_isSet;

    qint32 audio_preview_volume;
    bool m_audio_preview_volume_isSet;

    QString* audio_device_name;
    bool m_audio_device_name_isSet;

    qint32 white_balance_mode;
    bool m_white_balance_mode_isSet;

    double exposure_compensation;
    bool m_exposure_compensation_isSet;

    qint32 focus_mode;
    bool m_focus_mode_isSet;

    double focus_distance;
    bool m_focus_distance_isSet;

    double zoom_factor;
    bool m_zoom_factor_isSet;

    qint32 thermal_decoder;
    bool m_thermal_decoder_isSet;

    qint32 thermal_palette;
    bool m_thermal_palette_isSet;

    qint32 thermal_units;
    bool m_thermal_units_isSet;

    qint32 thermal_auto_range;
    bool m_thermal_auto_range_isSet;

    double thermal_minimum_c;
    bool m_thermal_minimum_c_isSet;

    double thermal_maximum_c;
    bool m_thermal_maximum_c_isSet;

    double thermal_auto_low_percentile;
    bool m_thermal_auto_low_percentile_isSet;

    double thermal_auto_high_percentile;
    bool m_thermal_auto_high_percentile_isSet;

    double thermal_auto_range_smoothing;
    bool m_thermal_auto_range_smoothing_isSet;

    qint32 thermal_marker_enabled;
    bool m_thermal_marker_enabled_isSet;

    double thermal_marker_x;
    bool m_thermal_marker_x_isSet;

    double thermal_marker_y;
    bool m_thermal_marker_y_isSet;

    qint32 thermal_show_min_max;
    bool m_thermal_show_min_max_isSet;

    qint32 thermal_chart_enabled;
    bool m_thermal_chart_enabled_isSet;

    qint32 thermal_chart_history_seconds;
    bool m_thermal_chart_history_seconds_isSet;

    qint32 thermal_chart_sample_interval_ms;
    bool m_thermal_chart_sample_interval_ms_isSet;

    qint32 use_reverse_api;
    bool m_use_reverse_api_isSet;

    QString* reverse_api_address;
    bool m_reverse_api_address_isSet;

    qint32 reverse_api_port;
    bool m_reverse_api_port_isSet;

    qint32 reverse_api_feature_set_index;
    bool m_reverse_api_feature_set_index_isSet;

    qint32 reverse_api_feature_index;
    bool m_reverse_api_feature_index_isSet;

    SWGRollupState* rollup_state;
    bool m_rollup_state_isSet;

    qint32 workspace_index;
    bool m_workspace_index_isSet;

};

}

#endif /* SWGCameraSettings_H_ */
