/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGCameraRect.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace SWGSDRangel {

SWGCameraRect::SWGCameraRect(QString* json) {
    init();
    this->fromJson(*json);
}

SWGCameraRect::SWGCameraRect() {
    x = 0;
    m_x_isSet = false;
    y = 0;
    m_y_isSet = false;
    width = 0;
    m_width_isSet = false;
    height = 0;
    m_height_isSet = false;
}

SWGCameraRect::~SWGCameraRect() {
    this->cleanup();
}

void
SWGCameraRect::init() {
    x = 0;
    m_x_isSet = false;
    y = 0;
    m_y_isSet = false;
    width = 0;
    m_width_isSet = false;
    height = 0;
    m_height_isSet = false;
}

void
SWGCameraRect::cleanup() {




}

SWGCameraRect*
SWGCameraRect::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGCameraRect::fromJsonObject(QJsonObject &pJson) {
    ::SWGSDRangel::setValue(&x, pJson["x"], "qint32", "");
    
    ::SWGSDRangel::setValue(&y, pJson["y"], "qint32", "");
    
    ::SWGSDRangel::setValue(&width, pJson["width"], "qint32", "");
    
    ::SWGSDRangel::setValue(&height, pJson["height"], "qint32", "");
    
}

QString
SWGCameraRect::asJson ()
{
    QJsonObject* obj = this->asJsonObject();

    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    delete obj;
    return QString(bytes);
}

QJsonObject*
SWGCameraRect::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    if(m_x_isSet){
        obj->insert("x", QJsonValue(x));
    }
    if(m_y_isSet){
        obj->insert("y", QJsonValue(y));
    }
    if(m_width_isSet){
        obj->insert("width", QJsonValue(width));
    }
    if(m_height_isSet){
        obj->insert("height", QJsonValue(height));
    }

    return obj;
}

qint32
SWGCameraRect::getX() {
    return x;
}
void
SWGCameraRect::setX(qint32 x) {
    this->x = x;
    this->m_x_isSet = true;
}

qint32
SWGCameraRect::getY() {
    return y;
}
void
SWGCameraRect::setY(qint32 y) {
    this->y = y;
    this->m_y_isSet = true;
}

qint32
SWGCameraRect::getWidth() {
    return width;
}
void
SWGCameraRect::setWidth(qint32 width) {
    this->width = width;
    this->m_width_isSet = true;
}

qint32
SWGCameraRect::getHeight() {
    return height;
}
void
SWGCameraRect::setHeight(qint32 height) {
    this->height = height;
    this->m_height_isSet = true;
}


bool
SWGCameraRect::isSet(){
    bool isObjectUpdated = false;
    do{
        if(m_x_isSet){
            isObjectUpdated = true; break;
        }
        if(m_y_isSet){
            isObjectUpdated = true; break;
        }
        if(m_width_isSet){
            isObjectUpdated = true; break;
        }
        if(m_height_isSet){
            isObjectUpdated = true; break;
        }
    }while(false);
    return isObjectUpdated;
}
}

