/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGMapFlightPlan.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace SWGSDRangel {

SWGMapFlightPlan::SWGMapFlightPlan(QString* json) {
    init();
    this->fromJson(*json);
}

SWGMapFlightPlan::SWGMapFlightPlan() {
    departure = nullptr;
    m_departure_isSet = false;
    arrival = nullptr;
    m_arrival_isSet = false;
    arrival_runway = nullptr;
    m_arrival_runway_isSet = false;
    approach = nullptr;
    m_approach_isSet = false;
    active_waypoint = 0;
    m_active_waypoint_isSet = false;
    waypoints = nullptr;
    m_waypoints_isSet = false;
}

SWGMapFlightPlan::~SWGMapFlightPlan() {
    this->cleanup();
}

void
SWGMapFlightPlan::init() {
    departure = new QString("");
    m_departure_isSet = false;
    arrival = new QString("");
    m_arrival_isSet = false;
    arrival_runway = new QString("");
    m_arrival_runway_isSet = false;
    approach = new QString("");
    m_approach_isSet = false;
    active_waypoint = 0;
    m_active_waypoint_isSet = false;
    waypoints = new QList<SWGMapRouteWaypoint*>();
    m_waypoints_isSet = false;
}

void
SWGMapFlightPlan::cleanup() {
    if(departure != nullptr) { 
        delete departure;
    }
    if(arrival != nullptr) { 
        delete arrival;
    }
    if(arrival_runway != nullptr) { 
        delete arrival_runway;
    }
    if(approach != nullptr) { 
        delete approach;
    }

    if(waypoints != nullptr) { 
        auto arr = waypoints;
        for(auto o: *arr) { 
            delete o;
        }
        delete waypoints;
    }
}

SWGMapFlightPlan*
SWGMapFlightPlan::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGMapFlightPlan::fromJsonObject(QJsonObject &pJson) {
    ::SWGSDRangel::setValue(&departure, pJson["departure"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&arrival, pJson["arrival"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&arrival_runway, pJson["arrivalRunway"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&approach, pJson["approach"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&active_waypoint, pJson["activeWaypoint"], "qint32", "");
    
    
    ::SWGSDRangel::setValue(&waypoints, pJson["waypoints"], "QList", "SWGMapRouteWaypoint");
}

QString
SWGMapFlightPlan::asJson ()
{
    QJsonObject* obj = this->asJsonObject();

    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    delete obj;
    return QString(bytes);
}

QJsonObject*
SWGMapFlightPlan::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    if(departure != nullptr && *departure != QString("")){
        toJsonValue(QString("departure"), departure, obj, QString("QString"));
    }
    if(arrival != nullptr && *arrival != QString("")){
        toJsonValue(QString("arrival"), arrival, obj, QString("QString"));
    }
    if(arrival_runway != nullptr && *arrival_runway != QString("")){
        toJsonValue(QString("arrivalRunway"), arrival_runway, obj, QString("QString"));
    }
    if(approach != nullptr && *approach != QString("")){
        toJsonValue(QString("approach"), approach, obj, QString("QString"));
    }
    if(m_active_waypoint_isSet){
        obj->insert("activeWaypoint", QJsonValue(active_waypoint));
    }
    if(waypoints && waypoints->size() > 0){
        toJsonArray((QList<void*>*)waypoints, obj, "waypoints", "SWGMapRouteWaypoint");
    }

    return obj;
}

QString*
SWGMapFlightPlan::getDeparture() {
    return departure;
}
void
SWGMapFlightPlan::setDeparture(QString* departure) {
    this->departure = departure;
    this->m_departure_isSet = true;
}

QString*
SWGMapFlightPlan::getArrival() {
    return arrival;
}
void
SWGMapFlightPlan::setArrival(QString* arrival) {
    this->arrival = arrival;
    this->m_arrival_isSet = true;
}

QString*
SWGMapFlightPlan::getArrivalRunway() {
    return arrival_runway;
}
void
SWGMapFlightPlan::setArrivalRunway(QString* arrival_runway) {
    this->arrival_runway = arrival_runway;
    this->m_arrival_runway_isSet = true;
}

QString*
SWGMapFlightPlan::getApproach() {
    return approach;
}
void
SWGMapFlightPlan::setApproach(QString* approach) {
    this->approach = approach;
    this->m_approach_isSet = true;
}

qint32
SWGMapFlightPlan::getActiveWaypoint() {
    return active_waypoint;
}
void
SWGMapFlightPlan::setActiveWaypoint(qint32 active_waypoint) {
    this->active_waypoint = active_waypoint;
    this->m_active_waypoint_isSet = true;
}

QList<SWGMapRouteWaypoint*>*
SWGMapFlightPlan::getWaypoints() {
    return waypoints;
}
void
SWGMapFlightPlan::setWaypoints(QList<SWGMapRouteWaypoint*>* waypoints) {
    this->waypoints = waypoints;
    this->m_waypoints_isSet = true;
}


bool
SWGMapFlightPlan::isSet(){
    bool isObjectUpdated = false;
    do{
        if(departure && *departure != QString("")){
            isObjectUpdated = true; break;
        }
        if(arrival && *arrival != QString("")){
            isObjectUpdated = true; break;
        }
        if(arrival_runway && *arrival_runway != QString("")){
            isObjectUpdated = true; break;
        }
        if(approach && *approach != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_active_waypoint_isSet){
            isObjectUpdated = true; break;
        }
        if(waypoints && (waypoints->size() > 0)){
            isObjectUpdated = true; break;
        }
    }while(false);
    return isObjectUpdated;
}
}

