/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGMapMesh.h
 *
 * A generic indexed triangle mesh. Vertices use WGS84 coordinates and triangle indices use counter-clockwise outward winding.
 */

#ifndef SWGMapMesh_H_
#define SWGMapMesh_H_

#include <QJsonObject>


#include "SWGMapCoordinate.h"
#include <QList>

#include "SWGObject.h"
#include "export.h"

namespace SWGSDRangel {

class SWG_API SWGMapMesh: public SWGObject {
public:
    SWGMapMesh();
    SWGMapMesh(QString* json);
    virtual ~SWGMapMesh();
    void init();
    void cleanup();

    virtual QString asJson () override;
    virtual QJsonObject* asJsonObject() override;
    virtual void fromJsonObject(QJsonObject &json) override;
    virtual SWGMapMesh* fromJson(QString &jsonString) override;

    QList<SWGMapCoordinate*>* getVertices();
    void setVertices(QList<SWGMapCoordinate*>* vertices);

    QList<qint32>* getTriangleIndices();
    void setTriangleIndices(QList<qint32>* triangle_indices);


    virtual bool isSet() override;

private:
    QList<SWGMapCoordinate*>* vertices;
    bool m_vertices_isSet;

    QList<qint32>* triangle_indices;
    bool m_triangle_indices_isSet;

};

}

#endif /* SWGMapMesh_H_ */
