/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGMeteorSettings.h
 *
 * Meteor detector channel settings
 */

#ifndef SWGMeteorSettings_H_
#define SWGMeteorSettings_H_

#include <QJsonObject>


#include "SWGChannelMarker.h"
#include "SWGGLSpectrum.h"
#include "SWGRollupState.h"
#include <QString>

#include "SWGObject.h"
#include "export.h"

namespace SWGSDRangel {

class SWG_API SWGMeteorSettings: public SWGObject {
public:
    SWGMeteorSettings();
    SWGMeteorSettings(QString* json);
    virtual ~SWGMeteorSettings();
    void init();
    void cleanup();

    virtual QString asJson () override;
    virtual QJsonObject* asJsonObject() override;
    virtual void fromJsonObject(QJsonObject &json) override;
    virtual SWGMeteorSettings* fromJson(QString &jsonString) override;

    qint64 getInputFrequencyOffset();
    void setInputFrequencyOffset(qint64 input_frequency_offset);

    qint32 getFrequencyMode();
    void setFrequencyMode(qint32 frequency_mode);

    qint64 getFrequency();
    void setFrequency(qint64 frequency);

    qint32 getChannelSampleRate();
    void setChannelSampleRate(qint32 channel_sample_rate);

    float getBlobSensitivity();
    void setBlobSensitivity(float blob_sensitivity);

    qint32 getMaxDurationMs();
    void setMaxDurationMs(qint32 max_duration_ms);

    qint32 getDetectionsTableColumnHidden();
    void setDetectionsTableColumnHidden(qint32 detections_table_column_hidden);

    qint32 getDetectionBoxPaddingPixels();
    void setDetectionBoxPaddingPixels(qint32 detection_box_padding_pixels);

    qint32 getDetectionLabelMode();
    void setDetectionLabelMode(qint32 detection_label_mode);

    double getTransmitterLatitude();
    void setTransmitterLatitude(double transmitter_latitude);

    double getTransmitterLongitude();
    void setTransmitterLongitude(double transmitter_longitude);

    float getTransmitterAzimuth();
    void setTransmitterAzimuth(float transmitter_azimuth);

    float getTransmitterElevation();
    void setTransmitterElevation(float transmitter_elevation);

    float getTransmitterBeamwidth();
    void setTransmitterBeamwidth(float transmitter_beamwidth);

    float getTransmitterHpbw();
    void setTransmitterHpbw(float transmitter_hpbw);

    double getReceiverLatitude();
    void setReceiverLatitude(double receiver_latitude);

    double getReceiverLongitude();
    void setReceiverLongitude(double receiver_longitude);

    qint32 getReceiverPositionSet();
    void setReceiverPositionSet(qint32 receiver_position_set);

    float getAntennaAzimuth();
    void setAntennaAzimuth(float antenna_azimuth);

    float getAntennaElevation();
    void setAntennaElevation(float antenna_elevation);

    float getAntennaBeamwidth();
    void setAntennaBeamwidth(float antenna_beamwidth);

    QString* getRotator();
    void setRotator(QString* rotator);

    qint32 getShowAntennaPatterns();
    void setShowAntennaPatterns(qint32 show_antenna_patterns);

    float getMapMaxAltitudeKm();
    void setMapMaxAltitudeKm(float map_max_altitude_km);

    qint32 getRgbColor();
    void setRgbColor(qint32 rgb_color);

    QString* getTitle();
    void setTitle(QString* title);

    qint32 getStreamIndex();
    void setStreamIndex(qint32 stream_index);

    qint32 getWorkspaceIndex();
    void setWorkspaceIndex(qint32 workspace_index);

    qint32 getHidden();
    void setHidden(qint32 hidden);

    SWGChannelMarker* getChannelMarker();
    void setChannelMarker(SWGChannelMarker* channel_marker);

    SWGGLSpectrum* getSpectrumGui();
    void setSpectrumGui(SWGGLSpectrum* spectrum_gui);

    SWGGLSpectrum* getHeadSpectrumGui();
    void setHeadSpectrumGui(SWGGLSpectrum* head_spectrum_gui);

    SWGRollupState* getRollupState();
    void setRollupState(SWGRollupState* rollup_state);


    virtual bool isSet() override;

private:
    qint64 input_frequency_offset;
    bool m_input_frequency_offset_isSet;

    qint32 frequency_mode;
    bool m_frequency_mode_isSet;

    qint64 frequency;
    bool m_frequency_isSet;

    qint32 channel_sample_rate;
    bool m_channel_sample_rate_isSet;

    float blob_sensitivity;
    bool m_blob_sensitivity_isSet;

    qint32 max_duration_ms;
    bool m_max_duration_ms_isSet;

    qint32 detections_table_column_hidden;
    bool m_detections_table_column_hidden_isSet;

    qint32 detection_box_padding_pixels;
    bool m_detection_box_padding_pixels_isSet;

    qint32 detection_label_mode;
    bool m_detection_label_mode_isSet;

    double transmitter_latitude;
    bool m_transmitter_latitude_isSet;

    double transmitter_longitude;
    bool m_transmitter_longitude_isSet;

    float transmitter_azimuth;
    bool m_transmitter_azimuth_isSet;

    float transmitter_elevation;
    bool m_transmitter_elevation_isSet;

    float transmitter_beamwidth;
    bool m_transmitter_beamwidth_isSet;

    float transmitter_hpbw;
    bool m_transmitter_hpbw_isSet;

    double receiver_latitude;
    bool m_receiver_latitude_isSet;

    double receiver_longitude;
    bool m_receiver_longitude_isSet;

    qint32 receiver_position_set;
    bool m_receiver_position_set_isSet;

    float antenna_azimuth;
    bool m_antenna_azimuth_isSet;

    float antenna_elevation;
    bool m_antenna_elevation_isSet;

    float antenna_beamwidth;
    bool m_antenna_beamwidth_isSet;

    QString* rotator;
    bool m_rotator_isSet;

    qint32 show_antenna_patterns;
    bool m_show_antenna_patterns_isSet;

    float map_max_altitude_km;
    bool m_map_max_altitude_km_isSet;

    qint32 rgb_color;
    bool m_rgb_color_isSet;

    QString* title;
    bool m_title_isSet;

    qint32 stream_index;
    bool m_stream_index_isSet;

    qint32 workspace_index;
    bool m_workspace_index_isSet;

    qint32 hidden;
    bool m_hidden_isSet;

    SWGChannelMarker* channel_marker;
    bool m_channel_marker_isSet;

    SWGGLSpectrum* spectrum_gui;
    bool m_spectrum_gui_isSet;

    SWGGLSpectrum* head_spectrum_gui;
    bool m_head_spectrum_gui_isSet;

    SWGRollupState* rollup_state;
    bool m_rollup_state_isSet;

};

}

#endif /* SWGMeteorSettings_H_ */
