/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGMapFlightPlan.h
 *
 * Flight plan / cleared route, drawn on the Map&#39;s ND (Navigation Display)
 */

#ifndef SWGMapFlightPlan_H_
#define SWGMapFlightPlan_H_

#include <QJsonObject>


#include "SWGMapRouteWaypoint.h"
#include <QList>
#include <QString>

#include "SWGObject.h"
#include "export.h"

namespace SWGSDRangel {

class SWG_API SWGMapFlightPlan: public SWGObject {
public:
    SWGMapFlightPlan();
    SWGMapFlightPlan(QString* json);
    virtual ~SWGMapFlightPlan();
    void init();
    void cleanup();

    virtual QString asJson () override;
    virtual QJsonObject* asJsonObject() override;
    virtual void fromJsonObject(QJsonObject &json) override;
    virtual SWGMapFlightPlan* fromJson(QString &jsonString) override;

    QString* getDeparture();
    void setDeparture(QString* departure);

    QString* getArrival();
    void setArrival(QString* arrival);

    QString* getArrivalRunway();
    void setArrivalRunway(QString* arrival_runway);

    QString* getApproach();
    void setApproach(QString* approach);

    qint32 getActiveWaypoint();
    void setActiveWaypoint(qint32 active_waypoint);

    QList<SWGMapRouteWaypoint*>* getWaypoints();
    void setWaypoints(QList<SWGMapRouteWaypoint*>* waypoints);


    virtual bool isSet() override;

private:
    QString* departure;
    bool m_departure_isSet;

    QString* arrival;
    bool m_arrival_isSet;

    QString* arrival_runway;
    bool m_arrival_runway_isSet;

    QString* approach;
    bool m_approach_isSet;

    qint32 active_waypoint;
    bool m_active_waypoint_isSet;

    QList<SWGMapRouteWaypoint*>* waypoints;
    bool m_waypoints_isSet;

};

}

#endif /* SWGMapFlightPlan_H_ */
