/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGRemoteTCPInputReport.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace SWGSDRangel {

SWGRemoteTCPInputReport::SWGRemoteTCPInputReport(QString* json) {
    init();
    this->fromJson(*json);
}

SWGRemoteTCPInputReport::SWGRemoteTCPInputReport() {
    sample_rate = 0;
    m_sample_rate_isSet = false;
    latitude = 0.0f;
    m_latitude_isSet = false;
    longitude = 0.0f;
    m_longitude_isSet = false;
    altitude = 0.0f;
    m_altitude_isSet = false;
    timing_available = 0;
    m_timing_available_isSet = false;
    remote_first_sample_time_us = 0L;
    m_remote_first_sample_time_us_isSet = false;
    transport_latency_us = 0L;
    m_transport_latency_us_isSet = false;
    timing_uncertainty_us = 0L;
    m_timing_uncertainty_us_isSet = false;
}

SWGRemoteTCPInputReport::~SWGRemoteTCPInputReport() {
    this->cleanup();
}

void
SWGRemoteTCPInputReport::init() {
    sample_rate = 0;
    m_sample_rate_isSet = false;
    latitude = 0.0f;
    m_latitude_isSet = false;
    longitude = 0.0f;
    m_longitude_isSet = false;
    altitude = 0.0f;
    m_altitude_isSet = false;
    timing_available = 0;
    m_timing_available_isSet = false;
    remote_first_sample_time_us = 0L;
    m_remote_first_sample_time_us_isSet = false;
    transport_latency_us = 0L;
    m_transport_latency_us_isSet = false;
    timing_uncertainty_us = 0L;
    m_timing_uncertainty_us_isSet = false;
}

void
SWGRemoteTCPInputReport::cleanup() {








}

SWGRemoteTCPInputReport*
SWGRemoteTCPInputReport::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGRemoteTCPInputReport::fromJsonObject(QJsonObject &pJson) {
    ::SWGSDRangel::setValue(&sample_rate, pJson["sampleRate"], "qint32", "");
    
    ::SWGSDRangel::setValue(&latitude, pJson["latitude"], "float", "");
    
    ::SWGSDRangel::setValue(&longitude, pJson["longitude"], "float", "");
    
    ::SWGSDRangel::setValue(&altitude, pJson["altitude"], "float", "");
    
    ::SWGSDRangel::setValue(&timing_available, pJson["timingAvailable"], "qint32", "");
    
    ::SWGSDRangel::setValue(&remote_first_sample_time_us, pJson["remoteFirstSampleTimeUs"], "qint64", "");
    
    ::SWGSDRangel::setValue(&transport_latency_us, pJson["transportLatencyUs"], "qint64", "");
    
    ::SWGSDRangel::setValue(&timing_uncertainty_us, pJson["timingUncertaintyUs"], "qint64", "");
    
}

QString
SWGRemoteTCPInputReport::asJson ()
{
    QJsonObject* obj = this->asJsonObject();

    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    delete obj;
    return QString(bytes);
}

QJsonObject*
SWGRemoteTCPInputReport::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    if(m_sample_rate_isSet){
        obj->insert("sampleRate", QJsonValue(sample_rate));
    }
    if(m_latitude_isSet){
        obj->insert("latitude", QJsonValue(latitude));
    }
    if(m_longitude_isSet){
        obj->insert("longitude", QJsonValue(longitude));
    }
    if(m_altitude_isSet){
        obj->insert("altitude", QJsonValue(altitude));
    }
    if(m_timing_available_isSet){
        obj->insert("timingAvailable", QJsonValue(timing_available));
    }
    if(m_remote_first_sample_time_us_isSet){
        obj->insert("remoteFirstSampleTimeUs", QJsonValue(remote_first_sample_time_us));
    }
    if(m_transport_latency_us_isSet){
        obj->insert("transportLatencyUs", QJsonValue(transport_latency_us));
    }
    if(m_timing_uncertainty_us_isSet){
        obj->insert("timingUncertaintyUs", QJsonValue(timing_uncertainty_us));
    }

    return obj;
}

qint32
SWGRemoteTCPInputReport::getSampleRate() {
    return sample_rate;
}
void
SWGRemoteTCPInputReport::setSampleRate(qint32 sample_rate) {
    this->sample_rate = sample_rate;
    this->m_sample_rate_isSet = true;
}

float
SWGRemoteTCPInputReport::getLatitude() {
    return latitude;
}
void
SWGRemoteTCPInputReport::setLatitude(float latitude) {
    this->latitude = latitude;
    this->m_latitude_isSet = true;
}

float
SWGRemoteTCPInputReport::getLongitude() {
    return longitude;
}
void
SWGRemoteTCPInputReport::setLongitude(float longitude) {
    this->longitude = longitude;
    this->m_longitude_isSet = true;
}

float
SWGRemoteTCPInputReport::getAltitude() {
    return altitude;
}
void
SWGRemoteTCPInputReport::setAltitude(float altitude) {
    this->altitude = altitude;
    this->m_altitude_isSet = true;
}

qint32
SWGRemoteTCPInputReport::getTimingAvailable() {
    return timing_available;
}
void
SWGRemoteTCPInputReport::setTimingAvailable(qint32 timing_available) {
    this->timing_available = timing_available;
    this->m_timing_available_isSet = true;
}

qint64
SWGRemoteTCPInputReport::getRemoteFirstSampleTimeUs() {
    return remote_first_sample_time_us;
}
void
SWGRemoteTCPInputReport::setRemoteFirstSampleTimeUs(qint64 remote_first_sample_time_us) {
    this->remote_first_sample_time_us = remote_first_sample_time_us;
    this->m_remote_first_sample_time_us_isSet = true;
}

qint64
SWGRemoteTCPInputReport::getTransportLatencyUs() {
    return transport_latency_us;
}
void
SWGRemoteTCPInputReport::setTransportLatencyUs(qint64 transport_latency_us) {
    this->transport_latency_us = transport_latency_us;
    this->m_transport_latency_us_isSet = true;
}

qint64
SWGRemoteTCPInputReport::getTimingUncertaintyUs() {
    return timing_uncertainty_us;
}
void
SWGRemoteTCPInputReport::setTimingUncertaintyUs(qint64 timing_uncertainty_us) {
    this->timing_uncertainty_us = timing_uncertainty_us;
    this->m_timing_uncertainty_us_isSet = true;
}


bool
SWGRemoteTCPInputReport::isSet(){
    bool isObjectUpdated = false;
    do{
        if(m_sample_rate_isSet){
            isObjectUpdated = true; break;
        }
        if(m_latitude_isSet){
            isObjectUpdated = true; break;
        }
        if(m_longitude_isSet){
            isObjectUpdated = true; break;
        }
        if(m_altitude_isSet){
            isObjectUpdated = true; break;
        }
        if(m_timing_available_isSet){
            isObjectUpdated = true; break;
        }
        if(m_remote_first_sample_time_us_isSet){
            isObjectUpdated = true; break;
        }
        if(m_transport_latency_us_isSet){
            isObjectUpdated = true; break;
        }
        if(m_timing_uncertainty_us_isSet){
            isObjectUpdated = true; break;
        }
    }while(false);
    return isObjectUpdated;
}
}

