/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGSchedulerChannelAction.h
 *
 * Channel action executed by a scheduler rule
 */

#ifndef SWGSchedulerChannelAction_H_
#define SWGSchedulerChannelAction_H_

#include <QJsonObject>


#include "SWGSchedulerSettingValue.h"
#include <QList>
#include <QString>

#include "SWGObject.h"
#include "export.h"

namespace SWGSDRangel {

class SWG_API SWGSchedulerChannelAction: public SWGObject {
public:
    SWGSchedulerChannelAction();
    SWGSchedulerChannelAction(QString* json);
    virtual ~SWGSchedulerChannelAction();
    void init();
    void cleanup();

    virtual QString asJson () override;
    virtual QJsonObject* asJsonObject() override;
    virtual void fromJsonObject(QJsonObject &json) override;
    virtual SWGSchedulerChannelAction* fromJson(QString &jsonString) override;

    qint32 getDeviceSetIndex();
    void setDeviceSetIndex(qint32 device_set_index);

    QString* getDeviceSetId();
    void setDeviceSetId(QString* device_set_id);

    qint32 getChannelIndex();
    void setChannelIndex(qint32 channel_index);

    QString* getChannelId();
    void setChannelId(QString* channel_id);

    qint32 getAction();
    void setAction(qint32 action);

    QString* getText();
    void setText(QString* text);

    QString* getCallsign();
    void setCallsign(QString* callsign);

    QString* getTo();
    void setTo(QString* to);

    QString* getVia();
    void setVia(QString* via);

    QString* getData();
    void setData(QString* data);

    QList<SWGSchedulerSettingValue*>* getSettings();
    void setSettings(QList<SWGSchedulerSettingValue*>* settings);


    virtual bool isSet() override;

private:
    qint32 device_set_index;
    bool m_device_set_index_isSet;

    QString* device_set_id;
    bool m_device_set_id_isSet;

    qint32 channel_index;
    bool m_channel_index_isSet;

    QString* channel_id;
    bool m_channel_id_isSet;

    qint32 action;
    bool m_action_isSet;

    QString* text;
    bool m_text_isSet;

    QString* callsign;
    bool m_callsign_isSet;

    QString* to;
    bool m_to_isSet;

    QString* via;
    bool m_via_isSet;

    QString* data;
    bool m_data_isSet;

    QList<SWGSchedulerSettingValue*>* settings;
    bool m_settings_isSet;

};

}

#endif /* SWGSchedulerChannelAction_H_ */
