/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGSchedulerChannelAction.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace SWGSDRangel {

SWGSchedulerChannelAction::SWGSchedulerChannelAction(QString* json) {
    init();
    this->fromJson(*json);
}

SWGSchedulerChannelAction::SWGSchedulerChannelAction() {
    device_set_index = 0;
    m_device_set_index_isSet = false;
    device_set_id = nullptr;
    m_device_set_id_isSet = false;
    channel_index = 0;
    m_channel_index_isSet = false;
    channel_id = nullptr;
    m_channel_id_isSet = false;
    action = 0;
    m_action_isSet = false;
    text = nullptr;
    m_text_isSet = false;
    callsign = nullptr;
    m_callsign_isSet = false;
    to = nullptr;
    m_to_isSet = false;
    via = nullptr;
    m_via_isSet = false;
    data = nullptr;
    m_data_isSet = false;
    settings = nullptr;
    m_settings_isSet = false;
}

SWGSchedulerChannelAction::~SWGSchedulerChannelAction() {
    this->cleanup();
}

void
SWGSchedulerChannelAction::init() {
    device_set_index = 0;
    m_device_set_index_isSet = false;
    device_set_id = new QString("");
    m_device_set_id_isSet = false;
    channel_index = 0;
    m_channel_index_isSet = false;
    channel_id = new QString("");
    m_channel_id_isSet = false;
    action = 0;
    m_action_isSet = false;
    text = new QString("");
    m_text_isSet = false;
    callsign = new QString("");
    m_callsign_isSet = false;
    to = new QString("");
    m_to_isSet = false;
    via = new QString("");
    m_via_isSet = false;
    data = new QString("");
    m_data_isSet = false;
    settings = new QList<SWGSchedulerSettingValue*>();
    m_settings_isSet = false;
}

void
SWGSchedulerChannelAction::cleanup() {

    if(device_set_id != nullptr) { 
        delete device_set_id;
    }

    if(channel_id != nullptr) { 
        delete channel_id;
    }

    if(text != nullptr) { 
        delete text;
    }
    if(callsign != nullptr) { 
        delete callsign;
    }
    if(to != nullptr) { 
        delete to;
    }
    if(via != nullptr) { 
        delete via;
    }
    if(data != nullptr) { 
        delete data;
    }
    if(settings != nullptr) { 
        auto arr = settings;
        for(auto o: *arr) { 
            delete o;
        }
        delete settings;
    }
}

SWGSchedulerChannelAction*
SWGSchedulerChannelAction::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGSchedulerChannelAction::fromJsonObject(QJsonObject &pJson) {
    ::SWGSDRangel::setValue(&device_set_index, pJson["deviceSetIndex"], "qint32", "");
    
    ::SWGSDRangel::setValue(&device_set_id, pJson["deviceSetId"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&channel_index, pJson["channelIndex"], "qint32", "");
    
    ::SWGSDRangel::setValue(&channel_id, pJson["channelId"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&action, pJson["action"], "qint32", "");
    
    ::SWGSDRangel::setValue(&text, pJson["text"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&callsign, pJson["callsign"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&to, pJson["to"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&via, pJson["via"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&data, pJson["data"], "QString", "QString");
    
    
    ::SWGSDRangel::setValue(&settings, pJson["settings"], "QList", "SWGSchedulerSettingValue");
}

QString
SWGSchedulerChannelAction::asJson ()
{
    QJsonObject* obj = this->asJsonObject();

    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    delete obj;
    return QString(bytes);
}

QJsonObject*
SWGSchedulerChannelAction::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    if(m_device_set_index_isSet){
        obj->insert("deviceSetIndex", QJsonValue(device_set_index));
    }
    if(device_set_id != nullptr && *device_set_id != QString("")){
        toJsonValue(QString("deviceSetId"), device_set_id, obj, QString("QString"));
    }
    if(m_channel_index_isSet){
        obj->insert("channelIndex", QJsonValue(channel_index));
    }
    if(channel_id != nullptr && *channel_id != QString("")){
        toJsonValue(QString("channelId"), channel_id, obj, QString("QString"));
    }
    if(m_action_isSet){
        obj->insert("action", QJsonValue(action));
    }
    if(text != nullptr && *text != QString("")){
        toJsonValue(QString("text"), text, obj, QString("QString"));
    }
    if(callsign != nullptr && *callsign != QString("")){
        toJsonValue(QString("callsign"), callsign, obj, QString("QString"));
    }
    if(to != nullptr && *to != QString("")){
        toJsonValue(QString("to"), to, obj, QString("QString"));
    }
    if(via != nullptr && *via != QString("")){
        toJsonValue(QString("via"), via, obj, QString("QString"));
    }
    if(data != nullptr && *data != QString("")){
        toJsonValue(QString("data"), data, obj, QString("QString"));
    }
    if(settings && settings->size() > 0){
        toJsonArray((QList<void*>*)settings, obj, "settings", "SWGSchedulerSettingValue");
    }

    return obj;
}

qint32
SWGSchedulerChannelAction::getDeviceSetIndex() {
    return device_set_index;
}
void
SWGSchedulerChannelAction::setDeviceSetIndex(qint32 device_set_index) {
    this->device_set_index = device_set_index;
    this->m_device_set_index_isSet = true;
}

QString*
SWGSchedulerChannelAction::getDeviceSetId() {
    return device_set_id;
}
void
SWGSchedulerChannelAction::setDeviceSetId(QString* device_set_id) {
    this->device_set_id = device_set_id;
    this->m_device_set_id_isSet = true;
}

qint32
SWGSchedulerChannelAction::getChannelIndex() {
    return channel_index;
}
void
SWGSchedulerChannelAction::setChannelIndex(qint32 channel_index) {
    this->channel_index = channel_index;
    this->m_channel_index_isSet = true;
}

QString*
SWGSchedulerChannelAction::getChannelId() {
    return channel_id;
}
void
SWGSchedulerChannelAction::setChannelId(QString* channel_id) {
    this->channel_id = channel_id;
    this->m_channel_id_isSet = true;
}

qint32
SWGSchedulerChannelAction::getAction() {
    return action;
}
void
SWGSchedulerChannelAction::setAction(qint32 action) {
    this->action = action;
    this->m_action_isSet = true;
}

QString*
SWGSchedulerChannelAction::getText() {
    return text;
}
void
SWGSchedulerChannelAction::setText(QString* text) {
    this->text = text;
    this->m_text_isSet = true;
}

QString*
SWGSchedulerChannelAction::getCallsign() {
    return callsign;
}
void
SWGSchedulerChannelAction::setCallsign(QString* callsign) {
    this->callsign = callsign;
    this->m_callsign_isSet = true;
}

QString*
SWGSchedulerChannelAction::getTo() {
    return to;
}
void
SWGSchedulerChannelAction::setTo(QString* to) {
    this->to = to;
    this->m_to_isSet = true;
}

QString*
SWGSchedulerChannelAction::getVia() {
    return via;
}
void
SWGSchedulerChannelAction::setVia(QString* via) {
    this->via = via;
    this->m_via_isSet = true;
}

QString*
SWGSchedulerChannelAction::getData() {
    return data;
}
void
SWGSchedulerChannelAction::setData(QString* data) {
    this->data = data;
    this->m_data_isSet = true;
}

QList<SWGSchedulerSettingValue*>*
SWGSchedulerChannelAction::getSettings() {
    return settings;
}
void
SWGSchedulerChannelAction::setSettings(QList<SWGSchedulerSettingValue*>* settings) {
    this->settings = settings;
    this->m_settings_isSet = true;
}


bool
SWGSchedulerChannelAction::isSet(){
    bool isObjectUpdated = false;
    do{
        if(m_device_set_index_isSet){
            isObjectUpdated = true; break;
        }
        if(device_set_id && *device_set_id != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_channel_index_isSet){
            isObjectUpdated = true; break;
        }
        if(channel_id && *channel_id != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_action_isSet){
            isObjectUpdated = true; break;
        }
        if(text && *text != QString("")){
            isObjectUpdated = true; break;
        }
        if(callsign && *callsign != QString("")){
            isObjectUpdated = true; break;
        }
        if(to && *to != QString("")){
            isObjectUpdated = true; break;
        }
        if(via && *via != QString("")){
            isObjectUpdated = true; break;
        }
        if(data && *data != QString("")){
            isObjectUpdated = true; break;
        }
        if(settings && (settings->size() > 0)){
            isObjectUpdated = true; break;
        }
    }while(false);
    return isObjectUpdated;
}
}

