/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGSchedulerSettingValue.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace SWGSDRangel {

SWGSchedulerSettingValue::SWGSchedulerSettingValue(QString* json) {
    init();
    this->fromJson(*json);
}

SWGSchedulerSettingValue::SWGSchedulerSettingValue() {
    name = nullptr;
    m_name_isSet = false;
    value = nullptr;
    m_value_isSet = false;
    type = 0;
    m_type_isSet = false;
}

SWGSchedulerSettingValue::~SWGSchedulerSettingValue() {
    this->cleanup();
}

void
SWGSchedulerSettingValue::init() {
    name = new QString("");
    m_name_isSet = false;
    value = new QString("");
    m_value_isSet = false;
    type = 0;
    m_type_isSet = false;
}

void
SWGSchedulerSettingValue::cleanup() {
    if(name != nullptr) { 
        delete name;
    }
    if(value != nullptr) { 
        delete value;
    }

}

SWGSchedulerSettingValue*
SWGSchedulerSettingValue::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGSchedulerSettingValue::fromJsonObject(QJsonObject &pJson) {
    ::SWGSDRangel::setValue(&name, pJson["name"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&value, pJson["value"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&type, pJson["type"], "qint32", "");
    
}

QString
SWGSchedulerSettingValue::asJson ()
{
    QJsonObject* obj = this->asJsonObject();

    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    delete obj;
    return QString(bytes);
}

QJsonObject*
SWGSchedulerSettingValue::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    if(name != nullptr && *name != QString("")){
        toJsonValue(QString("name"), name, obj, QString("QString"));
    }
    if(value != nullptr && *value != QString("")){
        toJsonValue(QString("value"), value, obj, QString("QString"));
    }
    if(m_type_isSet){
        obj->insert("type", QJsonValue(type));
    }

    return obj;
}

QString*
SWGSchedulerSettingValue::getName() {
    return name;
}
void
SWGSchedulerSettingValue::setName(QString* name) {
    this->name = name;
    this->m_name_isSet = true;
}

QString*
SWGSchedulerSettingValue::getValue() {
    return value;
}
void
SWGSchedulerSettingValue::setValue(QString* value) {
    this->value = value;
    this->m_value_isSet = true;
}

qint32
SWGSchedulerSettingValue::getType() {
    return type;
}
void
SWGSchedulerSettingValue::setType(qint32 type) {
    this->type = type;
    this->m_type_isSet = true;
}


bool
SWGSchedulerSettingValue::isSet(){
    bool isObjectUpdated = false;
    do{
        if(name && *name != QString("")){
            isObjectUpdated = true; break;
        }
        if(value && *value != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_type_isSet){
            isObjectUpdated = true; break;
        }
    }while(false);
    return isObjectUpdated;
}
}

