/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGSchedulerSettings.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace SWGSDRangel {

SWGSchedulerSettings::SWGSchedulerSettings(QString* json) {
    init();
    this->fromJson(*json);
}

SWGSchedulerSettings::SWGSchedulerSettings() {
    title = nullptr;
    m_title_isSet = false;
    rgb_color = 0;
    m_rgb_color_isSet = false;
    workspace_index = 0;
    m_workspace_index_isSet = false;
    rules = nullptr;
    m_rules_isSet = false;
    rollup_state = nullptr;
    m_rollup_state_isSet = false;
}

SWGSchedulerSettings::~SWGSchedulerSettings() {
    this->cleanup();
}

void
SWGSchedulerSettings::init() {
    title = new QString("");
    m_title_isSet = false;
    rgb_color = 0;
    m_rgb_color_isSet = false;
    workspace_index = 0;
    m_workspace_index_isSet = false;
    rules = new QList<SWGSchedulerRule*>();
    m_rules_isSet = false;
    rollup_state = new SWGRollupState();
    m_rollup_state_isSet = false;
}

void
SWGSchedulerSettings::cleanup() {
    if(title != nullptr) { 
        delete title;
    }


    if(rules != nullptr) { 
        auto arr = rules;
        for(auto o: *arr) { 
            delete o;
        }
        delete rules;
    }
    if(rollup_state != nullptr) { 
        delete rollup_state;
    }
}

SWGSchedulerSettings*
SWGSchedulerSettings::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGSchedulerSettings::fromJsonObject(QJsonObject &pJson) {
    ::SWGSDRangel::setValue(&title, pJson["title"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&rgb_color, pJson["rgbColor"], "qint32", "");
    
    ::SWGSDRangel::setValue(&workspace_index, pJson["workspaceIndex"], "qint32", "");
    
    
    ::SWGSDRangel::setValue(&rules, pJson["rules"], "QList", "SWGSchedulerRule");
    ::SWGSDRangel::setValue(&rollup_state, pJson["rollupState"], "SWGRollupState", "SWGRollupState");
    
}

QString
SWGSchedulerSettings::asJson ()
{
    QJsonObject* obj = this->asJsonObject();

    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    delete obj;
    return QString(bytes);
}

QJsonObject*
SWGSchedulerSettings::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    if(title != nullptr && *title != QString("")){
        toJsonValue(QString("title"), title, obj, QString("QString"));
    }
    if(m_rgb_color_isSet){
        obj->insert("rgbColor", QJsonValue(rgb_color));
    }
    if(m_workspace_index_isSet){
        obj->insert("workspaceIndex", QJsonValue(workspace_index));
    }
    if(rules && rules->size() > 0){
        toJsonArray((QList<void*>*)rules, obj, "rules", "SWGSchedulerRule");
    }
    if((rollup_state != nullptr) && (rollup_state->isSet())){
        toJsonValue(QString("rollupState"), rollup_state, obj, QString("SWGRollupState"));
    }

    return obj;
}

QString*
SWGSchedulerSettings::getTitle() {
    return title;
}
void
SWGSchedulerSettings::setTitle(QString* title) {
    this->title = title;
    this->m_title_isSet = true;
}

qint32
SWGSchedulerSettings::getRgbColor() {
    return rgb_color;
}
void
SWGSchedulerSettings::setRgbColor(qint32 rgb_color) {
    this->rgb_color = rgb_color;
    this->m_rgb_color_isSet = true;
}

qint32
SWGSchedulerSettings::getWorkspaceIndex() {
    return workspace_index;
}
void
SWGSchedulerSettings::setWorkspaceIndex(qint32 workspace_index) {
    this->workspace_index = workspace_index;
    this->m_workspace_index_isSet = true;
}

QList<SWGSchedulerRule*>*
SWGSchedulerSettings::getRules() {
    return rules;
}
void
SWGSchedulerSettings::setRules(QList<SWGSchedulerRule*>* rules) {
    this->rules = rules;
    this->m_rules_isSet = true;
}

SWGRollupState*
SWGSchedulerSettings::getRollupState() {
    return rollup_state;
}
void
SWGSchedulerSettings::setRollupState(SWGRollupState* rollup_state) {
    this->rollup_state = rollup_state;
    this->m_rollup_state_isSet = true;
}


bool
SWGSchedulerSettings::isSet(){
    bool isObjectUpdated = false;
    do{
        if(title && *title != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_rgb_color_isSet){
            isObjectUpdated = true; break;
        }
        if(m_workspace_index_isSet){
            isObjectUpdated = true; break;
        }
        if(rules && (rules->size() > 0)){
            isObjectUpdated = true; break;
        }
        if(rollup_state && rollup_state->isSet()){
            isObjectUpdated = true; break;
        }
    }while(false);
    return isObjectUpdated;
}
}

