/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGSchedulerDeviceSetAction.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace SWGSDRangel {

SWGSchedulerDeviceSetAction::SWGSchedulerDeviceSetAction(QString* json) {
    init();
    this->fromJson(*json);
}

SWGSchedulerDeviceSetAction::SWGSchedulerDeviceSetAction() {
    device_set_index = 0;
    m_device_set_index_isSet = false;
    device_set_id = nullptr;
    m_device_set_id_isSet = false;
    preset_group = nullptr;
    m_preset_group_isSet = false;
    preset_frequency = 0L;
    m_preset_frequency_isSet = false;
    preset_description = nullptr;
    m_preset_description_isSet = false;
    acquisition_action = 0;
    m_acquisition_action_isSet = false;
    file_sink_action = 0;
    m_file_sink_action_isSet = false;
    override_center_frequency = 0;
    m_override_center_frequency_isSet = false;
    center_frequency = 0L;
    m_center_frequency_isSet = false;
    settings = nullptr;
    m_settings_isSet = false;
}

SWGSchedulerDeviceSetAction::~SWGSchedulerDeviceSetAction() {
    this->cleanup();
}

void
SWGSchedulerDeviceSetAction::init() {
    device_set_index = 0;
    m_device_set_index_isSet = false;
    device_set_id = new QString("");
    m_device_set_id_isSet = false;
    preset_group = new QString("");
    m_preset_group_isSet = false;
    preset_frequency = 0L;
    m_preset_frequency_isSet = false;
    preset_description = new QString("");
    m_preset_description_isSet = false;
    acquisition_action = 0;
    m_acquisition_action_isSet = false;
    file_sink_action = 0;
    m_file_sink_action_isSet = false;
    override_center_frequency = 0;
    m_override_center_frequency_isSet = false;
    center_frequency = 0L;
    m_center_frequency_isSet = false;
    settings = new QList<SWGSchedulerSettingValue*>();
    m_settings_isSet = false;
}

void
SWGSchedulerDeviceSetAction::cleanup() {

    if(device_set_id != nullptr) { 
        delete device_set_id;
    }
    if(preset_group != nullptr) { 
        delete preset_group;
    }

    if(preset_description != nullptr) { 
        delete preset_description;
    }




    if(settings != nullptr) { 
        auto arr = settings;
        for(auto o: *arr) { 
            delete o;
        }
        delete settings;
    }
}

SWGSchedulerDeviceSetAction*
SWGSchedulerDeviceSetAction::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGSchedulerDeviceSetAction::fromJsonObject(QJsonObject &pJson) {
    ::SWGSDRangel::setValue(&device_set_index, pJson["deviceSetIndex"], "qint32", "");
    
    ::SWGSDRangel::setValue(&device_set_id, pJson["deviceSetId"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&preset_group, pJson["presetGroup"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&preset_frequency, pJson["presetFrequency"], "qint64", "");
    
    ::SWGSDRangel::setValue(&preset_description, pJson["presetDescription"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&acquisition_action, pJson["acquisitionAction"], "qint32", "");
    
    ::SWGSDRangel::setValue(&file_sink_action, pJson["fileSinkAction"], "qint32", "");
    
    ::SWGSDRangel::setValue(&override_center_frequency, pJson["overrideCenterFrequency"], "qint32", "");
    
    ::SWGSDRangel::setValue(&center_frequency, pJson["centerFrequency"], "qint64", "");
    
    
    ::SWGSDRangel::setValue(&settings, pJson["settings"], "QList", "SWGSchedulerSettingValue");
}

QString
SWGSchedulerDeviceSetAction::asJson ()
{
    QJsonObject* obj = this->asJsonObject();

    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    delete obj;
    return QString(bytes);
}

QJsonObject*
SWGSchedulerDeviceSetAction::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    if(m_device_set_index_isSet){
        obj->insert("deviceSetIndex", QJsonValue(device_set_index));
    }
    if(device_set_id != nullptr && *device_set_id != QString("")){
        toJsonValue(QString("deviceSetId"), device_set_id, obj, QString("QString"));
    }
    if(preset_group != nullptr && *preset_group != QString("")){
        toJsonValue(QString("presetGroup"), preset_group, obj, QString("QString"));
    }
    if(m_preset_frequency_isSet){
        obj->insert("presetFrequency", QJsonValue(preset_frequency));
    }
    if(preset_description != nullptr && *preset_description != QString("")){
        toJsonValue(QString("presetDescription"), preset_description, obj, QString("QString"));
    }
    if(m_acquisition_action_isSet){
        obj->insert("acquisitionAction", QJsonValue(acquisition_action));
    }
    if(m_file_sink_action_isSet){
        obj->insert("fileSinkAction", QJsonValue(file_sink_action));
    }
    if(m_override_center_frequency_isSet){
        obj->insert("overrideCenterFrequency", QJsonValue(override_center_frequency));
    }
    if(m_center_frequency_isSet){
        obj->insert("centerFrequency", QJsonValue(center_frequency));
    }
    if(settings && settings->size() > 0){
        toJsonArray((QList<void*>*)settings, obj, "settings", "SWGSchedulerSettingValue");
    }

    return obj;
}

qint32
SWGSchedulerDeviceSetAction::getDeviceSetIndex() {
    return device_set_index;
}
void
SWGSchedulerDeviceSetAction::setDeviceSetIndex(qint32 device_set_index) {
    this->device_set_index = device_set_index;
    this->m_device_set_index_isSet = true;
}

QString*
SWGSchedulerDeviceSetAction::getDeviceSetId() {
    return device_set_id;
}
void
SWGSchedulerDeviceSetAction::setDeviceSetId(QString* device_set_id) {
    this->device_set_id = device_set_id;
    this->m_device_set_id_isSet = true;
}

QString*
SWGSchedulerDeviceSetAction::getPresetGroup() {
    return preset_group;
}
void
SWGSchedulerDeviceSetAction::setPresetGroup(QString* preset_group) {
    this->preset_group = preset_group;
    this->m_preset_group_isSet = true;
}

qint64
SWGSchedulerDeviceSetAction::getPresetFrequency() {
    return preset_frequency;
}
void
SWGSchedulerDeviceSetAction::setPresetFrequency(qint64 preset_frequency) {
    this->preset_frequency = preset_frequency;
    this->m_preset_frequency_isSet = true;
}

QString*
SWGSchedulerDeviceSetAction::getPresetDescription() {
    return preset_description;
}
void
SWGSchedulerDeviceSetAction::setPresetDescription(QString* preset_description) {
    this->preset_description = preset_description;
    this->m_preset_description_isSet = true;
}

qint32
SWGSchedulerDeviceSetAction::getAcquisitionAction() {
    return acquisition_action;
}
void
SWGSchedulerDeviceSetAction::setAcquisitionAction(qint32 acquisition_action) {
    this->acquisition_action = acquisition_action;
    this->m_acquisition_action_isSet = true;
}

qint32
SWGSchedulerDeviceSetAction::getFileSinkAction() {
    return file_sink_action;
}
void
SWGSchedulerDeviceSetAction::setFileSinkAction(qint32 file_sink_action) {
    this->file_sink_action = file_sink_action;
    this->m_file_sink_action_isSet = true;
}

qint32
SWGSchedulerDeviceSetAction::getOverrideCenterFrequency() {
    return override_center_frequency;
}
void
SWGSchedulerDeviceSetAction::setOverrideCenterFrequency(qint32 override_center_frequency) {
    this->override_center_frequency = override_center_frequency;
    this->m_override_center_frequency_isSet = true;
}

qint64
SWGSchedulerDeviceSetAction::getCenterFrequency() {
    return center_frequency;
}
void
SWGSchedulerDeviceSetAction::setCenterFrequency(qint64 center_frequency) {
    this->center_frequency = center_frequency;
    this->m_center_frequency_isSet = true;
}

QList<SWGSchedulerSettingValue*>*
SWGSchedulerDeviceSetAction::getSettings() {
    return settings;
}
void
SWGSchedulerDeviceSetAction::setSettings(QList<SWGSchedulerSettingValue*>* settings) {
    this->settings = settings;
    this->m_settings_isSet = true;
}


bool
SWGSchedulerDeviceSetAction::isSet(){
    bool isObjectUpdated = false;
    do{
        if(m_device_set_index_isSet){
            isObjectUpdated = true; break;
        }
        if(device_set_id && *device_set_id != QString("")){
            isObjectUpdated = true; break;
        }
        if(preset_group && *preset_group != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_preset_frequency_isSet){
            isObjectUpdated = true; break;
        }
        if(preset_description && *preset_description != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_acquisition_action_isSet){
            isObjectUpdated = true; break;
        }
        if(m_file_sink_action_isSet){
            isObjectUpdated = true; break;
        }
        if(m_override_center_frequency_isSet){
            isObjectUpdated = true; break;
        }
        if(m_center_frequency_isSet){
            isObjectUpdated = true; break;
        }
        if(settings && (settings->size() > 0)){
            isObjectUpdated = true; break;
        }
    }while(false);
    return isObjectUpdated;
}
}

