/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGSchedulerRule.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace SWGSDRangel {

SWGSchedulerRule::SWGSchedulerRule(QString* json) {
    init();
    this->fromJson(*json);
}

SWGSchedulerRule::SWGSchedulerRule() {
    id = nullptr;
    m_id_isSet = false;
    name = nullptr;
    m_name_isSet = false;
    enabled = 0;
    m_enabled_isSet = false;
    trigger_type = 0;
    m_trigger_type_isSet = false;
    time = nullptr;
    m_time_isSet = false;
    recurrence = 0;
    m_recurrence_isSet = false;
    event_type = 0;
    m_event_type_isSet = false;
    event_source_id = nullptr;
    m_event_source_id_isSet = false;
    event_data_regex = nullptr;
    m_event_data_regex_isSet = false;
    event_delay = 0;
    m_event_delay_isSet = false;
    event_delay_unit = 0;
    m_event_delay_unit_isSet = false;
    command = nullptr;
    m_command_isSet = false;
    speech = nullptr;
    m_speech_isSet = false;
    device_set_actions = nullptr;
    m_device_set_actions_isSet = false;
    feature_actions = nullptr;
    m_feature_actions_isSet = false;
    last_run = nullptr;
    m_last_run_isSet = false;
}

SWGSchedulerRule::~SWGSchedulerRule() {
    this->cleanup();
}

void
SWGSchedulerRule::init() {
    id = new QString("");
    m_id_isSet = false;
    name = new QString("");
    m_name_isSet = false;
    enabled = 0;
    m_enabled_isSet = false;
    trigger_type = 0;
    m_trigger_type_isSet = false;
    time = new QString("");
    m_time_isSet = false;
    recurrence = 0;
    m_recurrence_isSet = false;
    event_type = 0;
    m_event_type_isSet = false;
    event_source_id = new QString("");
    m_event_source_id_isSet = false;
    event_data_regex = new QString("");
    m_event_data_regex_isSet = false;
    event_delay = 0;
    m_event_delay_isSet = false;
    event_delay_unit = 0;
    m_event_delay_unit_isSet = false;
    command = new QString("");
    m_command_isSet = false;
    speech = new QString("");
    m_speech_isSet = false;
    device_set_actions = new QList<SWGSchedulerDeviceSetAction*>();
    m_device_set_actions_isSet = false;
    feature_actions = new QList<SWGSchedulerFeatureAction*>();
    m_feature_actions_isSet = false;
    last_run = new QString("");
    m_last_run_isSet = false;
}

void
SWGSchedulerRule::cleanup() {
    if(id != nullptr) { 
        delete id;
    }
    if(name != nullptr) { 
        delete name;
    }


    if(time != nullptr) { 
        delete time;
    }


    if(event_source_id != nullptr) { 
        delete event_source_id;
    }
    if(event_data_regex != nullptr) { 
        delete event_data_regex;
    }


    if(command != nullptr) { 
        delete command;
    }
    if(speech != nullptr) { 
        delete speech;
    }
    if(device_set_actions != nullptr) { 
        auto arr = device_set_actions;
        for(auto o: *arr) { 
            delete o;
        }
        delete device_set_actions;
    }
    if(feature_actions != nullptr) { 
        auto arr = feature_actions;
        for(auto o: *arr) { 
            delete o;
        }
        delete feature_actions;
    }
    if(last_run != nullptr) { 
        delete last_run;
    }
}

SWGSchedulerRule*
SWGSchedulerRule::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGSchedulerRule::fromJsonObject(QJsonObject &pJson) {
    ::SWGSDRangel::setValue(&id, pJson["id"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&name, pJson["name"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&enabled, pJson["enabled"], "qint32", "");
    
    ::SWGSDRangel::setValue(&trigger_type, pJson["triggerType"], "qint32", "");
    
    ::SWGSDRangel::setValue(&time, pJson["time"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&recurrence, pJson["recurrence"], "qint32", "");
    
    ::SWGSDRangel::setValue(&event_type, pJson["eventType"], "qint32", "");
    
    ::SWGSDRangel::setValue(&event_source_id, pJson["eventSourceId"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&event_data_regex, pJson["eventDataRegex"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&event_delay, pJson["eventDelay"], "qint32", "");
    
    ::SWGSDRangel::setValue(&event_delay_unit, pJson["eventDelayUnit"], "qint32", "");
    
    ::SWGSDRangel::setValue(&command, pJson["command"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&speech, pJson["speech"], "QString", "QString");
    
    
    ::SWGSDRangel::setValue(&device_set_actions, pJson["deviceSetActions"], "QList", "SWGSchedulerDeviceSetAction");
    
    ::SWGSDRangel::setValue(&feature_actions, pJson["featureActions"], "QList", "SWGSchedulerFeatureAction");
    ::SWGSDRangel::setValue(&last_run, pJson["lastRun"], "QString", "QString");
    
}

QString
SWGSchedulerRule::asJson ()
{
    QJsonObject* obj = this->asJsonObject();

    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    delete obj;
    return QString(bytes);
}

QJsonObject*
SWGSchedulerRule::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    if(id != nullptr && *id != QString("")){
        toJsonValue(QString("id"), id, obj, QString("QString"));
    }
    if(name != nullptr && *name != QString("")){
        toJsonValue(QString("name"), name, obj, QString("QString"));
    }
    if(m_enabled_isSet){
        obj->insert("enabled", QJsonValue(enabled));
    }
    if(m_trigger_type_isSet){
        obj->insert("triggerType", QJsonValue(trigger_type));
    }
    if(time != nullptr && *time != QString("")){
        toJsonValue(QString("time"), time, obj, QString("QString"));
    }
    if(m_recurrence_isSet){
        obj->insert("recurrence", QJsonValue(recurrence));
    }
    if(m_event_type_isSet){
        obj->insert("eventType", QJsonValue(event_type));
    }
    if(event_source_id != nullptr && *event_source_id != QString("")){
        toJsonValue(QString("eventSourceId"), event_source_id, obj, QString("QString"));
    }
    if(event_data_regex != nullptr && *event_data_regex != QString("")){
        toJsonValue(QString("eventDataRegex"), event_data_regex, obj, QString("QString"));
    }
    if(m_event_delay_isSet){
        obj->insert("eventDelay", QJsonValue(event_delay));
    }
    if(m_event_delay_unit_isSet){
        obj->insert("eventDelayUnit", QJsonValue(event_delay_unit));
    }
    if(command != nullptr && *command != QString("")){
        toJsonValue(QString("command"), command, obj, QString("QString"));
    }
    if(speech != nullptr && *speech != QString("")){
        toJsonValue(QString("speech"), speech, obj, QString("QString"));
    }
    if(device_set_actions && device_set_actions->size() > 0){
        toJsonArray((QList<void*>*)device_set_actions, obj, "deviceSetActions", "SWGSchedulerDeviceSetAction");
    }
    if(feature_actions && feature_actions->size() > 0){
        toJsonArray((QList<void*>*)feature_actions, obj, "featureActions", "SWGSchedulerFeatureAction");
    }
    if(last_run != nullptr && *last_run != QString("")){
        toJsonValue(QString("lastRun"), last_run, obj, QString("QString"));
    }

    return obj;
}

QString*
SWGSchedulerRule::getId() {
    return id;
}
void
SWGSchedulerRule::setId(QString* id) {
    this->id = id;
    this->m_id_isSet = true;
}

QString*
SWGSchedulerRule::getName() {
    return name;
}
void
SWGSchedulerRule::setName(QString* name) {
    this->name = name;
    this->m_name_isSet = true;
}

qint32
SWGSchedulerRule::getEnabled() {
    return enabled;
}
void
SWGSchedulerRule::setEnabled(qint32 enabled) {
    this->enabled = enabled;
    this->m_enabled_isSet = true;
}

qint32
SWGSchedulerRule::getTriggerType() {
    return trigger_type;
}
void
SWGSchedulerRule::setTriggerType(qint32 trigger_type) {
    this->trigger_type = trigger_type;
    this->m_trigger_type_isSet = true;
}

QString*
SWGSchedulerRule::getTime() {
    return time;
}
void
SWGSchedulerRule::setTime(QString* time) {
    this->time = time;
    this->m_time_isSet = true;
}

qint32
SWGSchedulerRule::getRecurrence() {
    return recurrence;
}
void
SWGSchedulerRule::setRecurrence(qint32 recurrence) {
    this->recurrence = recurrence;
    this->m_recurrence_isSet = true;
}

qint32
SWGSchedulerRule::getEventType() {
    return event_type;
}
void
SWGSchedulerRule::setEventType(qint32 event_type) {
    this->event_type = event_type;
    this->m_event_type_isSet = true;
}

QString*
SWGSchedulerRule::getEventSourceId() {
    return event_source_id;
}
void
SWGSchedulerRule::setEventSourceId(QString* event_source_id) {
    this->event_source_id = event_source_id;
    this->m_event_source_id_isSet = true;
}

QString*
SWGSchedulerRule::getEventDataRegex() {
    return event_data_regex;
}
void
SWGSchedulerRule::setEventDataRegex(QString* event_data_regex) {
    this->event_data_regex = event_data_regex;
    this->m_event_data_regex_isSet = true;
}

qint32
SWGSchedulerRule::getEventDelay() {
    return event_delay;
}
void
SWGSchedulerRule::setEventDelay(qint32 event_delay) {
    this->event_delay = event_delay;
    this->m_event_delay_isSet = true;
}

qint32
SWGSchedulerRule::getEventDelayUnit() {
    return event_delay_unit;
}
void
SWGSchedulerRule::setEventDelayUnit(qint32 event_delay_unit) {
    this->event_delay_unit = event_delay_unit;
    this->m_event_delay_unit_isSet = true;
}

QString*
SWGSchedulerRule::getCommand() {
    return command;
}
void
SWGSchedulerRule::setCommand(QString* command) {
    this->command = command;
    this->m_command_isSet = true;
}

QString*
SWGSchedulerRule::getSpeech() {
    return speech;
}
void
SWGSchedulerRule::setSpeech(QString* speech) {
    this->speech = speech;
    this->m_speech_isSet = true;
}

QList<SWGSchedulerDeviceSetAction*>*
SWGSchedulerRule::getDeviceSetActions() {
    return device_set_actions;
}
void
SWGSchedulerRule::setDeviceSetActions(QList<SWGSchedulerDeviceSetAction*>* device_set_actions) {
    this->device_set_actions = device_set_actions;
    this->m_device_set_actions_isSet = true;
}

QList<SWGSchedulerFeatureAction*>*
SWGSchedulerRule::getFeatureActions() {
    return feature_actions;
}
void
SWGSchedulerRule::setFeatureActions(QList<SWGSchedulerFeatureAction*>* feature_actions) {
    this->feature_actions = feature_actions;
    this->m_feature_actions_isSet = true;
}

QString*
SWGSchedulerRule::getLastRun() {
    return last_run;
}
void
SWGSchedulerRule::setLastRun(QString* last_run) {
    this->last_run = last_run;
    this->m_last_run_isSet = true;
}


bool
SWGSchedulerRule::isSet(){
    bool isObjectUpdated = false;
    do{
        if(id && *id != QString("")){
            isObjectUpdated = true; break;
        }
        if(name && *name != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_enabled_isSet){
            isObjectUpdated = true; break;
        }
        if(m_trigger_type_isSet){
            isObjectUpdated = true; break;
        }
        if(time && *time != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_recurrence_isSet){
            isObjectUpdated = true; break;
        }
        if(m_event_type_isSet){
            isObjectUpdated = true; break;
        }
        if(event_source_id && *event_source_id != QString("")){
            isObjectUpdated = true; break;
        }
        if(event_data_regex && *event_data_regex != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_event_delay_isSet){
            isObjectUpdated = true; break;
        }
        if(m_event_delay_unit_isSet){
            isObjectUpdated = true; break;
        }
        if(command && *command != QString("")){
            isObjectUpdated = true; break;
        }
        if(speech && *speech != QString("")){
            isObjectUpdated = true; break;
        }
        if(device_set_actions && (device_set_actions->size() > 0)){
            isObjectUpdated = true; break;
        }
        if(feature_actions && (feature_actions->size() > 0)){
            isObjectUpdated = true; break;
        }
        if(last_run && *last_run != QString("")){
            isObjectUpdated = true; break;
        }
    }while(false);
    return isObjectUpdated;
}
}

