/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


#include "SWGSchedulerFeatureAction.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace SWGSDRangel {

SWGSchedulerFeatureAction::SWGSchedulerFeatureAction(QString* json) {
    init();
    this->fromJson(*json);
}

SWGSchedulerFeatureAction::SWGSchedulerFeatureAction() {
    feature_set_index = 0;
    m_feature_set_index_isSet = false;
    feature_index = 0;
    m_feature_index_isSet = false;
    feature_id = nullptr;
    m_feature_id_isSet = false;
    action = 0;
    m_action_isSet = false;
    camera_filename = nullptr;
    m_camera_filename_isSet = false;
    camera_record_raw_fits = 0;
    m_camera_record_raw_fits_isSet = false;
    camera_record_calibrated_media = 0;
    m_camera_record_calibrated_media_isSet = false;
    camera_record_post_processed_media = 0;
    m_camera_record_post_processed_media_isSet = false;
    camera_image_count = 0;
    m_camera_image_count_isSet = false;
    camera_video_duration = 0;
    m_camera_video_duration_isSet = false;
    find_target = nullptr;
    m_find_target_isSet = false;
    settings = nullptr;
    m_settings_isSet = false;
}

SWGSchedulerFeatureAction::~SWGSchedulerFeatureAction() {
    this->cleanup();
}

void
SWGSchedulerFeatureAction::init() {
    feature_set_index = 0;
    m_feature_set_index_isSet = false;
    feature_index = 0;
    m_feature_index_isSet = false;
    feature_id = new QString("");
    m_feature_id_isSet = false;
    action = 0;
    m_action_isSet = false;
    camera_filename = new QString("");
    m_camera_filename_isSet = false;
    camera_record_raw_fits = 0;
    m_camera_record_raw_fits_isSet = false;
    camera_record_calibrated_media = 0;
    m_camera_record_calibrated_media_isSet = false;
    camera_record_post_processed_media = 0;
    m_camera_record_post_processed_media_isSet = false;
    camera_image_count = 0;
    m_camera_image_count_isSet = false;
    camera_video_duration = 0;
    m_camera_video_duration_isSet = false;
    find_target = new QString("");
    m_find_target_isSet = false;
    settings = new QList<SWGSchedulerSettingValue*>();
    m_settings_isSet = false;
}

void
SWGSchedulerFeatureAction::cleanup() {


    if(feature_id != nullptr) { 
        delete feature_id;
    }

    if(camera_filename != nullptr) { 
        delete camera_filename;
    }





    if(find_target != nullptr) { 
        delete find_target;
    }
    if(settings != nullptr) { 
        auto arr = settings;
        for(auto o: *arr) { 
            delete o;
        }
        delete settings;
    }
}

SWGSchedulerFeatureAction*
SWGSchedulerFeatureAction::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGSchedulerFeatureAction::fromJsonObject(QJsonObject &pJson) {
    ::SWGSDRangel::setValue(&feature_set_index, pJson["featureSetIndex"], "qint32", "");
    
    ::SWGSDRangel::setValue(&feature_index, pJson["featureIndex"], "qint32", "");
    
    ::SWGSDRangel::setValue(&feature_id, pJson["featureId"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&action, pJson["action"], "qint32", "");
    
    ::SWGSDRangel::setValue(&camera_filename, pJson["cameraFilename"], "QString", "QString");
    
    ::SWGSDRangel::setValue(&camera_record_raw_fits, pJson["cameraRecordRawFits"], "qint32", "");
    
    ::SWGSDRangel::setValue(&camera_record_calibrated_media, pJson["cameraRecordCalibratedMedia"], "qint32", "");
    
    ::SWGSDRangel::setValue(&camera_record_post_processed_media, pJson["cameraRecordPostProcessedMedia"], "qint32", "");
    
    ::SWGSDRangel::setValue(&camera_image_count, pJson["cameraImageCount"], "qint32", "");
    
    ::SWGSDRangel::setValue(&camera_video_duration, pJson["cameraVideoDuration"], "qint32", "");
    
    ::SWGSDRangel::setValue(&find_target, pJson["findTarget"], "QString", "QString");
    
    
    ::SWGSDRangel::setValue(&settings, pJson["settings"], "QList", "SWGSchedulerSettingValue");
}

QString
SWGSchedulerFeatureAction::asJson ()
{
    QJsonObject* obj = this->asJsonObject();

    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    delete obj;
    return QString(bytes);
}

QJsonObject*
SWGSchedulerFeatureAction::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    if(m_feature_set_index_isSet){
        obj->insert("featureSetIndex", QJsonValue(feature_set_index));
    }
    if(m_feature_index_isSet){
        obj->insert("featureIndex", QJsonValue(feature_index));
    }
    if(feature_id != nullptr && *feature_id != QString("")){
        toJsonValue(QString("featureId"), feature_id, obj, QString("QString"));
    }
    if(m_action_isSet){
        obj->insert("action", QJsonValue(action));
    }
    if(camera_filename != nullptr && *camera_filename != QString("")){
        toJsonValue(QString("cameraFilename"), camera_filename, obj, QString("QString"));
    }
    if(m_camera_record_raw_fits_isSet){
        obj->insert("cameraRecordRawFits", QJsonValue(camera_record_raw_fits));
    }
    if(m_camera_record_calibrated_media_isSet){
        obj->insert("cameraRecordCalibratedMedia", QJsonValue(camera_record_calibrated_media));
    }
    if(m_camera_record_post_processed_media_isSet){
        obj->insert("cameraRecordPostProcessedMedia", QJsonValue(camera_record_post_processed_media));
    }
    if(m_camera_image_count_isSet){
        obj->insert("cameraImageCount", QJsonValue(camera_image_count));
    }
    if(m_camera_video_duration_isSet){
        obj->insert("cameraVideoDuration", QJsonValue(camera_video_duration));
    }
    if(find_target != nullptr && *find_target != QString("")){
        toJsonValue(QString("findTarget"), find_target, obj, QString("QString"));
    }
    if(settings && settings->size() > 0){
        toJsonArray((QList<void*>*)settings, obj, "settings", "SWGSchedulerSettingValue");
    }

    return obj;
}

qint32
SWGSchedulerFeatureAction::getFeatureSetIndex() {
    return feature_set_index;
}
void
SWGSchedulerFeatureAction::setFeatureSetIndex(qint32 feature_set_index) {
    this->feature_set_index = feature_set_index;
    this->m_feature_set_index_isSet = true;
}

qint32
SWGSchedulerFeatureAction::getFeatureIndex() {
    return feature_index;
}
void
SWGSchedulerFeatureAction::setFeatureIndex(qint32 feature_index) {
    this->feature_index = feature_index;
    this->m_feature_index_isSet = true;
}

QString*
SWGSchedulerFeatureAction::getFeatureId() {
    return feature_id;
}
void
SWGSchedulerFeatureAction::setFeatureId(QString* feature_id) {
    this->feature_id = feature_id;
    this->m_feature_id_isSet = true;
}

qint32
SWGSchedulerFeatureAction::getAction() {
    return action;
}
void
SWGSchedulerFeatureAction::setAction(qint32 action) {
    this->action = action;
    this->m_action_isSet = true;
}

QString*
SWGSchedulerFeatureAction::getCameraFilename() {
    return camera_filename;
}
void
SWGSchedulerFeatureAction::setCameraFilename(QString* camera_filename) {
    this->camera_filename = camera_filename;
    this->m_camera_filename_isSet = true;
}

qint32
SWGSchedulerFeatureAction::getCameraRecordRawFits() {
    return camera_record_raw_fits;
}
void
SWGSchedulerFeatureAction::setCameraRecordRawFits(qint32 camera_record_raw_fits) {
    this->camera_record_raw_fits = camera_record_raw_fits;
    this->m_camera_record_raw_fits_isSet = true;
}

qint32
SWGSchedulerFeatureAction::getCameraRecordCalibratedMedia() {
    return camera_record_calibrated_media;
}
void
SWGSchedulerFeatureAction::setCameraRecordCalibratedMedia(qint32 camera_record_calibrated_media) {
    this->camera_record_calibrated_media = camera_record_calibrated_media;
    this->m_camera_record_calibrated_media_isSet = true;
}

qint32
SWGSchedulerFeatureAction::getCameraRecordPostProcessedMedia() {
    return camera_record_post_processed_media;
}
void
SWGSchedulerFeatureAction::setCameraRecordPostProcessedMedia(qint32 camera_record_post_processed_media) {
    this->camera_record_post_processed_media = camera_record_post_processed_media;
    this->m_camera_record_post_processed_media_isSet = true;
}

qint32
SWGSchedulerFeatureAction::getCameraImageCount() {
    return camera_image_count;
}
void
SWGSchedulerFeatureAction::setCameraImageCount(qint32 camera_image_count) {
    this->camera_image_count = camera_image_count;
    this->m_camera_image_count_isSet = true;
}

qint32
SWGSchedulerFeatureAction::getCameraVideoDuration() {
    return camera_video_duration;
}
void
SWGSchedulerFeatureAction::setCameraVideoDuration(qint32 camera_video_duration) {
    this->camera_video_duration = camera_video_duration;
    this->m_camera_video_duration_isSet = true;
}

QString*
SWGSchedulerFeatureAction::getFindTarget() {
    return find_target;
}
void
SWGSchedulerFeatureAction::setFindTarget(QString* find_target) {
    this->find_target = find_target;
    this->m_find_target_isSet = true;
}

QList<SWGSchedulerSettingValue*>*
SWGSchedulerFeatureAction::getSettings() {
    return settings;
}
void
SWGSchedulerFeatureAction::setSettings(QList<SWGSchedulerSettingValue*>* settings) {
    this->settings = settings;
    this->m_settings_isSet = true;
}


bool
SWGSchedulerFeatureAction::isSet(){
    bool isObjectUpdated = false;
    do{
        if(m_feature_set_index_isSet){
            isObjectUpdated = true; break;
        }
        if(m_feature_index_isSet){
            isObjectUpdated = true; break;
        }
        if(feature_id && *feature_id != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_action_isSet){
            isObjectUpdated = true; break;
        }
        if(camera_filename && *camera_filename != QString("")){
            isObjectUpdated = true; break;
        }
        if(m_camera_record_raw_fits_isSet){
            isObjectUpdated = true; break;
        }
        if(m_camera_record_calibrated_media_isSet){
            isObjectUpdated = true; break;
        }
        if(m_camera_record_post_processed_media_isSet){
            isObjectUpdated = true; break;
        }
        if(m_camera_image_count_isSet){
            isObjectUpdated = true; break;
        }
        if(m_camera_video_duration_isSet){
            isObjectUpdated = true; break;
        }
        if(find_target && *find_target != QString("")){
            isObjectUpdated = true; break;
        }
        if(settings && (settings->size() > 0)){
            isObjectUpdated = true; break;
        }
    }while(false);
    return isObjectUpdated;
}
}

