/**
 * SDRangel
 * This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube    ---   Limitations and specifcities:    * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method.   * Preset import and export from/to file is a server only feature.   * Device set focus is a GUI only feature.   * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator   * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time   * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time    --- 
 *
 * OpenAPI spec version: 7.0.0
 * Contact: f4exb06@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGSchedulerFeatureAction.h
 *
 * Feature action executed by a scheduler rule
 */

#ifndef SWGSchedulerFeatureAction_H_
#define SWGSchedulerFeatureAction_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"
#include "export.h"

namespace SWGSDRangel {

class SWG_API SWGSchedulerFeatureAction: public SWGObject {
public:
    SWGSchedulerFeatureAction();
    SWGSchedulerFeatureAction(QString* json);
    virtual ~SWGSchedulerFeatureAction();
    void init();
    void cleanup();

    virtual QString asJson () override;
    virtual QJsonObject* asJsonObject() override;
    virtual void fromJsonObject(QJsonObject &json) override;
    virtual SWGSchedulerFeatureAction* fromJson(QString &jsonString) override;

    qint32 getFeatureSetIndex();
    void setFeatureSetIndex(qint32 feature_set_index);

    qint32 getFeatureIndex();
    void setFeatureIndex(qint32 feature_index);

    QString* getFeatureId();
    void setFeatureId(QString* feature_id);

    qint32 getAction();
    void setAction(qint32 action);

    QString* getCameraFilename();
    void setCameraFilename(QString* camera_filename);

    qint32 getCameraRecordMode();
    void setCameraRecordMode(qint32 camera_record_mode);

    qint32 getCameraImageCount();
    void setCameraImageCount(qint32 camera_image_count);

    qint32 getCameraVideoDuration();
    void setCameraVideoDuration(qint32 camera_video_duration);

    QString* getFindTarget();
    void setFindTarget(QString* find_target);


    virtual bool isSet() override;

private:
    qint32 feature_set_index;
    bool m_feature_set_index_isSet;

    qint32 feature_index;
    bool m_feature_index_isSet;

    QString* feature_id;
    bool m_feature_id_isSet;

    qint32 action;
    bool m_action_isSet;

    QString* camera_filename;
    bool m_camera_filename_isSet;

    qint32 camera_record_mode;
    bool m_camera_record_mode_isSet;

    qint32 camera_image_count;
    bool m_camera_image_count_isSet;

    qint32 camera_video_duration;
    bool m_camera_video_duration_isSet;

    QString* find_target;
    bool m_find_target_isSet;

};

}

#endif /* SWGSchedulerFeatureAction_H_ */
